перенос вульпканина
AdventureTimeSS14/space_station_ADT pull request #120
Opened 2024-07-09 15:00 UTC by Darki255

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2024-07-09 15:01 UTC, Darki255 commented
https://github.com/AdventureTimeSS14/space_station_ADT/issues/52

2024-07-09 19:53 UTC, Darki255 commented
Теперь ждем, когда систему языков перенесут

2024-07-13 08:28 UTC, Ratyyy submitted a review, later dismissed

2024-07-13 08:42 UTC, Schrodinger71 requested changes
в папки Content.Server.ADT

2024-07-13 08:42 UTC, Schrodinger71 commented on Content.Server/Speech/EntitySystems/RoarAccentSystem.cs
> +namespace Content.Server.Speech.EntitySystems;
Что за новый файл среди визардовских

2024-07-13 08:48 UTC, Darki255 commented on Content.Server/Speech/EntitySystems/RoarAccentSystem.cs
> +namespace Content.Server.Speech.EntitySystems;
это было у наших вульп 
![image](https://github.com/user-attachments/assets/127c072e-1252-41bb-a7e3-440eb316d951)
И по смыслу названия акцента понимаем, что при произношение слова где есть буква "р" она троится - типо такого "Рррыба"

2024-07-13 08:50 UTC, Darki255 commented on Content.Server/Speech/EntitySystems/RoarAccentSystem.cs
> +namespace Content.Server.Speech.EntitySystems;
> это было у наших вульп ![image](https://private-user-images.githubusercontent.com/87230164/348460843-127c072e-1252-41bb-a7e3-440eb316d951.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NjA4MDksIm5iZiI6MTcyMDg2MDUwOSwicGF0aCI6Ii84NzIzMDE2NC8zNDg0NjA4NDMtMTI3YzA3MmUtMTI1Mi00MWJiLWE3ZTMtNDQwZWIzMTZkOTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDA4NDgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhODc1MTJkY2JkYTdkZjFlNmJlNmNmMjNhZmY2YTU4Y2I3MDNhMjA0ZTIzMGJkNzVhNjk4ODJkZTFlMDk1YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vtzwek8Ow3ZDdV28_wVO0J4RVCeNhtbyKM3HZHST6DM) И по смыслу названия акцента понимаем, что при произношение слова где есть буква "р" она троится - типо такого "Рррыба"

Ну и к тому, это прописано в системе

2024-07-13 08:52 UTC, Schrodinger71 commented on Content.Server/Speech/EntitySystems/RoarAccentSystem.cs
> +namespace Content.Server.Speech.EntitySystems;
давай давай, сортируем)

2024-07-14 12:56 UTC, Darki255 commented
> в папки Content.Server.ADT

Сделал

2024-07-18 21:50 UTC, Schrodinger71 reviewed
![image](https://github.com/user-attachments/assets/08e8f5bd-1c81-4548-a639-b8d77020b209)

Player 
с большой буквыыыы

2024-07-18 21:50 UTC, Schrodinger71 commented on Resources/Locale/ru-RU/ADT/prototypes/entities/mobs/player/Vulpkanin.ftl
> +ent-MobVulpkanin = Урист МакВульпканин
Resources/Locale/ru-RU/ADT/Entities/Mobs/Player/Vulpkanin.ftl

2024-07-18 22:31 UTC, Schrodinger71 requested changes
Audio
NES --> ADT поменять

Textures вульп тоже попереносить в ADT

2024-07-21 18:45 UTC, Schrodinger71 commented
Чини
```bash
  Error Message:
   SERVER: 0,055s [ERRO] userdb: Load of user data failed: Robust.Shared.Prototypes.UnknownPrototypeException: Unknown DatasetPrototype prototype: firstFemaleVulp
   at Robust.Shared.Prototypes.PrototypeManager.Index[T](String id) in /home/runner/work/space_station_ADT/space_station_ADT/RobustToolbox/Robust.Shared/Prototypes/PrototypeManager.cs:line 257
   ```

2024-07-28 23:08 UTC, Schrodinger71 approved these changes

2024-07-28 23:10 UTC, merged