тотальное обновление спрайтов
AdventureTimeSS14/space_station_ADT pull request #129
Opened 2024-07-12 10:15 UTC by Ratyyy

## Описание PR

**Медиа**

**Проверки**

- [Х] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [Х] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [Х] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [Х] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- tweak: Изменены многие спрайты.

2024-07-12 13:39 UTC, 1Stepka1 commented
Был бы тут Арсений он был ругался
Но тут я
И я буду ругаться
Зачем пытаться сократить мету? Особенно когда ссылки в прошлой мете не указывали конкретно на TG Station. Там где https://github.com/tgstation/tgstation изначально указано пойдет такое сокращение с прикреплением ссылки на репозиторий который в рамках этой меты называется TG Station, в других случаях нет. Насчет урезания ссылок на конкретные изменения тоже сомнительно, но лучше их оставить будет 
![изображение](https://github.com/user-attachments/assets/c81c4e16-15a6-47c1-b890-103615b20f64)

2024-07-12 13:40 UTC, Ratyyy commented
> Был бы тут Арсений он был ругался Но тут я И я буду ругаться Зачем пытаться сократить мету? Особенно когда ссылки в прошлой мете не указывали конкретно на TG Station. Там где https://github.com/tgstation/tgstation изначально указано пойдет такое сокращение с прикреплением ссылки на репозиторий который в рамках этой меты называется TG Station, в других случаях нет. Насчет урезания ссылок на конкретные изменения тоже сомнительно, но лучше их оставить будет ![изображение](https://private-user-images.githubusercontent.com/131589665/348280117-c81c4e16-15a6-47c1-b890-103615b20f64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3OTE4ODgsIm5iZiI6MTcyMDc5MTU4OCwicGF0aCI6Ii8xMzE1ODk2NjUvMzQ4MjgwMTE3LWM4MWM0ZTE2LTE1YTYtNDdjMS1iODkwLTEwMzYxNWIyMGY2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQxMzM5NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzJhYTEwODFkYmM3ODFiYWI5MzEzOWMzZWYzNGJmMGRlZjcyODNiMDhjMzJiYzZjY2M3OWY5NThhYWZiMDJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qoXV7W_BGVkp5POAtZRwWwPp3IoJeXANZFLh2XcOx9s)

хорошо, сейчас буду чинить

2024-07-13 07:22 UTC, Schrodinger71 requested changes

2024-07-13 21:32 UTC, 1Stepka1 commented
Уже выглядит сносно, неплохо

2024-07-13 21:40 UTC, Ratyyy commented
> Уже выглядит сносно, неплохо

так.. значит, можно апрув ревью?

2024-07-14 08:57 UTC, 1Stepka1 approved these changes
Надеюсь ничего не упустил

2024-07-14 08:59 UTC, merged