шинель для кадета СБ
AdventureTimeSS14/space_station_ADT pull request #136
Opened 2024-07-26 10:28 UTC by RipZoro1

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлена шинель для кадета СБ

2024-07-26 10:29 UTC, RipZoro1 commented
Проверю потом

2024-07-26 20:09 UTC, Schrodinger71 commented
![image](https://github.com/user-attachments/assets/aa98ae00-a154-49b0-a5b6-cc4d39189b34)
Предлагаю в описании пра, что пойдёт в чейнж лог, сделать более РПЭшным

2024-07-27 09:26 UTC, 1Stepka1 requested changes
Resources/Locale/ru-RU/ADT/Entities/Clothing/OuterClothing/clothing.ftl переименовать clothing.ftl в coats.ftl
Убрать все изменения из Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/hardsuit.yml и перенести в Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/coats.yml
Почему у какого чертого куска тряпки кадета защита почти как у самой тяжелой брони
Какого хрена текстуры которые добавляются от нас находятся в папке текстур визардов? Перенести в папку ADT с таким же путем
В мете указано состояние воксов но текстур которые относились бы к этому нету,так что убирай часть упоминающих воксов

2024-08-06 11:09 UTC, Schrodinger71 requested changes
https://github.com/AdventureTimeSS14/space_station_ADT/pull/136#issuecomment-2253434995

2024-08-06 22:27 UTC, closed without merging