Maior rxbzz
AdventureTimeSS14/space_station_ADT pull request #137
Opened 2024-07-26 19:51 UTC by RipZoro1

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2024-07-26 19:56 UTC, RipZoro1 commented
блятьб, я делал на сборке, которая поломалась. так что проверить не могу :(

2024-07-27 09:29 UTC, 1Stepka1 requested changes
Описание пра? Что здесь добавляется? Я как по коду смотрю тут и другая херня есть
Напиши конкретно что именно и добавь то что относится конкретно к этому обновлении(что за руны?Что за Event-Cult-of-the-Lamb)

2024-08-08 15:15 UTC, Bolper commented on Resources/Prototypes/ADT/Datasets/Names/cburn_names.yml
> +  - Майор
Майор? Просто Майор? добавивь вариативность имен. Например Майор Оруэл.

2024-08-08 15:17 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Mobs/player/humanoid.yml
> +- type: entity
СССП штуки? Мы же переносим Майора

2024-08-08 15:20 UTC, Schrodinger71 commented on Resources/Prototypes/ADT/Datasets/Names/cburn_names.yml
> +  - Майор
Это первая часть приписки, всё ок, а ВОТ К НАЗВАНИЮ АЙДИШНика вопросы, с хера корвакс `Corvax`
![image](https://github.com/user-attachments/assets/20946278-026f-4c45-8d50-40f2c5265ac7)

2024-08-09 12:30 UTC, closed without merging