Робототехник, КПК, айди
AdventureTimeSS14/space_station_ADT pull request #145
Opened 2024-07-29 01:49 UTC by PyotrIgn

Добавление робототехника.

По какой-то неизвестной мне причине - в интерфейсе нет возможности настройки лодаута для робототехника. Если кто-то уже добавлял профессии - требуется помощь.

2024-07-29 08:23 UTC, Schrodinger71 commented on Resources/Prototypes/Maps/atlas.yml
> +            ADTRoboticist: [ 1, 1 ] #ADT
Так а стоит ли, на офф мапах менять настройки `- type: gameMap`, если всё равно потом нам создавать всё своё кастомное

2024-07-29 08:30 UTC, Schrodinger71 commented on Resources/Prototypes/Roles/Jobs/departments.yml
> +  - ADTRoboticist
Тут добавить коммент # ADT-Roles

2024-07-29 08:30 UTC, Schrodinger71 commented on Resources/Prototypes/Roles/play_time_trackers.yml
> +  id: JobRoboticist
Это всё-таки стоит перенести по путям `Resources/Prototypes/ADT/Roles/play_time_trackers.yml`

2024-07-29 08:31 UTC, Schrodinger71 commented on Resources/Prototypes/ADT/Roles/play_time_trackers.yml
> +#   id: JobRoboticist
hmm

2024-07-29 08:34 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Objects/Devices/encryption_keys.yml
> +    - Binary
Также комментом подписать # ADT Tweak Roboticist

2024-07-29 16:20 UTC, PyotrIgn commented on Resources/Prototypes/Roles/play_time_trackers.yml
> +  id: JobRoboticist
Это я перетыкивал в пустой надежде на то, что лодаут таки начнет высвечиваться. Как и добавление робототеха в манифесты карт

2024-08-01 18:32 UTC, Schrodinger71 requested changes
*Ну вот вроде самое такое..*

2024-08-01 18:32 UTC, Schrodinger71 commented on Resources/Locale/ru-RU/job/job-description.ftl
> +job-description-roboticist = Собирайте боргов, мехов, обслуживайте синтетиков и поражайте (либо пугайте) экипаж своими новейшими разработками.
заменить путь `Resources/Locale/ru-RU/job/job-description.ftl` На `Resources/Locale/ru-RU/ADT/Job/job-description.ftl`

2024-08-01 18:32 UTC, Schrodinger71 commented on Resources/Locale/ru-RU/job/job-names.ftl
> +JobRoboticist = робототехник
заменить путь `Resources/Locale/ru-RU/job/job-names.ftl` на `Resources/Locale/ru-RU/ADT/Job/job-names.ftl`

2024-08-01 18:32 UTC, Schrodinger71 commented on Resources/Prototypes/ADT/Entities/Objects/Misc/identification_cards.yml
> +  id: ADTRoboticistIDCard
Нет локализации, сделать в `Resources/Locale/ru-RU/ADT/Entities/Objects/Misc/identification_cards.ftl`

2024-08-01 18:32 UTC, Schrodinger71 commented on Resources/Locale/ru-RU/ADT/Entities/Markers/Spawners/jobs.ftl
> +    .desc = { ent-SpawnPointJobBase.desc }
`Resources/Locale/ru-RU/ADT/Entities/Markers/Spawners/jobs.ftl` на `/ru-RU/ADT/prototypes/Entities/Markers/Spawners/jobs.ftl`

2024-08-02 08:51 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Roles/Jobs/Science/roboticist.yml
> +    pocket1: BorgTranslatorImplanter
Может лучше всего сразу вколоть ему?

2024-08-02 08:53 UTC, 1Stepka1 commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/roboticist.rsi/meta.json
> +    "copyright": "Sprite by Prazat (discord: prazat911), monkey derivative made by brainfood1183 (github)",
Как я понимаю то что делал празат это в основном респрайты а не совершенно новый спрайт?Верно?

2024-08-02 08:58 UTC, 1Stepka1 commented
И да там человек уже завершил профессию одну так что лучше бы синхронизировать сборку ибо часть файлов которые задействованы здесь уже были изменены им

2024-08-02 17:40 UTC, PyotrIgn commented on Resources/Prototypes/ADT/Roles/Jobs/Science/roboticist.yml
> +    pocket1: BorgTranslatorImplanter
А как реализуемо?

2024-08-02 17:53 UTC, Schrodinger71 commented on Resources/Prototypes/ADT/Roles/Jobs/Science/roboticist.yml
> +    pocket1: BorgTranslatorImplanter
Вот пример прописывания

 ```yml
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
    
    ```

![image](https://github.com/user-attachments/assets/7788b636-3b97-4aa9-952e-abb03409469f)

2024-08-02 22:43 UTC, PyotrIgn commented on Resources/Prototypes/ADT/Roles/Jobs/Science/roboticist.yml
> +    pocket1: BorgTranslatorImplanter
тогда закрываю лодаут с имплантом и делаю таким образом

2024-08-02 22:44 UTC, PyotrIgn commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/roboticist.rsi/meta.json
> +    "copyright": "Sprite by Prazat (discord: prazat911), monkey derivative made by brainfood1183 (github)",
ну так или не так, но визуально он схож с официалами. Потому имеет смысл вписать?

2024-08-02 22:48 UTC, FaDeOkno commented on Resources/Prototypes/ADT/Roles/Jobs/Science/roboticist.yml
> +    pocket1: BorgTranslatorImplanter
> тогда закрываю лодаут с имплантом и делаю таким образом

Можно будет как имплант использовать после обновления языков

2024-08-03 06:09 UTC, 1Stepka1 commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/roboticist.rsi/meta.json
> +    "copyright": "Sprite by Prazat (discord: prazat911), monkey derivative made by brainfood1183 (github)",
да, если это всё таки респрайт то надо оставить авторство прошлого человека и вписать что resprite by и так далее

2024-08-03 22:36 UTC, closed without merging