Ursus
AdventureTimeSS14/space_station_ADT pull request #159
Opened 2024-07-31 11:56 UTC by Schrodinger71

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2024-07-31 23:29 UTC, Schrodinger71 commented
Покажи тесты пж

2024-08-01 11:40 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Damage/ADTmodifiers.yml
> -
Это что ещё

2024-08-07 08:58 UTC, 1Stepka1 commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Mobs/Customization/Markings/Ursus_custom.ftl
Не знаю чем тут приписка custom если оно уже находится в папке Customozation

2024-08-07 09:00 UTC, Schrodinger71 commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Mobs/Customization/Markings/Ursus_custom.ftl
хм... угум

2024-08-07 09:12 UTC, 1Stepka1 requested changes
Я разочарован. Надеюсь ты исправишься

2024-08-07 09:16 UTC, Schrodinger71 commented on Resources/Audio/ADT/Ursus/cry1.ogg
пиздец

2024-08-07 09:16 UTC, Schrodinger71 commented on Resources/Textures/ADT/Mobs/Ursus/custom.rsi/Muzzle2.png
тьфу

2024-08-07 10:11 UTC, 1Stepka1 approved these changes

2024-08-07 10:12 UTC, merged