Гемофилия
AdventureTimeSS14/space_station_ADT pull request #162
Opened 2024-08-01 13:08 UTC by AnderFan

Добавлена гемофилия. В этот раз всё красиво

2024-08-01 13:21 UTC, 1Stepka1 requested changes

2024-08-01 13:21 UTC, 1Stepka1 commented on Resources/Locale/ru-RU/ADT/traits/disabilities.ftl
> +trait-hemophilia-desc = Ваша кровь сворачивается крайне плохо.
Это ещё почему в другом файле хоть в en-US это в другой? Лучше уж что-то одно

2024-08-01 13:21 UTC, 1Stepka1 commented on Content.Server/Body/Components/BloodstreamComponent.cs
> +    [RegisterComponent, Access(typeof(BloodstreamSystem), typeof(ReactionMixerSystem), (typeof(HemophiliaSystem)))]
Лучше пометить это что это мы изменяли, по типу #ADT hemophilia

2024-08-01 13:21 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Traits/speech.yml
> +      modifier: 0.01
Что это делает в speech.yml? Перенести в Resources\Prototypes\ADT\Traits\disabilities.yml

2024-08-02 06:36 UTC, KashRas2 commented on Content.Server/ADT/Hemophilia/HemophiliaSystem.cs
> +namespace Content.Server.Hemophilia;
Стоит поменять неймспейс на `Content.Server.ADT.Hemophilia;`, так как данный файл находится именно в папке АДТ.

2024-08-04 20:37 UTC, Schrodinger71 commented on Content.Shared/ADT/hemophilia/HemophiliaComponent.cs
> +namespace Content.Shared.Traits;
Не совпадает с путём ADT

2024-08-06 08:06 UTC, 1Stepka1 approved these changes
В принципе теперь все устраивает здесь

2024-08-06 10:48 UTC, Darki255 approved these changes
найс

2024-08-06 10:48 UTC, Schrodinger71 reviewed
Хм

2024-08-06 10:49 UTC, Schrodinger71 approved these changes
Теперь нормик наверн

2024-08-06 10:49 UTC, merged