Тотальный реворк языков
AdventureTimeSS14/space_station_ADT pull request #165
Opened 2024-08-02 02:41 UTC by FaDeOkno

## Описание PR

Полный реворк системы языков. Улучшение, оптимизация и доведение до более-менее презентабельного вида.

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.
![image](https://github.com/user-attachments/assets/7d9ab38d-ba16-4eab-9529-fc36ebb25e79)
![image](https://github.com/user-attachments/assets/0389984b-46a4-4386-9e62-ffd64967aade)

**Изменения**

:cl:
- tweak: Полный реворк системы языков.
- tweak: Языки теперь выделяются не названием, а цветом текста.
- tweak: Упрощена система языков.
- tweak: Языковые импланты теперь можно извлечь.
- add: Меню языков теперь открывается при нажатии на кнопку L и имеет кнопку в верхнем меню.

2024-08-02 02:48 UTC, FaDeOkno commented
Починю позже

2024-08-02 08:25 UTC, Schrodinger71 commented on Content.Client/Corvax/TTS/TTSSystem.cs
> +            _contentRoot.AddOrUpdateFile(filePath, ev.Data);
закомментируй, что ты это для языков вносил

2024-08-02 08:25 UTC, Schrodinger71 commented on Content.Client/Input/ContentContexts.cs
> +            human.AddFunction(ContentKeyFunctions.OpenLanguagesMenu);
// ADT LanguagesMenu

2024-08-02 08:25 UTC, Schrodinger71 commented on Content.Client/UserInterface/Systems/MenuBar/Widgets/GameTopMenuBar.xaml
> +        />
Эту вставку тоже стоит прокомментировать <-- ADT Tweak -->

```xaml
<detail>
    <band height="20">
    <!--
      Hello,
         I am a multi-line XML comment
         <staticText>
            <reportElement x="180" y="0" width="200" height="20"/>
            <text><![CDATA[Hello World!]]></text>
          </staticText>
      -->
     </band>
</detail>
```

2024-08-02 08:25 UTC, Schrodinger71 commented on Content.Server/ADT/Language/LanguageSystem.cs
>  namespace Content.Server.Language;
*по моему пути с файлом не сходятся..*

2024-08-02 08:25 UTC, Schrodinger71 commented on Content.Server/ADT/Language/TranslatorImplantSystem.cs
> +namespace Content.Server.Implants;
namespace в ADT переделывать по пути файла 0.о

2024-08-02 08:25 UTC, Schrodinger71 commented on Content.Server/Corvax/TTS/TTSSystem.cs
> +        RaiseNetworkEvent(new PlayTTSEvent(soundData, languageSoundData, language, GetNetEntity(uid)), Filter.Pvs(uid));
Все изменения в офф файлах коммментируй

2024-08-02 08:25 UTC, Schrodinger71 commented on Content.Server/Corvax/TTS/TTSSystem.cs
> +        var obfTtsEvent = new PlayTTSEvent(obfSoundData, obfLangSoundData, language, GetNetEntity(uid), true);
//ADT Tweak Update Language

2024-08-02 08:25 UTC, Schrodinger71 commented on Content.Server/Radio/EntitySystems/HeadsetSystem.cs
> +        }
МХМ

2024-08-02 08:25 UTC, Schrodinger71 commented on Content.Server/Radio/EntitySystems/RadioDeviceSystem.cs
> +        _chat.TrySendInGameICMessage(uid, args.Message, InGameICChatType.Whisper, ChatTransmitRange.GhostRangeLimit, nameOverride: name, checkRadioPrefix: false, language: args.Language);
И это

2024-08-02 08:25 UTC, Schrodinger71 commented on Content.Server/Radio/EntitySystems/RadioSystem.cs
> +        }
И это тоже КОття

2024-08-02 08:43 UTC, 1Stepka1 requested changes
Так же видно что трогаются части визардов,где-то подписано где-то нет,и,а где-то вообще по другому подписанно,Шредингер уже указал некоторые часть,постарайся более единообразно указывать комментарий изменения

2024-08-02 08:43 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Entities/Objects/Device/Translators/handheld.yml
Исходя из преведущих запросов на правку это перенести в Resources/Prototypes/ADT/Entities/Objects/Device/handheld.yml

2024-08-02 08:43 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Entities/Objects/Device/Translators/implanters.yml
Перенесика это все по правильному пути,а именно Resources\Prototypes\ADT\Entities\Objects\Misc\implanters.yml

2024-08-02 08:43 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Entities/Objects/Device/Translators/implants.yml
- type: SubdermalImplant уже говорит о том что это должно быть в subdermal_implants.yml по пути  Resources\Prototypes\ADT\Entities\Objects\Misc\

2024-08-02 13:06 UTC, FaDeOkno commented on Content.Server/ADT/Language/TranslatorImplantSystem.cs
> +namespace Content.Server.Implants;
> namespace в ADT переделывать по пути файла 0.о

Это ведь адски неудобно и некрасиво выглядит

2024-08-02 13:38 UTC, FaDeOkno commented
Ужасы
Поправил всё, вроде

2024-08-04 12:31 UTC, 1Stepka1 commented
Хотел бы увидеть фото или видео демонстрацию работу переводчиков так как по какой-то причине я не смог с ними нормально поработать

2024-08-04 19:55 UTC, Schrodinger71 commented on Content.Server/Corvax/TTS/TTSSystem.cs
> +            "Здесь был котя."
Забавно ^-^

2024-08-04 20:01 UTC, Schrodinger71 requested changes

2024-08-04 20:01 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Mobs/Player/observer.yml
> +    - Universal
добавь что это от тебя изменения # Frontier / Ghosts should understand any language.

2024-08-04 20:01 UTC, Schrodinger71 commented on Resources/keybinds.yml
> +  key: L
Тут тоже отметь что реворк языков

2024-08-04 20:01 UTC, Schrodinger71 commented
В целом неплохо уже

2024-08-06 08:10 UTC, 1Stepka1 approved these changes

2024-08-06 17:20 UTC, FaDeOkno commented on Resources/Prototypes/Entities/Mobs/Player/observer.yml
> +    - Universal
> добавь что это от тебя изменения # Frontier / Ghosts should understand any language.

В этой версии языков от фронтира только генерация сообщения и xaml файл меню

2024-08-06 17:21 UTC, FaDeOkno commented on Resources/Prototypes/Entities/Mobs/Player/observer.yml
> +    - Universal
Укажу, если не указано, сейчас

2024-08-06 17:27 UTC, FaDeOkno commented on Resources/Prototypes/Entities/Mobs/Player/observer.yml
> +    - Universal
Указал

2024-08-06 17:27 UTC, FaDeOkno commented on Resources/keybinds.yml
> +  key: L
Указал

2024-08-06 17:55 UTC, Schrodinger71 approved these changes
Котя пупс

2024-08-06 17:55 UTC, merged