Novakid
AdventureTimeSS14/space_station_ADT pull request #170
Opened 2024-08-02 11:58 UTC by AnderFan

Перенесены новакиды, исправлена устаревшая строчка кода в системе их свечения.
Большое спасибо Шрёдьке и Коте за помощь.

2024-08-04 07:22 UTC, FrisKisDr commented
ХЕХЕ. Мои любимые поломки метаболизма

2024-08-04 19:28 UTC, AnderFan commented
ПОбеда!

2024-08-05 06:56 UTC, AnderFan commented
Гойда!

2024-08-06 08:01 UTC, 1Stepka1 requested changes
Как-то многовато для одного пра правок,но надеюсь ты справишься и сделаешь нашу сборку лучше

2024-08-06 16:37 UTC, AnderFan commented on Resources/Prototypes/Reagents/gases.yml
> +      # Cant be added until I add metabolism effects on reagent removal
не гойда..

2024-08-06 16:46 UTC, AnderFan commented on Resources/Audio/ADT/Novakid/novakid_laugh01.ogg
Я не знаю, я не писал новакдов ;(

2024-08-06 16:50 UTC, 1Stepka1 commented on Resources/Audio/ADT/Novakid/novakid_laugh01.ogg
Ну так узнай откуда взялись эти файлы вообще,там фрискиса спроси или что-то ещё,если не сможешь то всегда можешь поменять на другие где уже известны авторы и лицензия

2024-08-06 19:01 UTC, 1Stepka1 approved these changes

2024-08-06 19:07 UTC, merged