IPC
AdventureTimeSS14/space_station_ADT pull request #171
Opened 2024-08-02 16:29 UTC by nixsilvam404

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2024-08-04 11:51 UTC, 1Stepka1 requested changes
Сейчас буду проверять их в деле,но пока нашел только эти не точности

2024-08-04 11:51 UTC, 1Stepka1 commented on Resources/Locale/ru-RU/ADT/Voice/emotes.ftl
Переместить это в Resources/Locale/ru-RU/ADT/chat/emotes.ftl

2024-08-04 11:51 UTC, 1Stepka1 commented on Resources/Locale/ru-RU/ADT/Species/ipc.ftl
это переместить сюда Resources/Locale/ru-RU/ADT/prototypes/Species

2024-08-04 11:51 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Damage/ADTmodifiers.yml
> +    Piercing: 15
Конечно я все же понимаю что это машина но куда такие значения? по логике конечно их хрен должны пробить но от этого они просто становятся неубиваемые если урон меньше этих значения, то есть урон будет 16 колющего это будет (16-15) * 1.85 = 2

2024-08-04 12:30 UTC, 1Stepka1 commented
Так впринципе работает ходит там делает заряжается лечится и тому подобное, каких-то ошибок не выдавало(у меня по крайней мере)

2024-08-04 20:23 UTC, Schrodinger71 requested changes

2024-08-04 20:23 UTC, Schrodinger71 commented on Content.Shared/Radio/EntitySystems/EncryptionKeySystem.cs
> +
Тут что-то не понятное
`if (component.KeyContainer.ContainedEntities.Count == 0)`
дублирование проверки?

а `if (component.Channels.Count > 0)`
это что?

2024-08-04 20:23 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Structures/Power/apc.yml
Не подписано

2024-08-04 20:54 UTC, nixsilvam404 commented on Resources/Locale/ru-RU/ADT/Species/ipc.ftl
нахуя

2024-08-04 20:59 UTC, Darki255 commented on Resources/Locale/ru-RU/ADT/Species/ipc.ftl
> нахуя

что бы пути одинаковые были. Мне это он тоже написал

2024-08-05 16:18 UTC, nixsilvam404 commented on Resources/Locale/ru-RU/ADT/Species/ipc.ftl
Я вчера смотрела явно не глазами, а чем-то еще.. Перепутала с другим файлом и не поняла сначала зачем его перемещать в другое место.

2024-08-05 21:32 UTC, Darki255 approved these changes

2024-08-05 21:33 UTC, merged