ниан
AdventureTimeSS14/space_station_ADT pull request #175
Opened 2024-08-03 16:43 UTC by Darki255

## Описание PR

Этот ПР переносит ниан
**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлены нианы

2024-08-03 16:52 UTC, Darki255 commented
![image](https://github.com/user-attachments/assets/0df357e3-46f2-4995-858a-09ad46e49fba)

2024-08-03 19:11 UTC, 1Stepka1 commented on Resources/Prototypes/tags.yml
> +  id: ADTMothFriendlyFood
Не порядок, нужно это перенести в tags только в нашей папке. С остальным вроде впоряде

2024-08-03 19:32 UTC, 1Stepka1 approved these changes

2024-08-03 22:08 UTC, Schrodinger71 commented on Resources/Locale/ru-RU/species/species.ftl
> +#species-name-moth = Ниан
вообще он ключи всё-равно считывает даже закоменченные

2024-08-03 22:09 UTC, Schrodinger71 commented on Resources/Locale/ru-RU/species/species.ftl
> +#species-name-moth = Ниан
а то будут у нас дубликаты опять в ftl

2024-08-03 22:10 UTC, Schrodinger71 commented on Resources/Locale/ru-RU/species/species.ftl
> +#species-name-moth = Ниан
надо думать может вообще не трогать

2024-08-03 22:42 UTC, Darki255 commented on Resources/Locale/ru-RU/species/species.ftl
> +#species-name-moth = Ниан
Я проводил локальный тест ямла, мне сначала высветило, что имеется дубликат. После комментариев оно перестало выдавать ошибку с дубликатом

2024-08-04 11:37 UTC, 1Stepka1 requested changes
Кое-что есть

2024-08-04 11:37 UTC, 1Stepka1 commented on Resources/Locale/ru-RU/ADT/Moth/species.ftl
Resources/Locale/ru-RU/ADT/prototypes/Species

2024-08-04 18:00 UTC, 1Stepka1 approved these changes

2024-08-04 20:26 UTC, Schrodinger71 commented on Resources/Locale/ru-RU/species/species.ftl
> +#species-name-moth = Ниан
Оке

2024-08-04 20:34 UTC, Schrodinger71 requested changes

2024-08-04 20:34 UTC, Schrodinger71 commented on Resources/Prototypes/Voice/speech_emote_sounds.yml
Подписать # ADT Tweak что для ниан и объяснить зачем

2024-08-04 20:34 UTC, Schrodinger71 commented on Resources/Prototypes/Species/moth.yml
> +# - type: species
Тут тоже подпиши что для ADT ниан закоментили

2024-08-04 20:34 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Mobs/Species/moth.yml
> +# - type: entity
Ну вообщем везде так

2024-08-04 20:34 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
>      wilhelmProbability: 0.001
Подпиши 
```yml
# Start-ADT Tweak Нианы
Male: MaleMoth
Female: FemaleMoth
Unsexed: MaleMoth
# End-ADT Tweak Нианы
```

2024-08-04 20:34 UTC, Schrodinger71 commented on Resources/Prototypes/Damage/modifier_sets.yml
Тож подпиши что для ADT закоментили и не трогали

2024-08-04 21:23 UTC, Schrodinger71 approved these changes

2024-08-04 21:44 UTC, merged