Сумеречники
AdventureTimeSS14/space_station_ADT pull request #179
Opened 2024-08-05 05:21 UTC by FaDeOkno

## Описание PR

Перенос сумеречников на новую сборку
И НАКОНЕЦ-ТО они названы Shadekin вместо Shadowkin

**Медиа**

![ezgif-2-2197192745](https://github.com/user-attachments/assets/1d34ecf4-417f-4126-a171-31ff009cc7db)

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлено иное отображение одежды на сумеречниках

2024-08-05 10:04 UTC, Schrodinger71 requested changes

2024-08-05 10:04 UTC, Schrodinger71 commented on Resources/Locale/ru-RU/ADT/species/species.ftl
> +species-name-shadekin = Сумеречник
Давайка это по этому пути `Locale\ru-RU\ADT\prototypes\Species\`

2024-08-05 10:04 UTC, Schrodinger71 commented on Resources/Locale/ru-RU/ADT/reagents/meta/biological.ftl
> +reagent-desc-shadekin-blood = Я надеюсь, что ботаники просто раздавили блюспейс помидор.
Таксс ну это по идее сюда `Resources\Locale\re-RU\ADT\prototypes\Reagents\biological.ftl`

2024-08-05 10:04 UTC, Schrodinger71 commented
Может Стёпка ещё чего найдёт

2024-08-05 10:56 UTC, FaDeOkno commented
@Schrodinger71 Пути поправил

2024-08-06 07:39 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Entities/Mobs/Species/shadekin.yml
> +  #   shortscale: 0.85
У нас же есть система ростал,может раскоментить это? Если же это не надо то просто убрать

2024-08-06 07:46 UTC, 1Stepka1 requested changes
А так к остальному вроде вопросов нету

2024-08-06 07:46 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Entities/Mobs/shadekin_ears.yml
Кажись это должно быть в папке Markings

2024-08-06 07:46 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Entities/Mobs/shadekin_tails.yml
Кажись это должно быть в папке Markings

2024-08-06 13:55 UTC, FaDeOkno commented on Resources/Prototypes/ADT/Entities/Mobs/Species/shadekin.yml
> +  #   shortscale: 0.85
На ветке сумеречников её вроде ещё нет

2024-08-06 14:47 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Entities/Mobs/Species/shadekin.yml
> +  #   shortscale: 0.85
Но на сборке она есть

2024-08-06 16:46 UTC, FaDeOkno commented on Resources/Prototypes/ADT/Entities/Mobs/Species/shadekin.yml
> +  #   shortscale: 0.85
Есть, но только тогда тесты полетят. Проще отдельно раскомментить после мерджа

2024-08-06 17:47 UTC, FaDeOkno commented on Resources/Prototypes/ADT/Entities/Mobs/shadekin_ears.yml
Готово

2024-08-06 17:47 UTC, FaDeOkno commented on Resources/Prototypes/ADT/Entities/Mobs/shadekin_tails.yml
Готово

2024-08-06 17:56 UTC, Schrodinger71 commented
Конфликты

2024-08-06 20:18 UTC, Schrodinger71 approved these changes

2024-08-06 20:18 UTC, merged