Перенос Drones & SpaceSEC
AdventureTimeSS14/space_station_ADT pull request #200
Opened 2024-08-07 17:03 UTC by Lonkuk

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

no cl

2024-08-07 19:08 UTC, Bolper reviewed
Resources/Prototypes/ADT/Drones/Drone-Antags/ перенести в Resources/Prototypes/ADT/Entities/Mobs/Silicons/Drones/Drone-Antags/
Resources/Prototypes/ADT/KD/Channels/Channels/DroneAntagChannel.yml перенести в Resources/Prototypes/ADT/radio_channels.yml + убрать русский язык
Resources/Prototypes/ADT/KD/Channels/keys/DroneAntagKey.yml перенести в Resources/Prototypes/ADT/Entities/Objects/Device/encryption_keys.yml + убрать русский язык
Resources/Prototypes/name_identifier_groups.yml перенести в Resources/Prototypes/ADT/name_identifier_groups.yml
Resources/Textures/ADT/Mobs/Silicon/AntagDrones/ перенести в Resources/Textures/ADT/Mobs/Silicon/Drones/AntagDrones/

2024-08-07 20:15 UTC, Lonkuk commented
Это пиздеу

2024-08-07 21:53 UTC, Schrodinger71 commented
Дубликат  `DroneAntag`

```bash
Run dotnet run --project Content.YAMLLinter/Content.YAMLLinter.csproj --no-build
Unhandled exception. NUnit.Framework.AssertionException: CLIENT: 7,472s [ERRO] eng: Exception whilst loading prototypes from /Prototypes/ADT/Drones/Drone-Antags/DroneAntag_Turret.yml:
Robust.Shared.Prototypes.PrototypeLoadException: Duplicate ID: 'DroneAntag' for kind 'Content.Shared.NPC.Prototypes.NpcFactionPrototype
   at Robust.Shared.Prototypes.PrototypeManager.MergeMapping(ExtractedMappingData mapping, Boolean overwrite, Dictionary`2 changed) in /home/runner/work/space_station_ADT/space_station_ADT/RobustToolbox/Robust.Shared/Prototypes/PrototypeManager.YamlLoad.cs:line 213
```

![image](https://github.com/user-attachments/assets/ca266213-2fa3-46bb-ba4b-75f552346756)

2024-08-08 09:13 UTC, Schrodinger71 submitted a review, later dismissed
`Resources/Locale/ru-RU/ADT/Entities/Objects/Misc/identification_cards.ftl`
В этом файле конфликт решить

2024-08-08 17:23 UTC, Lonkuk commented
Yapeee

2024-08-09 10:25 UTC, Bolper reviewed
Стало лучше. Не буду именно запрашивать изменния, ибо уезжаю и проверить времени скорей всего не будет.

2024-08-09 10:25 UTC, Bolper commented on Resources/Textures/ADT/Structures/Doors/Airlocks/Glass/space_sec_shuttle.rsi/meta.json
> +  "copyright": "Taken from CEV-Eris at commit https://github.com/discordia-space/CEV-Eris/commit/14517938186858388656a6aee14bf47af9e9649f - then modified by 20kdc & AJCM-git, glass by Peptide90, modi
Я в этом коммите вижу только html и yml файлы. Откуда pngшки?

2024-08-09 10:25 UTC, Bolper commented on Resources/Textures/ADT/Objects/Misc/space_sec_ids.rsi/meta.json
У меня очень большое ощущение, что это и все сопутсвующие файлы должны быть в Resources/Textures/ADT/Interface/Misc/space_sec_ids.rsi

2024-08-09 16:38 UTC, Bolper commented on Resources/Textures/ADT/Structures/Doors/Airlocks/Glass/space_sec_shuttle.rsi/meta.json
> +  "copyright": "Taken from CEV-Eris at commit https://github.com/discordia-space/CEV-Eris/commit/14517938186858388656a6aee14bf47af9e9649f - then modified by 20kdc & AJCM-git, glass by Peptide90, modi
Хотя на это мжешь забить наверно

2024-08-10 08:45 UTC, Schrodinger71 commented
Жесть тут работа кипит

2024-08-10 18:18 UTC, 1Stepka1 commented
После изменений запрашиваемых от @Bolper я посмотрю что тут такое

2024-08-10 20:23 UTC, Lonkuk commented on Resources/Textures/ADT/Structures/Doors/Airlocks/Glass/space_sec_shuttle.rsi/meta.json
> +  "copyright": "Taken from CEV-Eris at commit https://github.com/discordia-space/CEV-Eris/commit/14517938186858388656a6aee14bf47af9e9649f - then modified by 20kdc & AJCM-git, glass by Peptide90, modi
Png из Resources\Textures\Structures\Doors\Airlocks\Glass\shuttle_syndicate.rsi тупо перекрашенный и мета от туда же + дописал "modified by Lonkuk (github)", где png в том коммите я без понятия

2024-08-10 20:35 UTC, Lonkuk commented on Resources/Textures/ADT/Objects/Misc/space_sec_ids.rsi/meta.json
В ADT/Interface/ текстуры икон для визора, а в ADT/Objects текстуры для айди карт. Всё лежит на правильных местах.

2024-08-13 14:12 UTC, 1Stepka1 requested changes
Изначально я думал тут будет меньше, потом больше
Но вышло нормально учитывая какой щиткод был в прошлом,есть над чем поработать

2024-08-13 14:12 UTC, 1Stepka1 commented on Resources/Textures/ADT/Mobs/Silicon/Drones/AntagDrones/drone-core-advanced.rsi/meta.json
Все ядра из AntagDrones перенести куда надо по аналогии с прототипом

2024-08-13 14:12 UTC, 1Stepka1 commented on Resources/Textures/ADT/Objects/Misc/space_sec_ids.rsi/default-inhand-left.png
Пусть лучше все id карты будут со всеми остальными нежели чем в отдельной папке

2024-08-13 14:12 UTC, 1Stepka1 commented on Resources/Textures/ADT/Structures/Doors/Airlocks/Glass/space_sec_shuttle.rsi/meta.json
> +  "copyright": "Taken from CEV-Eris at commit https://github.com/discordia-space/CEV-Eris/commit/14517938186858388656a6aee14bf47af9e9649f - then modified by 20kdc & AJCM-git, glass by Peptide90, modi
Что за сборище мусора здесь? В коммите ничего нету,подозреваю и авторства других тоже навряд ли относятся к этим спрайтам, исправить и оставить те которые актуальные.

2024-08-13 14:12 UTC, 1Stepka1 commented on Resources/Textures/ADT/Structures/Wallmounts/space_sec_poster.rsi/meta.json
Отдельную папку для одного спрайта и меты вообще не целесообразно,перемести в общую Resources/Textures/ADT/Structures/Wallmounts/signs.rsi

2024-08-14 19:18 UTC, Lonkuk commented
Всё сделано, всё переделано.

2024-08-15 19:12 UTC, 1Stepka1 commented
Такс проверю все сейчас

2024-08-15 19:19 UTC, 1Stepka1 requested changes

2024-08-15 19:19 UTC, 1Stepka1 commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Clothing/Head/hardsuits-helmets.ftl
Неверное название файла,переименовать в hardsuit-helmets.ftl

2024-08-15 19:19 UTC, 1Stepka1 commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Structures/Doors/Airlock/airlock.ftl
Неверное название файла,переименовать в airlocks.ftl

2024-08-17 17:10 UTC, 1Stepka1 approved these changes
Докрутятся тесты можешь мерджить

2024-08-17 17:25 UTC, merged