Черты персонажа
AdventureTimeSS14/space_station_ADT pull request #202
Opened 2024-08-08 04:32 UTC by FaDeOkno

## Описание PR

Дело было вечером, делать было нечего...
Собственно, я реализовал свою давнюю задумку. Положительные черты персонажей, а не только негативные.

**Медиа**

![image](https://github.com/user-attachments/assets/e50da604-d95e-483f-b43d-4b98ac06dff9)

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Переведены черты персонажа на систему поинтов.
- add: Добавлена черты "Ловкий". Она позволяет быстро забираться в шкафы без необходимости открывать их.
- add: Добавлена черты "Осторожный шаг". Она позволяет не получать урон, проходя по осколкам без обуви.
- add: Добавлена черты "Спринтер". Она слегка увеличивает скорость персонажа.
- add: Добавлена черты "Сильный бросок". Она усиливает броски предметов.
- add: Добавлена черты "Паркурщик". Она позволяет быстро забираться на столы.

2024-08-09 14:54 UTC, Schrodinger71 requested changes
![image](https://github.com/user-attachments/assets/2cb9754f-9271-47bf-891e-a4e8f68e6176)

2024-08-10 18:50 UTC, 1Stepka1 commented on Content.Shared/Climbing/Events/CheckClimbSpeedModifiers.cs
Такс а нельзя ли это запихнуть к нам а не визардам?Или как-то явно указать что это не их файлы

2024-08-10 18:50 UTC, 1Stepka1 commented on Content.Shared/Throwing/CheckThrowRangeModifiersEvent.cs
Такс а нельзя ли это запихнуть к нам а не визардам?Или как-то явно указать что это не их файлы

2024-08-10 18:51 UTC, 1Stepka1 requested changes
Сомнительно но окей

2024-08-10 18:51 UTC, 1Stepka1 commented on Content.Shared/Climbing/Systems/ClimbSystem.cs
> +        var args = new DoAfterArgs(EntityManager, user, delay, new ClimbDoAfterEvent(),
Здесь тоже

2024-08-10 18:51 UTC, 1Stepka1 commented on Content.Shared/Throwing/ThrowingSystem.cs
> +
Комментариев бы сюда

2024-08-10 18:51 UTC, 1Stepka1 commented on Resources/Locale/ru-RU/preferences/ui/humanoid-profile-editor.ftl
> +#trait-category-quirks = Причуды
пометь здесь комментарием ADT

2024-08-10 18:51 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Traits/quirks.yml
А что нам мешает не скидывать все в один файл и так же по отдельным тасовать к примеру disabilities.yml для негативных черт а quirks для положительных? Ну или вообще создать под них категорию с другими названиями к примеру positive ,а то тут по намешано всего, вроде в C# нету никаких жестко закодированных путей так что это может быть где угодно.

2024-08-10 18:51 UTC, 1Stepka1 commented on Resources/Prototypes/Traits/disabilities.yml
Не знаю зачем это переносится в нашу папку если Resources/Prototypes/Traits/quirks.yml остались в своей
Тем более большая часть из них изначально визардовская.

2024-08-10 18:52 UTC, 1Stepka1 commented
Ошибки само собою пофиксить

2024-08-11 00:22 UTC, FaDeOkno commented on Resources/Prototypes/Traits/disabilities.yml
Да, херню сделал. Поправлю

2024-08-12 07:44 UTC, 1Stepka1 commented
Я тут смотрю все меняет свою категорию на category: Quirks но это действительно нужно для работы этого или же просто для визуального отображения?

2024-08-12 10:21 UTC, FaDeOkno commented
> Я тут смотрю все меняет свою категорию на category: Quirks но это действительно нужно для работы этого или же просто для визуального отображения?

В каждой категории свои поинты, это нужно для работы

2024-08-12 15:41 UTC, 1Stepka1 approved these changes
Вроде все работает,все нерабочие пофиксили

2024-08-13 08:20 UTC, merged