Smes
AdventureTimeSS14/space_station_ADT pull request #208
Opened 2024-08-08 18:36 UTC by Bolper

## Описание PR

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

Собственно добавлен индустриальный СМЭС и иследование его в РНД

2024-08-08 19:05 UTC, 1Stepka1 requested changes
А так остальное в порядке

2024-08-08 19:05 UTC, 1Stepka1 commented on Resources/Textures/ADT/Structures/Power/industrial_smes.rsi/meta.json
> +  "copyright": "remake of smes that Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/9c7d509354ee030300f63c701da63c17928c3b3b and modified by Swept",
Проверив ссылку я так и не нашел того самого смэса, найди корректный источник откуда взят спрайт или кем он сделан

2024-08-08 19:08 UTC, Bolper commented on Resources/Textures/ADT/Structures/Power/industrial_smes.rsi/meta.json
> +  "copyright": "remake of smes that Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/9c7d509354ee030300f63c701da63c17928c3b3b and modified by Swept",
А я знаю( 
У нас так было. Но хорошо

2024-08-08 19:17 UTC, Bolper commented on Resources/Textures/ADT/Structures/Power/industrial_smes.rsi/meta.json
> +  "copyright": "remake of smes that Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/9c7d509354ee030300f63c701da63c17928c3b3b and modified by Swept",
Моня написать просто с TGstation?

2024-08-09 09:26 UTC, 1Stepka1 approved these changes

2024-08-09 09:28 UTC, merged