Синий щит
AdventureTimeSS14/space_station_ADT pull request #210
Opened 2024-08-09 00:04 UTC by PyotrIgn

Синий Щит с последним апдейтом от Tamioki

2024-08-09 02:48 UTC, PyotrIgn commented
Что завтра добавлю:

Недостающие локализации
Вопрос с лодаутами
Вопрос с револьвером (из него нельзя стрелять в положении, когда клинок не активирован, потому возможно нужна замена на старый или иной аналог)

2024-08-09 16:31 UTC, Schrodinger71 commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Clothing/Head/hats.ftl
> +    .desc = Плотный и устойчивый шлем Офицера Синего Щита на основе шлемов Отряда Быстрого Реагирования. Призван держать воздух внутри, пули снаружи.
Шлем в hаts? мб тут лучше отдельный файл `hardsuit-helmets.ftl`
и да можно к id: приписать `ADT`

2024-08-09 16:31 UTC, Schrodinger71 commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Clothing/Uniforms/jumpsuits.ftl
> +    .desc = Юбка и белая рубашка с погонами Офицера "Синего Щита", уже очень скоро она будет окроплена кроваво-алой кровью врагов НТ, перепутавших его с охранником продуктового магазина 21-го века.
в будущем тут надо будет рассортировать на 2 файла `jumpskirts.ftl` и `jumpsuits.ftl`

2024-08-09 16:31 UTC, Schrodinger71 commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Structures/Storage/Closets/Lockers/lockers.ftl
> +    .desc = { ent-SuitStorageBase.desc }
Ну тож стоит всем прототипам `ADT` приписку

2024-08-09 16:31 UTC, Schrodinger71 commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Storage/bsweaponcase.ftl
> +ent-BaseWeaponCaseNTBS = оружейный кейс
ну тут тож можн к id `ADT`

2024-08-09 16:31 UTC, Schrodinger71 commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Fun/figurines.ftl
> +ent-ToyFigurineBlueshieldOfficer = фигурка офицера синего щита
id: `ADT`

2024-08-09 16:31 UTC, Schrodinger71 commented on Resources/Locale/ru-RU/corvax/hidden-description/hiddenDescription.ftl
> +corvax-hidden-desc-ADTWeaponSaberRevBlueshield-security = [color=#DE3A3A]Это энергетический меч-револьвер! Кажется, это принадлежит Офицеру Синего Щита, очень опасное оружие, если попадёт не в те рук
Не стоит мешать скрытые приписки вещей корвакса и визденов с нашими вещами, лучше поместить это сюда ``\Locale\ru-RU\ADT\hidden-description\hiddenDescription.ftl

2024-08-09 16:31 UTC, Schrodinger71 commented
Так это только папка locаl... КХМ ща дальше пойдём

2024-08-09 17:02 UTC, Schrodinger71 commented on Resources/Prototypes/Access/misc.yml
> +  - BlueShield
```yml
# Можно коментик поставить, и магистрату и ОСЩ
```

2024-08-09 17:02 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Objects/Fun/figurine_boxes.yml
> +        orGroup: SpacemenFig
```yml
# Ну тут тоже откмеентить или в самый низ поместить и прописать ADT Tweak
```

2024-08-09 17:02 UTC, Schrodinger71 commented on Resources/Prototypes/Roles/Jobs/departments.yml
> +  - ADTBlueShieldOfficer
```yml
# ADT-Roles
```

2024-08-09 17:03 UTC, Schrodinger71 commented
Всё уснул

2024-08-09 20:38 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Clothing/Head/hats.ftl
> +    .desc = Плотный и устойчивый шлем Офицера Синего Щита на основе шлемов Отряда Быстрого Реагирования. Призван держать воздух внутри, пули снаружи.
Сдеано

2024-08-09 20:39 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Clothing/Uniforms/jumpsuits.ftl
> +    .desc = Юбка и белая рубашка с погонами Офицера "Синего Щита", уже очень скоро она будет окроплена кроваво-алой кровью врагов НТ, перепутавших его с охранником продуктового магазина 21-го века.
Разбил и перетащил туда локализации других юбок

2024-08-09 20:40 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Structures/Storage/Closets/Lockers/lockers.ftl
> +    .desc = { ent-SuitStorageBase.desc }
Сделано

2024-08-09 20:51 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Storage/bsweaponcase.ftl
> +ent-BaseWeaponCaseNTBS = оружейный кейс
Сделано

2024-08-09 20:52 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Fun/figurines.ftl
> +ent-ToyFigurineBlueshieldOfficer = фигурка офицера синего щита
Сделано

2024-08-09 20:53 UTC, 1Stepka1 commented
Посмотрю завтра,ибо тут что-то доделывать ещё будут

2024-08-09 20:53 UTC, PyotrIgn commented on Resources/Locale/ru-RU/corvax/hidden-description/hiddenDescription.ftl
> +corvax-hidden-desc-ADTWeaponSaberRevBlueshield-security = [color=#DE3A3A]Это энергетический меч-револьвер! Кажется, это принадлежит Офицеру Синего Щита, очень опасное оружие, если попадёт не в те рук
Переместил

2024-08-09 20:54 UTC, PyotrIgn commented on Resources/Prototypes/Access/misc.yml
> +  - BlueShield
Проставил ADT-Tweak

2024-08-09 20:55 UTC, PyotrIgn commented on Resources/Prototypes/Entities/Objects/Fun/figurine_boxes.yml
> +        orGroup: SpacemenFig
Проставил

2024-08-09 20:55 UTC, PyotrIgn commented on Resources/Prototypes/Roles/Jobs/departments.yml
> +  - ADTBlueShieldOfficer
Проставил

2024-08-10 12:52 UTC, 1Stepka1 requested changes
А так в основном уже неплохо

2024-08-10 12:52 UTC, 1Stepka1 commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Clothing/Back/backpack.ftl
> +    .suffix = { "Полный" }
Все Filled версии переместить по пути \prototypes\catalog\fills\ и раскидать куда надо по файлам,это относится ко всем остальным предметам и структурам у которых есть обычная и Filled версия

2024-08-10 12:52 UTC, 1Stepka1 commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Clothing/Neck/cloak.ftl
Переименовать в cloaks

2024-08-10 12:52 UTC, 1Stepka1 commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Clothing/Uniforms/turtleneck.ftl
> +    .desc = Белая удобная водолазка с юбкой для Офицера "Синего Щита" с пришитыми золотыми погонами и ярким именным бейджиком. К сожалению, если вы её наденете, это не будет значить, что вам дадут от
По id предметов(Jumpskirt и Jumpsuit) ясно что куда надо распределить,но точно не сюда

2024-08-10 12:52 UTC, 1Stepka1 commented on Resources/Textures/Clothing/Belt/belt_overlay.rsi/meta.json
> +    },
указать здесь что это от нас изменения

2024-08-10 13:01 UTC, 1Stepka1 commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Clothing/Back/backpack.ftl
Ах да пока заметил,Duffel и Satchel в отдельные файлы, с Filled так же(Satchel патологоанатома потом перенесем или ты можешь сам)

2024-08-10 13:10 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Clothing/Back/backpack.ftl
> +    .suffix = { "Полный" }
По факту филлед версий и нет, это копирование со старой сборки, потому удалю

2024-08-10 13:27 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Clothing/Back/backpack.ftl
> +    .suffix = { "Полный" }
Сделано

2024-08-10 13:28 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Clothing/Neck/cloak.ftl
Сделано

2024-08-10 13:28 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Clothing/Uniforms/turtleneck.ftl
> +    .desc = Белая удобная водолазка с юбкой для Офицера "Синего Щита" с пришитыми золотыми погонами и ярким именным бейджиком. К сожалению, если вы её наденете, это не будет значить, что вам дадут от
Сделано

2024-08-10 13:30 UTC, PyotrIgn commented on Resources/Textures/Clothing/Belt/belt_overlay.rsi/meta.json
> +    },
Сделано

2024-08-10 13:30 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Clothing/Back/backpack.ftl
Раскидал

2024-08-10 18:12 UTC, 1Stepka1 approved these changes
Ладно уж без меты тогда

2024-08-10 18:43 UTC, merged