Лютая сортировка 3: Бл@ть
AdventureTimeSS14/space_station_ADT pull request #211
Opened 2024-08-09 06:59 UTC by FaDeOkno

## Описание PR

Переоткрываю. Ну, по крайней мере пытаюсь.

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Новый антагонист - Фантом!
- add: Множество новых способностей Ревенанту!
- add: Новая роль - Полтергейст!
- tweak: Баф ревенанта!

2024-08-10 11:09 UTC, Schrodinger71 commented on Content.Shared/Revenant/Components/RevenantComponent.cs
> +
Аддтт //

2024-08-10 11:09 UTC, Schrodinger71 commented on Content.Shared/Revenant/Components/RevenantComponent.cs
>      #endregion
/// ААДТ

2024-08-10 11:09 UTC, Schrodinger71 commented on Content.Shared/Revenant/Components/RevenantComponent.cs
>      #endregion
И тут

2024-08-10 11:09 UTC, Schrodinger71 commented on Content.Shared/Revenant/Components/RevenantComponent.cs
КОКОККООТТЯЯ

2024-08-10 11:09 UTC, Schrodinger71 commented on Content.Shared/Revenant/SharedRevenant.cs
Да Котя

2024-08-10 11:09 UTC, Schrodinger71 commented on Content.Shared/Revenant/SharedRevenant.cs
> +}
//АДТ

2024-08-10 11:09 UTC, Schrodinger71 commented on Content.Shared/Store/ListingPrototype.cs
Котька

2024-08-10 11:09 UTC, Schrodinger71 commented on Content.Shared/Store/ListingPrototype.cs
>              PurchaseAmount = PurchaseAmount,
Пупс

2024-08-10 11:09 UTC, Schrodinger71 commented on Content.Shared/Tabletop/SharedTabletopSystem.cs
> +
Котя //АДТ

2024-08-10 11:09 UTC, Schrodinger71 commented on Content.Shared/Weapons/Ranged/HitscanPrototype.cs
>  }
Ты знаешь

2024-08-10 11:09 UTC, Schrodinger71 commented on Resources/Locale/ru-RU/ADT/Clothing/OuterClothing/paranormal.ftl
> +    .desc = Вам либо хочется либо узнать, кто из ваших коллег одержим, либо выглядеть как робокоп.
ЁМАёё ПУти, КОТя

2024-08-10 11:09 UTC, Schrodinger71 commented on Resources/Locale/ru-RU/ADT/Clothing/OuterClothing/paranormal.ftl
> +    .desc = Вам либо хочется либо узнать, кто из ваших коллег одержим, либо выглядеть как робокоп.
должны быть другие

2024-08-10 11:11 UTC, Schrodinger71 requested changes
Атрибуты для АУДИО файлов

2024-08-10 11:12 UTC, Schrodinger71 commented on Resources/Locale/ru-RU/ADT/Clothing/OuterClothing/paranormal.ftl
> +    .desc = Вам либо хочется либо узнать, кто из ваших коллег одержим, либо выглядеть как робокоп.
где `\prototypes\`  в путях

2024-08-11 08:24 UTC, FaDeOkno commented on Content.Server/Bible/BibleSystem.cs
> +
52-53 строки
    // Too much changes and I forgor what is not changed.
    // ADT File.

2024-08-11 08:26 UTC, FaDeOkno commented on Content.Shared/Revenant/Components/RevenantComponent.cs
> +
какой адт, это билять фикс обновы
в мастере так же, максимум в другом месте

2024-08-11 10:09 UTC, PyotrIgn approved these changes
Ну так как в коде я мало что понимаю, а по поводу оформления уже все было сказано - одобряю, нужно затестировать на деве поскорее.

2024-08-13 16:14 UTC, merged