Барки
AdventureTimeSS14/space_station_ADT pull request #216
Opened 2024-08-10 07:33 UTC by FaDeOkno

## Описание PR

Та самая тема, которую я планировал сделать ещё с полгода назад, или раньше. Даёт возможность использовать как голос персонажа не ТТС, а барки.
Игроки могут переключаться между тем, что из этого слышать.

**Медиа**

![image](https://github.com/user-attachments/assets/e34246de-eca6-44e4-b545-b0c51df91ac5)
![image](https://github.com/user-attachments/assets/1ab90804-18e1-49db-9725-398878d7f103)

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлена система барков. Вы можете переключить вид сопровождения текста. ТТС - привычная говорилка, Барки - короткие звуки, имитирующие звуки.

2024-08-12 15:40 UTC, 1Stepka1 requested changes
И к тому же attribution надо для аудио файлов,хотя и ясно что они скорее всего открытые но указать это нужно,к тому же лицензию правильную вписать тоже
И да я видел что меня убрали из запрашиваемых но я уже начал поэтому так

2024-08-12 15:40 UTC, 1Stepka1 commented on Content.Client/VoiceMask/VoiceMaskNameChangeWindow.xaml.cs
> +        // Corvax-TTS-End
Интересно,среди нас шпион,но очень странные выделители,и не только в этом месте но в некоторых других

2024-08-12 15:40 UTC, 1Stepka1 commented on Content.Client/Corvax/TTS/TTSSystem.cs
> +
Опять таки комментарии

2024-08-12 15:40 UTC, 1Stepka1 commented on Content.Server.Database/Migrations/Postgres/20240809114911_Barks.Designer.cs
Вообще есть вариант пометить все эти файлы в Content.Server.Database что они от нас,комментарием там

2024-08-12 15:40 UTC, 1Stepka1 commented on Content.Server/Database/ServerDbBase.cs
> +                profile.HighBarkVar
Снизу уже помечено а сверху нет,интересно получилось

2024-08-12 15:40 UTC, 1Stepka1 commented on Content.Shared/Preferences/HumanoidCharacterProfile.cs
Где-то есть комментарии где-то нет,надо исправить

2024-08-12 15:40 UTC, 1Stepka1 commented on Resources/Locale/ru-RU/ADT/prototypes/Barks/roundstart.ftl
здесь сделать подобно так ибо все же барки это не прототипы так что и путь будет соответствующим,это относится ко всему что связанно с барками
![изображение](https://github.com/user-attachments/assets/ef129d0e-2ef0-4483-8414-78cd6728df08)
Resources/Locale/ru-RU/ADT//Barks/

2024-08-12 15:41 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Barks/roundstart.yml
Название довольно странное, roundstart? а есть типо не roundstart или будут другие категории в будущем?

2024-08-12 16:13 UTC, FaDeOkno commented on Content.Server.Database/Migrations/Postgres/20240809114911_Barks.Designer.cs
В миграциях я ничего трогать не буду, мало ли сломается

2024-08-12 16:15 UTC, 1Stepka1 commented on Content.Server.Database/Migrations/Postgres/20240809114911_Barks.Designer.cs
Тоже думаю об этом,тогда ладно

2024-08-12 16:18 UTC, FaDeOkno commented on Content.Client/VoiceMask/VoiceMaskNameChangeWindow.xaml.cs
> +        // Corvax-TTS-End
ой
ахах

2024-08-12 16:23 UTC, FaDeOkno commented on Resources/Locale/ru-RU/ADT/prototypes/Barks/roundstart.ftl
Прототипы барков есть, и это их названия. Не вижу проблемы

2024-08-12 16:26 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Barks/roundstart.yml
Раз намечено развитие этого то окей

2024-08-12 16:28 UTC, FaDeOkno commented on Resources/Prototypes/ADT/Barks/roundstart.yml
Ну банально удобный редактор барков для панели трюков нужен будет потом

2024-08-13 06:17 UTC, 1Stepka1 approved these changes

2024-08-13 08:19 UTC, merged

2025-05-18 15:05 UTC, Cinkafox commented on Content.Client/ADT/Bark/Systems/SpeechBarksSystem.cs
> +    private async void OnEntitySpoke(PlaySpeechBarksEvent ev)
БЛЯХАХАХААХ! Асинхроная задачка для каждого барка? И зальем в конце вишенькой Task.Delay.. АХФВЫПЗВФПБЛЯЯ Ебать вы Юнити девелопмент))) Пик разработки Сосаки14)))

2025-05-18 15:14 UTC, FaDeOkno commented on Content.Client/ADT/Bark/Systems/SpeechBarksSystem.cs
> +    private async void OnEntitySpoke(PlaySpeechBarksEvent ev)
Сделай лучше, раз так хочется

2025-05-18 15:24 UTC, Cinkafox commented on Content.Client/ADT/Bark/Systems/SpeechBarksSystem.cs
> +    private async void OnEntitySpoke(PlaySpeechBarksEvent ev)
можно же было сделать +- примерно вот так:
```cs
public void SetBark(Entity<SpeechBarksComponent> ent, string message)
{
	ent.Comp.ActiveLetterCount = message.Length;
}


public override void Update(float frameTime)
{
        base.Update(frameTime);

        var query = EntityQueryEnumerator<SpeechBarksComponent, TransformComponent>();
        while (query.MoveNext(out var entity, out var barkComp, out var transformComp))
	{
		if(barkComp.ActiveLetterCount == 0) continue;

		if (barkComp.PassedTime < barkComp.Delay)
        	{
           	 	barkComp.PassedTime += frameTime * 1000;
            		continue;
        	}
        
        	barkComp.PassedTime = 0;

 		if (_player.LocalSession == null)
                	continue;

		if (transformComp.Coordinates.TryDistance(EntityManager, Transform(_player.LocalEntity.Value).Coordinates, out var distance) &&
                    distance > SharedChatSystem.VoiceRange)
                    	continue;

            	_audio.PlayEntity(audioResource.AudioStream, entity, audioParams.WithPitchScale(_random.NextFloat(barkComp.Pitch - 0.1f, barkComp.Pitch + 0.1f)));
		barkComp.ActiveLetterCount--;
	}

}
```
Код примерный, за правильность не ручаюсь, но тут суть в том, чтобы не юзать асинхронку тут ВООБЩЕ и не стопать его по всякой хуйне!

2025-05-18 15:39 UTC, Cinkafox commented on Content.Client/ADT/Bark/Systems/SpeechBarksSystem.cs
> +    private async void OnEntitySpoke(PlaySpeechBarksEvent ev)
> Сделай лучше, раз так хочется

Тут дело не в "лучше не лучше", тут уже дело в ебанной оптимизации. Клиент просто захлебнется в тасках

2025-05-18 15:49 UTC, FaDeOkno commented on Content.Client/ADT/Bark/Systems/SpeechBarksSystem.cs
> +    private async void OnEntitySpoke(PlaySpeechBarksEvent ev)
Ну вообще по факту, признаю. Мне на момент написания просто не хотелось делать через Update

2025-05-18 16:04 UTC, Cinkafox commented on Content.Client/ADT/Bark/Systems/SpeechBarksSystem.cs
> +    private async void OnEntitySpoke(PlaySpeechBarksEvent ev)
всё же стоит переписать хотя бы это. Игроки скажут спасибо за оптимизацию <3