disease
AdventureTimeSS14/space_station_ADT pull request #218
Opened 2024-08-10 16:30 UTC by Darki255

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлены болезни

2024-08-14 20:53 UTC, FaDeOkno requested changes
Убирай ReagentEffect'ы и, желательно, апгрейды машин. Этот пр про болезни.
_Пока что_ это всё

2024-08-14 20:53 UTC, FaDeOkno commented on Content.Shared/Chemistry/Reagent/ReagentEffect.cs
НЕТ такого понятия как ReagentEffect в сборке, и быть не должно. Убирай это и используй EntityEffect

2024-08-14 20:53 UTC, FaDeOkno commented on Content.Shared/Construction/Components/MachinePartComponent.cs
Апгрейды машин вырезали. Уверен, что хочешь вернуть и поддерживать эту механику?

2024-08-14 20:53 UTC, FaDeOkno commented on Content.Server/Backmen/Chemistry/ReagentEffects/ChemCauseDisease.cs
> +public sealed partial class ChemCauseDisease : ReagentEffect
Используй EntityEffect.

2024-08-14 20:53 UTC, FaDeOkno commented on Content.Server/Backmen/Chemistry/ReagentEffects/ChemMiasmaPoolSource.cs
> +public sealed partial class ChemMiasmaPoolSource : ReagentEffect
Используй EntityEffect.

2024-08-14 20:53 UTC, FaDeOkno commented on Content.Server/Backmen/Disease/Components/DiseaseVaccineCreatorComponent.cs
> +    public string MachinePartCost = "Manipulator";
Если ты не собираешься поддерживать механику апгрейда машин, убери это и все референсы.

2024-08-14 20:53 UTC, FaDeOkno commented on Content.Server/Backmen/Disease/DiseaseDiagnosisSystem.cs
> +        if (!TryComp<DiseaseSwabComponent>(args.Used, out var swab))
Я думаю, стоит сделать проверку на то, что предмет вообще есть. Иначе каждое взаимодействие с диагностировщиком будет сопровождаться попапом

2024-08-21 13:05 UTC, Bolper requested changes
Как кажется, тут должно быть великое перенаселение народов в папку ADT

2024-08-23 12:28 UTC, FaDeOkno commented
> Как кажется, тут должно быть великое перенаселение народов в папку ADT

Тут много чего нужно...

2024-09-05 18:38 UTC, Bolper commented
_вопль ужаса_
![Screenshot_2024-09-05-21-38-35-022_com.github.android.png](https://github.com/user-attachments/assets/3d9d250e-57c0-46ea-a41a-05a27de21638)

2024-09-09 21:09 UTC, Schrodinger71 requested changes

2024-09-09 21:09 UTC, Schrodinger71 commented on Content.Server/Medical/HealthAnalyzerSystem.cs
> +            EntityManager.System<DiseaseSystem>().TryAddDisease(args.Target.Value, _proto.Index(uid.Comp.Disease.Value));
Вот это пометить бы

2024-09-26 20:17 UTC, closed without merging