brigmedic
AdventureTimeSS14/space_station_ADT pull request #266
Opened 2024-08-15 07:34 UTC by AnderFan

Перенос бригмедика

2024-08-15 08:29 UTC, AnderFan commented
крч я почти полностью уверен, что YAML Linter просто сошёл с ума

2024-08-16 13:55 UTC, AnderFan commented
Очередная победа чайниковых идеалов!

2024-08-19 08:02 UTC, AnderFan commented
Добавлены медипены во все аварийные запасы и изменены текстурки худов

2024-08-19 11:43 UTC, AnderFan commented
Билд ругается на слишком большое количество предметов в шкафе бригмеда, но шанс того, что в ящике при заказе окажутся все предметы из списка невероятно мал, поэтому я считаю, что это не баг а фича

2024-08-19 15:15 UTC, Bolper commented
Надо будет посмотреть~

2024-08-20 13:54 UTC, FaDeOkno requested changes
Две огромные беды:
- Комментарии
- Пути

2024-08-20 13:54 UTC, FaDeOkno commented on .gitignore
Это что?

2024-08-20 13:54 UTC, FaDeOkno commented on Resources/Locale/ru-RU/ADT/Entities/clothing/eyes/glasses.ftl
ru-RU/ADT/prototypes/...

2024-08-20 13:54 UTC, FaDeOkno commented on Resources/Locale/ru-RU/ADT/Fills/boxes/emergency.ftl
ru-RU/ADT/prototypes/Catalog/Fills/...

2024-08-20 13:54 UTC, FaDeOkno commented on Resources/Locale/ru-RU/ADT/Fills/cargo.ftl
Зачем пустой файл?

2024-08-20 13:54 UTC, FaDeOkno commented on Resources/Locale/ru-RU/ADT/KD/BrigMedic/BrigMedic.ftl
Что за KD? В ADT/prototypes/ раскладывай всё по местам

2024-08-20 13:54 UTC, FaDeOkno commented on Resources/Locale/ru-RU/prototypes/catalog/cargo/cargo-security.ftl
В ADT

2024-08-20 13:54 UTC, FaDeOkno commented on Resources/Prototypes/ADT/Catalog/Fills/Lockers/suit_storage.yml
> +    access: [["Medical"]]
Медицинский доступ? Я думаю, лучше поставить СБ

2024-08-20 13:54 UTC, FaDeOkno commented on Resources/Prototypes/ADT/Entities/Objects/Fun/figurines.yml
> +# ����� ��� ����� �������, ����� ����� ��� ������� �� ����� ����� ����� ��������� �� ������ �����.
Что за символы?

2024-08-20 13:54 UTC, FaDeOkno commented on Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/backpack.yml
В ADT

2024-08-20 13:54 UTC, FaDeOkno commented on Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/duffelbag.yml
В ADT

2024-08-20 13:54 UTC, FaDeOkno commented on Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/satchel.yml
В ADT

2024-08-20 13:54 UTC, FaDeOkno commented on Resources/Prototypes/Catalog/Fills/Boxes/emergency.yml
Комментарии добавь

2024-08-20 13:54 UTC, FaDeOkno commented on Resources/Prototypes/Catalog/Fills/Crates/security.yml
> +  id: ADTCrateSecurityBrigmedic
В ADT!

2024-08-20 13:54 UTC, FaDeOkno commented on Resources/Prototypes/Catalog/Fills/Lockers/security.yml
> +  id: LockerBrigmedicFilledHardsuit
Комментарии!

2024-08-20 13:54 UTC, FaDeOkno commented on Resources/Prototypes/Entities/Markers/Spawners/jobs.yml
> +    job_id: Brigmedic
_Странно, что этих строк не было_
Но комментарии не забывай.

2024-08-20 13:54 UTC, FaDeOkno commented on Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
> +    - JobIconBrigmedic
Комментарии!!

2024-08-20 13:54 UTC, FaDeOkno commented on Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
> +    job: Brigmedic
Комментарии!!

2024-08-20 13:54 UTC, FaDeOkno commented on Resources/Prototypes/Roles/Jobs/Fun/misc_startinggear.yml
> +#  duffelbag: ClothingBackpackDuffelBrigmedicFilled
КОММЕНТАРИИ

2024-08-20 13:54 UTC, FaDeOkno commented on Resources/Prototypes/Roles/Jobs/Security/brigmedic.yml
В ADT

2024-08-20 13:54 UTC, FaDeOkno commented on Resources/Prototypes/Roles/Jobs/departments.yml
> +  - Brigmedic
КОММЕНТАРИИИИИ

2024-08-20 13:54 UTC, FaDeOkno commented on Resources/Prototypes/Roles/play_time_trackers.yml
> +  id: JobBrigmedic
В ADT перенеси трекер

2024-08-20 13:58 UTC, Bolper commented
Я так смотрю.. Ревью который сделал котя. И не понимаю почему всё не по своим местам...

2024-08-20 13:59 UTC, FaDeOkno commented
> Я так смотрю.. Ревью который сделал котя. И не понимаю почему всё не по своим местам...

Забывают все, каждый в разных масштабах

2024-08-20 23:38 UTC, FaDeOkno requested changes
Таакс, ну вродеб теперь всё нормально. Но ещё нужно починить тесты, у тебя жалуется на то, что ты запихнул больше 30 объектов в шкаф

2024-08-21 06:29 UTC, AnderFan commented
Я же уже писал насчёт этого, шанс спавна всех предметов в шкафу крайне мал, что бы ради этого убирать что-то. Там всё нужное

2024-08-21 09:43 UTC, FaDeOkno commented
> Я же уже писал насчёт этого, шанс спавна всех предметов в шкафу крайне мал, что бы ради этого убирать что-то. Там всё нужное

Тесты ломаются. Разве нельзя их убрать в коробку какую, или вручную расставить на мапах?

2024-08-21 09:45 UTC, FaDeOkno commented
+ игра пытается заспавнить объект, который не существует. Хз отсюда ли проблема.

2024-08-21 12:54 UTC, Bolper requested changes
Я лично дождусь, пока не обновят описание ПРа на более нормальное.

2024-08-21 12:54 UTC, Bolper commented on Resources/Textures/Structures/Storage/closet.rsi/brigmedlocked.png
Так. Шкаф бригмедика. Как понимаю он не визардский раз мы его добавляем.
Теперь вопрос, почему это не в папке ADT.

2024-08-21 12:54 UTC, Bolper commented on Resources/Textures/Clothing/Eyes/Hud/sec.rsi/equipped-EYES.png
К чему данные изменения спрайтов худов? В пре написано - перенос бригмедика, про худы там ни слова не сказано. А это означает что? Правильно! Сделать описание ПРа более обширное. по примеру: перенесены: роль бригмедика, шкаф бригмедика, гарнитура и так далее. Ибо перенос бригмедика лично для меня означает - взять добавить роль, без сопутвующей экиперовки. Да даже если брать, что перенос с экипервкой, все равно надо указать, какую именно перенесли.

2024-08-21 16:50 UTC, AnderFan commented on Resources/Textures/Clothing/Eyes/Hud/sec.rsi/equipped-EYES.png
Как будто не старый контент переношу, а новый пишу...
Сэр, да, сэр...

2024-08-21 16:52 UTC, FaDeOkno commented on Resources/Textures/Clothing/Eyes/Hud/sec.rsi/equipped-EYES.png
Разработка она такая

2024-08-21 19:45 UTC, 1Stepka1 reviewed
Как вижу уже большая работа проделана бро,ты красавчик
Осталось неемного.с этими правками думаю ты справишься

2024-08-21 19:45 UTC, 1Stepka1 commented on Resources/Locale/ru-RU/ADT/Catalog/Fills/Backpacks/duffelbag.ftl
Что тут делает одна одинокая запись которая должна быть в Resources/Locale/ru-RU/ADT/prototypes/Catalog/Fills/backpacks/starter_gear/duffelbag.ftl ? Не ясно конечно

2024-08-21 19:45 UTC, 1Stepka1 commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Fun/toys.ftl
> +    .desc = Фигурка, представляющая собой бригмедика - бравого полевого медика сражающегося за жизни своих товарищей, даже под градом пуль и лучей лазерных винтовок.
Ошибся файликом перенеси в figurines.ftl. Он находится в той же папке что и toys.ftl

2024-08-21 19:45 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Entities/Clothing/Uniforms/Jumpskirt.yml
![изображение](https://github.com/user-attachments/assets/2cf79de9-74ad-4624-8fe5-972af8f6f80f)
Пум-пурум думаю тут ясно что надо поправить

2024-08-21 19:45 UTC, 1Stepka1 commented on Resources/Prototypes/Catalog/Fills/Boxes/emergency.yml
> +    - id: SpaceMedipen
С днем комментарии,хоть я вижу что тут изменилась одна строчка и у всех коробках то можно конкретно здесь указать комментарий что добавили космический медипен и он есть во всех BoxSurvival

2024-08-21 19:45 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Guidebook/srp.yml
@Schrodinger71 и Я решили чтобы игроки не путались стоит пока не добавлять срп в меню руководства,так что пока закомментируй эти изменения

2024-08-21 19:45 UTC, 1Stepka1 commented on Resources/Prototypes/Catalog/Fills/Lockers/security.yml
> -    # ADT-WikiBooks-End
Лучше просто закомментить все это

2024-08-21 19:45 UTC, 1Stepka1 commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpskirts.yml
> +    sprite: ADT/Clothing/Uniforms/Jumpskirt/brigmedic.rsi
В Resources/Prototypes/Entities/Clothing/Uniforms/jumpsuits.yml указал комментарии,а тут нет,не дело,исправляйся

2024-08-21 19:45 UTC, 1Stepka1 submitted a review, later dismissed
мискликнул по skill issue

2024-08-21 19:46 UTC, 1Stepka1 commented on Resources/Textures/Structures/Storage/closet.rsi/brigmedlocked.png
Мне конечно интересно для чего,я что-то не нашел чтобы этот спрайт где либо использовался

2024-08-21 19:55 UTC, AnderFan commented on Resources/Locale/ru-RU/ADT/Catalog/Fills/Backpacks/duffelbag.ftl
но это же не начальное снаряжение, нет? Это просто вариация заполненной сумки

2024-08-21 19:58 UTC, 1Stepka1 commented on Resources/Locale/ru-RU/ADT/Catalog/Fills/Backpacks/duffelbag.ftl
Блять,я себя захуярил.не туда смотрел,сорян бро

2024-08-21 20:36 UTC, AnderFan commented on Resources/Textures/Structures/Storage/closet.rsi/brigmedlocked.png
Без него не запускается 0_0

2024-08-21 20:39 UTC, 1Stepka1 commented on Resources/Textures/Structures/Storage/closet.rsi/brigmedlocked.png
Ладно пусть будет

2024-08-22 06:39 UTC, AnderFan commented
АХХАХАХАХАХАХ победа

2024-08-22 13:15 UTC, 1Stepka1 approved these changes

2024-08-22 15:20 UTC, merged