Drask
AdventureTimeSS14/space_station_ADT pull request #28
Opened 2024-06-29 20:26 UTC by nixsilvam404

Перенос драска

no cl

2024-07-03 20:03 UTC, Schrodinger71 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/adt/entities/mobs/player/drask.ftl
> +    .desc = { ent-BaseMobDrask.desc }
Меняем путь

2024-07-03 20:05 UTC, Schrodinger71 commented on Resources/Locale/en-US/species/namepreset.ftl
> +namepreset-firstdashfirstdashfirst = { $first1 }-{ $first2 }-{ $first3 }
/ADT/

2024-07-03 20:28 UTC, 1Stepka1 commented
Вот это тут коммитов, А пока👍

2024-07-03 20:28 UTC, Schrodinger71 commented on Resources/Prototypes/ADT/Entities/Mobs/Species/Drask.yml
> +- type: speechSounds
Resources\Prototypes\ADT\Voice\speech_sounds.yml

2024-07-03 20:29 UTC, Schrodinger71 commented on Resources/Prototypes/ADT/Entities/Mobs/Species/Drask.yml
> +- type: emoteSounds
Resources\Prototypes\ADT\Voice\speech_emote_sounds.yml

2024-07-03 20:31 UTC, Schrodinger71 commented on Resources/Prototypes/ADT/Entities/Mobs/Species/Drask.yml
> +- type: soundCollection
Resources\Prototypes\ADT\SoundCollections\emotes.yml

2024-07-03 20:33 UTC, Schrodinger71 requested changes
Меняем

2024-07-03 20:41 UTC, nixsilvam404 commented
> Меняем

Жесть строгий

2024-07-03 20:43 UTC, Schrodinger71 requested changes
м

2024-07-04 16:20 UTC, nixsilvam404 commented on Resources/Prototypes/ADT/Entities/Mobs/Species/Drask.yml
> +- type: emoteSounds
Это мне тут надо путь прописать в 112 вместо просто названия прототипа, да? Или как?

2024-07-04 17:31 UTC, Schrodinger71 commented on Resources/Prototypes/ADT/Entities/Mobs/Species/Drask.yml
> +- type: emoteSounds
С такими типами emoteSound переместить по такому пути

2024-07-09 22:41 UTC, Schrodinger71 approved these changes
Гуд

2024-07-09 22:43 UTC, merged