[ПЕРЕНОС] Прыжковые ботинки
AdventureTimeSS14/space_station_ADT pull request #297
Opened 2024-08-17 22:15 UTC by Darki255

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

- add: Добавлены прыжковые ботинки
- add: Добавлены прыжковые ботинки синдиката

2024-08-17 22:15 UTC, Darki255 commented
![image](https://github.com/user-attachments/assets/89ec4ce5-ce79-4317-9624-67ddfe92de0f)

2024-08-18 07:43 UTC, 1Stepka1 requested changes

2024-08-18 07:43 UTC, 1Stepka1 commented on Resources/Locale/ru-RU/ADT/Catalog/Store/uplink.ftl
Переименовать в uplink-catalog.ftl

2024-08-18 07:43 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Catalog/uplink.yml
Переименовать в uplink_catalog.yml

2024-08-18 07:43 UTC, 1Stepka1 commented on Resources/Prototypes/Catalog/Fills/Crates/salvage.yml
> +        prob: 0.1
Комментарии

2024-08-18 09:56 UTC, 1Stepka1 approved these changes

2024-08-18 10:14 UTC, merged