Patolog
AdventureTimeSS14/space_station_ADT pull request #30
Opened 2024-06-29 23:08 UTC by Darki255

## Описание PR

Этот ПР переносит патолога
**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

no cl

2024-06-29 23:18 UTC, Darki255 commented
Теперь надо перенести одежду, вещи его, добавить guidbook, спрайты, срп(если есть). Может еще что-то

2024-07-01 10:23 UTC, Darki255 commented
Ну вроде все, осталось решить ямл

2024-07-13 08:10 UTC, Schrodinger71 commented
Хм... а что если везде убрать этот символ `3`

2024-07-13 08:14 UTC, Schrodinger71 commented
бляха, Кекс, зачем цифры в id

2024-07-13 08:23 UTC, Schrodinger71 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/adt/catalog/fills/backpacks/startegear/backpack.ftl
> +ent-ADTClothingBackpackPathologistFilled = { ent-ADTClothingBackpackPathologist }
Давай ка поменяем все пути переводов на `/Locale/ru-RU/ADT/`

2024-07-13 08:37 UTC, Schrodinger71 requested changes
Пути в `/Locale/ru-RU/ADT/` переделать

`Resources/Locale/ru-RU/job/job-names.ftl`
`Resources/Locale/ru-RU/ss14-ru/prototypes/adt/catalog/fills/backpacks/startegear/backpack.ftl`
`Resources/Locale/ru-RU/ss14-ru/prototypes/adt/catalog/fills/backpacks/startegear/duffelbag.ftl`
`Resources/Locale/ru-RU/ss14-ru/prototypes/adt/catalog/fills/backpacks/startegear/satchel.ftl`
`Resources/Locale/ru-RU/ss14-ru/prototypes/adt/catalog/fills/lockers/biohazard.ftl`
И т.д.

2024-07-13 08:57 UTC, Schrodinger71 commented
ну и хуйня

2024-07-22 18:40 UTC, Darki255 commented
пошел нахуй ямл

2024-07-22 21:11 UTC, Darki255 commented
на сегодня все, я устал

2024-07-28 17:10 UTC, Darki255 commented
Я забыл самое важное, добавить его на карты

2024-07-29 16:23 UTC, closed without merging