Перенос всех постеров
AdventureTimeSS14/space_station_ADT pull request #304
Opened 2024-08-18 21:06 UTC by Lonkuk

## Описание PR

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

no cl

2024-08-19 05:40 UTC, Bolper requested changes
И очень объёмно 
Всё постеры и картинки из Resources/Textures/ADT/Objects/Decoration/
Раскидать по Resources/Textures/ADT/Structures/Wallmounts/
Фуух. Вроде всё.

2024-08-19 05:40 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Structures/Wallmount/Signs/posters.yml
Всё картины (paintingBase) мы перемещаем в Resources/Prototypes/ ADT/Entities/Structures/Wallmounts/Signs/paintings.yml
И мне очень не нравится название ADTPosterBaseKek возможно заменить на ADTPosterBase.

2024-08-19 05:40 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Structures/Wallmount/Signs/posters.yml
> +  name: random helloween wall decor spawner
Я чуть чуть почти не доглядел. В общем.. Спавнерам тут не место, по этому мы героически перетаскиваем их вот сюда Resources/Prototypes/ ADT/Entities/Markers/Spawners/Random/posters.yml

2024-08-19 05:40 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Structures/Wallmount/Signs/posters.yml
И раз у нас уже есть база, то не плохо было бы от неё наследоваться

2024-08-19 05:40 UTC, Bolper commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Structures/Wallmount/Signs/halloween.ftl
Перенести эти постеры в Resources/Locale/ru-RU/ADT/prototypes/Entities/Structures/Wallmount/Signs/posters.ftl
И что за флажки... Аа.. Флажки - постеры.. Или стоп... Так
Флажки в Resources/Locale/ru-RU/ADT/prototypes/Entities/Structures/Wallmount/Signs/flags.ftl

2024-08-19 05:40 UTC, Bolper commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Structures/Wallmount/Signs/halloween.ftl
Ладно.. Эти флажки очень спорная вещь как я смотрю. Так что их тоже наверно в Resources/Locale/ru-RU/ADT/prototypes/Entities/Structures/Wallmount/Signs/posters.ftl
Может изменится.

2024-08-19 05:40 UTC, Bolper commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Structures/Wallmount/Signs/ussp.ftl
Это всё в Resources/Locale/ru-RU/ADT/prototypes/Entities/Structures/Wallmount/Signs/posters.ftl

2024-08-19 05:40 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Structures/Wallmount/Signs/posters.yml
> +  id: ADTHalloweenTrianglesBlackOrange1
Кароче что я понял. Надо бы добавить в id слово Poster, чтобы получилось ADT PosterHalloweenTrianglesBlackOrange1
У FTL соответственно тоже изменить 
И ниже тоже.

2024-08-19 05:52 UTC, Bolper commented
Но прежде чем менять, пусть Стёпка за мной перепроверит. @1Stepka1

2024-08-19 07:30 UTC, Bolper commented
И ещё вот
![Screenshot_2024-08-19-10-29-53-025_com.discord.png](https://github.com/user-attachments/assets/d1fbbaec-7d7d-4c39-bdc5-9fb6edb6aada)

2024-08-19 13:38 UTC, Bolper commented
Продублирую на всякий
![изображение](https://github.com/user-attachments/assets/ccc0d3fd-0f82-4520-8f2d-2554dfa7a9f1)

2024-08-19 13:38 UTC, Bolper commented
продублирую на всякий
![изображение](https://github.com/user-attachments/assets/8ada17a1-55d0-4b4b-a170-ac8b6cf8662b)

2024-08-19 13:39 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Structures/Wallmount/Signs/posters.yml
> +  id: ADTHalloweenTrianglesBlackOrange1
Продублирую на всякий
![изображение](https://github.com/user-attachments/assets/036678cb-f935-4450-9407-9b5bef343f69)

2024-08-19 19:06 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Structures/Wallmount/Signs/posters.yml
> +  id: ADTHalloweenTrianglesBlackOrange1
@1Stepka1 твоё слово?

2024-08-19 19:14 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Entities/Structures/Wallmount/Signs/posters.yml
> +  id: ADTHalloweenTrianglesBlackOrange1
@Bolper мое слово когда выполнятся преведущие запросы для правок
в данный момент ничего сказать не могу

2024-08-19 19:19 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Entities/Structures/Wallmount/Signs/posters.yml
> +  id: ADTHalloweenTrianglesBlackOrange1
Но насчет спора то \Wallmounts это все что крепится к стене или хотя бы должно на ней находится чтобы выглядело так как было задумано

2024-08-19 19:20 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Structures/Wallmount/Signs/posters.yml
> +  id: ADTHalloweenTrianglesBlackOrange1
По идеи тоже так думаю. Но как то хз в данном случае

2024-08-19 19:23 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Structures/Wallmount/Signs/posters.yml
> +  id: ADTHalloweenTrianglesBlackOrange1
Но я и не скажу ято оно относится к объектам

2024-08-19 19:30 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Entities/Structures/Wallmount/Signs/posters.yml
> +  id: ADTHalloweenTrianglesBlackOrange1
Не знаешь как в данном случае то посмотри папки что там находится, разница будет на лицо

2024-08-21 12:34 UTC, Bolper approved these changes
Все ок

2024-08-21 13:36 UTC, merged