Защита от стамина урона + блокировка шприцов ухтантам и скафандрам
AdventureTimeSS14/space_station_ADT pull request #314
Opened 2024-08-19 21:38 UTC by FaDeOkno

## Описание PR

Добавил защиту от стана и блокировку шприцов унатхам, а так же мобам в скафандрах

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Котя
- add: Добавлена защита от стана скафандрам ЯО и СБ.
- add: Теперь шприцы не работают на мобов, которые носят скафандры.
- add: Шприцы так же перестали работать на унатхов даже без скафандра.

2024-08-20 08:29 UTC, KashRas2 requested changes
По коду особо чего-то не нашел. По сути всё работает на вызове ивента и всё. Всё гениальное просто, но вот то, что я указал в ревью, желательно исполнить сейчас.

2024-08-20 08:29 UTC, KashRas2 commented on Content.Server/Chemistry/EntitySystems/HypospraySystem.cs
> +        if (!entity.Comp.IgnoreBlockers)
КОММЕНТАРИИ

2024-08-20 08:29 UTC, KashRas2 commented on Content.Shared/Armor/SharedArmorSystem.cs
> +        var examineMarkup = GetArmorExamine(component.Modifiers, component.StaminaModifier);
КОММЕНТАРИИ

2024-08-20 08:29 UTC, KashRas2 commented on Content.Shared/Armor/SharedArmorSystem.cs
> +    private FormattedMessage GetArmorExamine(DamageModifierSet armorModifiers, float staminaModifier)
КОММЕНТАРИИ

2024-08-20 08:29 UTC, KashRas2 commented on Content.Shared/Armor/SharedArmorSystem.cs
> +        msg.PushNewline();
КОММЕНТАРИИ

2024-08-20 08:29 UTC, KashRas2 commented on Content.Shared/Damage/Systems/StaminaSystem.cs
> +        if (!ignoreResistances)
ну опять комментарии

2024-08-20 08:29 UTC, KashRas2 commented on Resources/Locale/ru-RU/armor/armor-examine.ftl
> +armor-stamina-protection-value = - [color=cyan] Стамина [/color] урон снижается на [color=lightblue]{ $value }%[/color].
Я считаю, что локалки лучше к нам в директорию сувать, чтобы пол года не искать.

2024-08-20 08:29 UTC, KashRas2 commented on Content.Server/Chemistry/EntitySystems/SolutionInjectOnEventSystem.cs
> +            // if (!injector.Comp.PierceArmor && _inventory.TryGetSlotEntity(target, "outerClothing", out var suit) && _tag.HasTag(suit.Value, "Hardsuit"))
Спорно на самом деле. Я бы лучше вместо комментариев заменил на то, что ты сделал выше. Как по мне, это смотрелось бы лучше, так как при апстриме так или иначе, но этот файл будет в числе конфликтных

2024-08-20 08:29 UTC, KashRas2 commented on Content.Server/ADT/Chemistry/Systems/InjectorsBlockerSystem.cs
> +using Content.Shared.Database;
Слишком много ненужных юзингов. База данных просто убила прям.

2024-08-20 08:29 UTC, KashRas2 commented on Content.Shared/Chemistry/InjectAttemptEvent.cs
> +using Content.Shared.Inventory;
Данный файл я бы к нам в директорию бы сунул, коль ты тот, что в сервере туда сунул.

2024-08-20 08:31 UTC, FaDeOkno commented on Content.Server/ADT/Chemistry/Systems/InjectorsBlockerSystem.cs
> +using Content.Shared.Database;
> Слишком много ненужных юзингов. База данных просто убила прям.

Я без понятия откуда, VSC сам их прославлял, я не проверил

2024-08-20 12:28 UTC, FaDeOkno commented
> По коду особо чего-то не нашел. По сути всё работает на вызове ивента и всё. Всё гениальное просто, но вот то, что я указал в ревью, желательно исполнить сейчас.

Для такого фикса особо многого и не нужно

2024-08-20 12:31 UTC, KashRas2 submitted a review, later dismissed
Ещё это и всё.

2024-08-20 12:31 UTC, KashRas2 commented on Resources/Locale/ru-RU/chemistry/components/injector-component.ftl
> +injector-component-fail-user = Вы не можете ввести содержимое шприца в { CAPITALIZE($target) }.
Это тоже в отдельный желательно

2024-08-23 17:24 UTC, PyotrIgn approved these changes

2024-08-23 17:24 UTC, merged