Возвращение контента Сирены vol. 1
AdventureTimeSS14/space_station_ADT pull request #315
Opened 2024-08-20 10:30 UTC by Us3rn4me228

## Описание PR
Перенос контента Сирены (и не только) со старой репы. Давно пора было)))

**Медиа**
![image](https://github.com/user-attachments/assets/1781308f-b3bd-4505-a3db-41af3cf3983a)

**Проверки**
- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Username228
- add: Добавлен Р.П.А. - пинпоинтер, указывающий на близжайшую аномалию. Он является хайриском РД.
- tweak: Изменены спрайты крашеров и улучшенного шахтёрского кинжала.
- add: Добавлены Кристаллы с Сирены. Они красиво светятся и из их осколков можно сделать цветные трубы и кулончики.

2024-08-20 20:28 UTC, 1Stepka1 commented
Великое переселение файлов в структуру ADT должно произойти
Иначе никак

2024-08-20 21:10 UTC, Bolper commented
Согласен. Ревью будет чуть позже. Но в нём будет абсолютно тоже самое. Просто больше конкретики

2024-08-21 12:43 UTC, Bolper requested changes
Не... Я устану писать комментарии к данному ревью. Но, как я говорил выше, все необходимо переместить в папки ADT, даже если код взят с Сирены. Как произведутся работы по переносу всего в ADT, то запросите ревью еще раз. Сейчас на это невыносимо смотреть.

2024-08-22 00:01 UTC, Us3rn4me228 commented
kak zaprosit' review

2024-08-22 07:53 UTC, Bolper commented
У тебя я смотрю ещё ошибки остались. Сначало их надо починить. ![Screenshot_2024-08-22-10-51-13-598_com.github.android.png](https://github.com/user-attachments/assets/2d4969cd-a756-4487-95ab-299d0bb31e9f)

Хотя не знаю что за ошибки, не смотрел.

2024-08-29 20:05 UTC, FaDeOkno commented
Ошибки в путях к rsi файлам

2024-08-29 20:05 UTC, FaDeOkno commented
Поправь в прототипах на правильные

2024-10-26 14:59 UTC, Darkiich commented
Закрываю PR по причине долгого отсутствия актива

2024-10-26 14:59 UTC, closed without merging