Приколы атмоса
AdventureTimeSS14/space_station_ADT pull request #329
Opened 2024-08-21 18:02 UTC by Flopochka

## Описание PR

Изменил суфикс труб, добавил печать канистры и закинул рсу и бтт в изучения
**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Крафт канистры для хранения. Изучение РСУ и БТТ

2024-08-21 18:25 UTC, Bolper requested changes
Поверхностное ревью. 
Проведу полноценное попозже

2024-08-21 18:25 UTC, Bolper commented on Resources/Locale/en-US/research/technologies.ftl
> +research-technology-compact-technologies = Matter compression technologies
Это зачем?

2024-08-21 18:25 UTC, Bolper commented on Resources/Locale/ru-RU/research/technologies.ftl
>  research-technology-advanced-tools = Продвинутые инструменты
Эмэ... В папку ADT

2024-08-21 19:36 UTC, Bolper commented
![Screenshot_2024-08-21-22-36-17-027_com android chrome](https://github.com/user-attachments/assets/963ebcd3-455e-44a7-b0fb-357d3614f04e)
Чиним

2024-08-21 20:06 UTC, Bolper requested changes
Так... по идеи все... Я конечно сейчас никакой и ревью на сегодня от меня больше на этом ПРе не ждите. Ночь

2024-08-21 20:06 UTC, Bolper commented on Resources/Prototypes/ADT/Recipes/Lathes/misc.yml
Я пытаюсь понять... Как Автолат распечатает такую здоровенную махину, которая по размерам сравнима с самим автолатом. И да, данная канистра стоит 1к при продаже в карго, как я помню. Выводы сделаешь сам. (могу подтолкнуть --> Убрать)

2024-08-21 20:06 UTC, Bolper commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Я уже сказал про канистру.

2024-08-21 20:09 UTC, Bolper commented
> ![Screenshot_2024-08-21-22-36-17-027_com android chrome](https://private-user-images.githubusercontent.com/169089627/360073685-963ebcd3-455e-44a7-b0fb-357d3614f04e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNzExMjEsIm5iZiI6MTcyNDI3MDgyMSwicGF0aCI6Ii8xNjkwODk2MjcvMzYwMDczNjg1LTk2M2ViY2QzLTQ1NWUtNDRhNy1iMGZiLTM1N2QzNjE0ZjA0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQyMDA3MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjk2ZWY4MDk4YjJhY2JjOGUwYzBlYTFhNzE0OTViZTM5NmQzY2JlM2QxMTg4YTNmNTcyYjMxZWVhY2UxY2ZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UpJ0FbA8VpR2tgHqvFuzeWSyLnVVrlkzdGTrAcGXtVs) Чиним

Хотя... Наверно не в твоем ПРе беда, перезапущу тест

2024-08-21 20:10 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Recipes/Lathes/misc.yml
Канистра сама по себе стоит вроде не сильно дорого,а вот с газом внутри уже да,но помню визарды урезали цену обычным газам и канистры подешевели

2024-08-21 20:11 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Recipes/Lathes/misc.yml
Хотя нет все таки она 1000 стоит

2024-08-21 20:16 UTC, Bolper commented on Resources/Prototypes/ADT/Recipes/Lathes/misc.yml
Нет, пустая - 1к
Я перепроверил и по родителю и в игре

2024-08-21 22:56 UTC, Lonkuk commented
https://github.com/AdventureTimeSS14/space_station_ADT/actions/runs/10495808264/job/29078044084?pr=329#step:10:16
Жалуется что есть изучения, но невозможно сделать на автолатах.
Всё что изучается нужно добавить в Resources\Prototypes\Entities\Structures\Machines\lathe.yml

2024-08-22 07:49 UTC, Bolper commented
> ![image](https://github.com/user-attachments/assets/9f07c1d7-3275-4d93-867e-395fc3c94537)
> Жалуется что есть изучения, но невозможно сделать на автолатах.
> Всё что изучается нужно добавить в Resources\Prototypes\Entities\Structures\Machines\lathe.yml

А да, красавчик
Так и есть.

2024-08-22 17:51 UTC, Flopochka commented on Resources/Locale/ru-RU/ADT/research/technologies.ftl
у офов вся локализация технологий в одном файле так что делаю как они ток в ADT

2024-08-22 17:52 UTC, Flopochka commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Блюспейс канистра выстреливается из автолата, цены починил

2024-08-23 10:26 UTC, Bolper requested changes
Я душнила я гандон

2024-08-23 10:26 UTC, Bolper commented on Resources/Prototypes/Entities/Structures/Storage/Canisters/gas_canisters.yml
> +      price: 250 #ADT Tweak
Всё бы хорошо. Но заместо того чтобы просто писать ADT Tweak надо написать предыдущую цену. Тобишь ADT Tweak 1000

2024-08-23 10:37 UTC, Bolper approved these changes
Как хорошо быть гандоном

2024-08-23 11:00 UTC, FaDeOkno commented on Resources/Prototypes/Entities/Structures/Storage/Canisters/gas_canisters.yml
> +      price: 250 #ADT Tweak
> Всё бы хорошо. Но заместо того чтобы просто писать ADT Tweak надо написать предыдущую цену. Тобишь ADT Tweak 1000

А зачем?

2024-08-23 11:13 UTC, Bolper commented on Resources/Prototypes/Entities/Structures/Storage/Canisters/gas_canisters.yml
> +      price: 250 #ADT Tweak
Чтобы видеть что именно было изменено и на сколько, что раньше было и т п. А то по коммитам лазить такое себе удовольствие даже если пользоваться журналом изменений

2024-08-23 11:13 UTC, Bolper commented on Resources/Prototypes/Entities/Structures/Storage/Canisters/gas_canisters.yml
> +      price: 250 #ADT Tweak
Сейчас если полазить по файликам то можно заметить, что корваксы так делают

2024-08-23 11:41 UTC, Bolper commented
@Flopochka У тебя тесты сдохли

2024-08-23 17:23 UTC, merged