наследственный глава революции
AdventureTimeSS14/space_station_ADT pull request #330
Opened 2024-08-21 19:29 UTC by Ratyyy

## Описание PR

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

2024-08-21 19:39 UTC, Bolper requested changes
А где собственно в описании ПРа описанные изменения? 
![Screenshot_2024-08-21-22-37-42-072_com android chrome](https://github.com/user-attachments/assets/f4d09d4f-4d3a-4ad4-9155-e6de33a89db5)
И так как я особо не хочу разбираться в писанине на с#, то позову Кэша.

2024-08-21 19:40 UTC, Ratyyy commented
> А где собственно в описании ПРа описанные изменения? ![Screenshot_2024-08-21-22-37-42-072_com android chrome](https://private-user-images.githubusercontent.com/169089627/360074327-f4d09d4f-4d3a-4ad4-9155-e6de33a89db5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNjk0ODMsIm5iZiI6MTcyNDI2OTE4MywicGF0aCI6Ii8xNjkwODk2MjcvMzYwMDc0MzI3LWY0ZDA5ZDRmLTRkM2EtNGFkNC05MTU1LWU2ZGUzM2E4OWRiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxOTM5NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjIxZGMyMjRhNmJkZjc5MWJmNDcyMGY4Njc3YmM0NDhhODEyNmViMGE2YmNkNTNiMWFhYjY1M2UyOTM1MTNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RYTpkZCC9C6MMun6rEW5cGFV1YiaftG2JosE_BQ8Y7I) И так как я особо не хочу разбираться в писанине на с#, то позову Кэша.

тут весь код со старой репы, перенесён без изменений

2024-08-21 20:33 UTC, KashRas2 requested changes
Конечно перенос переносом, но тем не менее.

2024-08-21 20:33 UTC, KashRas2 commented on Content.Server/GameTicking/Rules/RevolutionaryRuleSystem.cs
> -                _popup.PopupEntity(Loc.GetString("rev-break-control", ("name", Identity.Entity(uid, EntityManager))), uid);
Стоит закоментить эту локализацию, так как она ни к чему не привязана более.

2024-08-21 20:33 UTC, KashRas2 commented on Content.Server/GameTicking/Rules/RevolutionaryRuleSystem.cs
> +        var dead = 0;
Бляха, хардкор какой-то пошел. Лучше эту переменную вынести за пределы данной переменной. Иначе реально хардкор.

2024-08-21 20:34 UTC, KashRas2 commented on Content.Server/GameTicking/Rules/RevolutionaryRuleSystem.cs
> -                _popup.PopupEntity(Loc.GetString("rev-break-control", ("name", Identity.Entity(uid, EntityManager))), uid);
Я имею ввиду то, что находится в ftl файле.

2024-08-21 21:15 UTC, Ratyyy commented on Content.Server/GameTicking/Rules/RevolutionaryRuleSystem.cs
> +        var dead = 0;
что... куда выносить то, а главное зачем, в чём смысл выносить это в глобальную переменную этой системы?
ну и если что, у фантома есть то же самое, прям абсолютно

2024-08-21 21:16 UTC, FaDeOkno commented on Content.Server/GameTicking/Rules/RevolutionaryRuleSystem.cs
> +        var dead = 0;
> что... куда выносить то, а главное зачем, в чём смысл выносить это в глобальную переменную этой системы? ну и если что, у фантома есть то же самое, прям абсолютно

(это копипаст)

2024-08-21 21:21 UTC, Ratyyy commented on Content.Server/GameTicking/Rules/RevolutionaryRuleSystem.cs
> +        var dead = 0;
значит, просто переделывать у фантома в палбик и использовать этот метод тут?

2024-08-21 21:21 UTC, KashRas2 commented on Content.Server/GameTicking/Rules/RevolutionaryRuleSystem.cs
> +        var dead = 0;
> что... куда выносить то, а главное зачем, в чём смысл выносить это в глобальную переменную этой системы? ну и если что, у фантома есть то же самое, прям абсолютно

Я фантома не проверял, так что да. Хардкодинг подразумевает, что переменная используется по сути где-то очень закрыто и невидимо. Можно конечно оставит и в таком виде, но даже не знаю.

2024-08-21 21:38 UTC, Bolper commented
> > А где собственно в описании ПРа описанные изменения? ![Screenshot_2024-08-21-22-37-42-072_com android chrome](https://private-user-images.githubusercontent.com/169089627/360074327-f4d09d4f-4d3a-4ad4-9155-e6de33a89db5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNjk0ODMsIm5iZiI6MTcyNDI2OTE4MywicGF0aCI6Ii8xNjkwODk2MjcvMzYwMDc0MzI3LWY0ZDA5ZDRmLTRkM2EtNGFkNC05MTU1LWU2ZGUzM2E4OWRiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxOTM5NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjIxZGMyMjRhNmJkZjc5MWJmNDcyMGY4Njc3YmM0NDhhODEyNmViMGE2YmNkNTNiMWFhYjY1M2UyOTM1MTNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RYTpkZCC9C6MMun6rEW5cGFV1YiaftG2JosE_BQ8Y7I) И так как я особо не хочу разбираться в писанине на с#, то позову Кэша.
> 
> тут весь код со старой репы, перенесён без изменений

Это то очень хорошо, что он перенесён без изменений. Но, относительно этого репозитория - изменения есть. И они должны быть указаны в описании ПРа.

2024-08-21 23:05 UTC, PyotrIgn commented
а я верно понимаю, что наследоваться глава революции будет до бесконечности, и чтобы сделать полную над революцией - СБ и командованию надо всех обколоть майндшилдами?

просто если так - то может радикально увеличить число имплантов в поставке? Иначе вряд ли на станции, пораженной революцией (то есть с гарантированно неработающим снабжением) хватит средств на заказ имплантов

ну или контрреволюционный обр должен иметь солидных запас имплантов при себе для массовых прививок

2024-08-22 06:05 UTC, Ratyyy commented on Content.Server/GameTicking/Rules/RevolutionaryRuleSystem.cs
> +        var dead = 0;
вот так что-ли как-то?

2024-08-22 07:55 UTC, Bolper commented
> а я верно понимаю, что наследоваться глава революции будет до бесконечности, и чтобы сделать полную над революцией - СБ и командованию надо всех обколоть майндшилдами?
> 
> просто если так - то может радикально увеличить число имплантов в поставке? Иначе вряд ли на станции, пораженной революцией (то есть с гарантированно неработающим снабжением) хватит средств на заказ имплантов
> 
> ну или контрреволюционный обр должен иметь солидных запас имплантов при себе для массовых прививок

А как по мне это +РП
Почему базовый сотрудник не может вербовать в реву? Хуй знает. Так что хз
Но соглашусь. МЩ как то маловато.

2024-08-22 08:09 UTC, KashRas2 commented on Content.Server/GameTicking/Rules/RevolutionaryRuleSystem.cs
> +        var dead = 0;
Да, теперь всё отлично.

2024-08-22 08:09 UTC, KashRas2 commented on Content.Server/GameTicking/Rules/RevolutionaryRuleSystem.cs
> -                _popup.PopupEntity(Loc.GetString("rev-break-control", ("name", Identity.Entity(uid, EntityManager))), uid);
Осталось это и тогда смогу принять.

2024-08-22 10:02 UTC, Ratyyy commented
> > а я верно понимаю, что наследоваться глава революции будет до бесконечности, и чтобы сделать полную над революцией - СБ и командованию надо всех обколоть майндшилдами?
> > просто если так - то может радикально увеличить число имплантов в поставке? Иначе вряд ли на станции, пораженной революцией (то есть с гарантированно неработающим снабжением) хватит средств на заказ имплантов
> > ну или контрреволюционный обр должен иметь солидных запас имплантов при себе для массовых прививок
> 
> А как по мне это +РП Почему базовый сотрудник не может вербовать в реву? Хуй знает. Так что хз Но соглашусь. МЩ как то маловато.

я передам маперам, чтобы в оружейку добавляли оружейный кейс с имплантами

2024-08-22 21:06 UTC, KashRas2 approved these changes
Порядок.

2024-08-22 21:06 UTC, merged