Время на младшие должности
AdventureTimeSS14/space_station_ADT pull request #333
Opened 2024-08-22 19:10 UTC by jungarikjan

## Описание PR

- Убрано ограничение на становление кадетом, тех. ассистентом, интерном, лаборантом, если ты уже много наиграл в отделе
- Для того, чтобы стать грузчиком или тех. ассистентом - нужно набрать 4 часа (анти-набегаторские меры)

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- remove: Убрано ограничение на становление кадетом, тех. ассистентом, интерном, лаборантом, если ты уже много наиграл в отделе
- tweak: Для того, чтобы стать грузчиком или тех. ассистентом - нужно набрать 4 часа

2024-08-22 19:48 UTC, Bolper requested changes
Лучше закомменть, то что удалил и поставь ADT Tweak в комментарии

2024-08-22 19:49 UTC, Bolper commented
> Лучше закомменть, то что удалил и поставь ADT Tweak в комментарии

Душить плохо, но я плохой и душный
Но аппрув после этого дам

2024-08-22 21:44 UTC, 1Stepka1 approved these changes

2024-08-22 23:51 UTC, Darki255 commented
> Лучше закомменть, то что удалил и поставь ADT Tweak в комментарии

Душить плохо, но тут ты правильно написал, что надо сделать

2024-08-22 23:57 UTC, Darkiich submitted a review, later dismissed
Джунгар, в описании ПРа у значка CL желательно написать ник, чтобы оно отображалось в ченджлогах(может оно итак будет отображать, но на всякий думаю стоит)

2024-08-23 05:50 UTC, Bolper approved these changes
Я конечно утром и нихрена не вижу. Но вроде всё ок и Стёпка дал апрув.

2024-08-23 12:17 UTC, merged