галлюцинации + фантом с сектере
AdventureTimeSS14/space_station_ADT pull request #334
Opened 2024-08-22 21:22 UTC by Ratyyy

## Описание PR

**Медиа**

**Проверки**

- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Ratyyy
- add: Среди членов экипажа начали крайне быстро распространятся слухи о странных звуках, изредка слышных на станции....
- tweak: фантом теперь может выпасть в секрете

2024-08-22 21:29 UTC, 1Stepka1 approved these changes

2024-08-22 21:29 UTC, 1Stepka1 requested changes
Ах блин, атрибуции где?

2024-08-22 21:36 UTC, 1Stepka1 reviewed
Одна строчкк конечно круто но надо сделать как в остальных подобных файлах

2024-08-22 21:45 UTC, 1Stepka1 approved these changes
Если тесты ничего не скажут то нормуль все

2024-08-23 00:24 UTC, PyotrIgn commented
тест стабильно валится пятый раз

2024-08-23 10:11 UTC, merged