Вокс-пиджин
AdventureTimeSS14/space_station_ADT pull request #336
Opened 2024-08-23 11:14 UTC by Flopochka

## Описание PR

язык и переводчики
**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Язык «Вокс-пиджин»

2024-08-23 11:37 UTC, Bolper approved these changes

2024-08-23 11:37 UTC, Bolper commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
>        - RootSpeakTranslatorImplanter
Если у тебя сразу несколько id надо добавить то ставится ADT tweak start и ADT tweak end . 
Но оставлю на твою совесть это не проставленное ADT tweak у voxcommontranslatorimplanter

2024-08-23 11:37 UTC, Bolper commented on RobustToolbox
А вот это не ебу вообще что такое
Ты же ничего там не трогал?

2024-08-23 12:11 UTC, FaDeOkno commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
>        - RootSpeakTranslatorImplanter
Там уже указано, что это наше

2024-08-23 12:16 UTC, FaDeOkno requested changes

2024-08-23 12:16 UTC, FaDeOkno commented on Resources/Locale/ru-RU/ADT/Languages/languages.ftl
> +language-VoxPidgin-description = Язык воксов — это смесь чириканья и визгов, труднопонимаемая для других рас из-за ультразвуковых характеристик. Они используют рунопись или транслитерацию, что делает
Опиши более кратко, без вырезок из вики

2024-08-23 12:16 UTC, FaDeOkno commented on Resources/Prototypes/ADT/Entities/Mobs/Player/Vox.yml
> +    - type: LanguageSpeaker
Добавь к BaseMobVox, а так же укажи, что ADT компонент

2024-08-23 12:16 UTC, FaDeOkno commented on Resources/Prototypes/ADT/Languages/languages.yml
> +  color: "#419167"
Добавь пункт `whisperColor` с менее насыщенным цветом, иначе шёпот не будет выделяться

2024-08-23 12:16 UTC, FaDeOkno commented on Resources/Prototypes/Entities/Mobs/Player/vox.yml
> +﻿#ADT Tweak (replaced)
А зачем, извиняюсь, переносить в адт папку? Подпиши в оригинальной

2024-08-23 12:20 UTC, FaDeOkno commented
Ну и с робустой разобраться надо, эти изменения тут не нужны

2024-08-23 12:24 UTC, Bolper commented
> Ну и с робустой разобраться надо, эти изменения тут не нужны

Люблю Котю~

2024-08-27 10:28 UTC, Flopochka commented on RobustToolbox
все данные их %AppData% отправляются мне на эмейл, а так ничего)

2024-08-27 10:29 UTC, Flopochka commented
я не знаю чё мне делать с робустой, там у них гит обновился

2024-08-27 12:24 UTC, Bolper commented
> Ну и с робустой разобраться надо, эти изменения тут не нужны

Ну по факту он всего лишь их подтянул, ничего незаконного я в них не увидел. Все равно надо будет рано или поздно обновлять.

2024-08-27 12:35 UTC, Bolper reviewed
Ну честно. вот теперь точно не вижу ничего незаконного

2024-08-27 12:35 UTC, Bolper commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
>        - RootSpeakTranslatorImplanter
Было бы ADT Languages mechanic было бы вообще круто. А так (Может быть я забыл, что эт наша механика)
Но ладно ладно)))

2024-08-27 12:35 UTC, Bolper commented on Resources/Prototypes/Entities/Mobs/Player/vox.yml
> +  # ADT components
ну котька же сказал. К BaseMobVox

2024-08-28 11:19 UTC, FaDeOkno reviewed
Ну вроде норм, с робустой и конфликтами только разберись

2024-08-28 11:19 UTC, FaDeOkno commented on Resources/Prototypes/ADT/Entities/Objects/Device/handheld.yml
> +  id: VoxCommonTranslator
VoxCommon 💀

2024-08-28 11:30 UTC, Bolper commented
Resolve conflicts @Flopochka

2024-08-28 11:49 UTC, Bolper commented
@Flopochka у тебя конфликты в пре, реши их, целая кнопочка есть для этого
Пока не решишь ничего не будет, даже если аппрувну

2024-08-28 11:50 UTC, Bolper commented
> @Flopochka у тебя конфликты в пре, реши их, целая кнопочка есть для этого
> Пока не решишь ничего не будет, даже если аппрувну 

![Screenshot_2024-08-28-14-50-41-233_com.github.android.png](https://github.com/user-attachments/assets/dc23c30d-a509-4360-9df5-38a884b69c43)

2024-08-29 15:25 UTC, Bolper approved these changes
ну уэээ номана

2024-08-30 11:42 UTC, Schrodinger71 commented
Такс тут Робуста

2024-08-30 12:33 UTC, Schrodinger71 approved these changes

2024-09-01 09:41 UTC, merged