Мед апдейт™ - мед препараты.
AdventureTimeSS14/space_station_ADT pull request #340
Opened 2024-08-24 11:31 UTC by JustKekc

Препараты с таблеткомата без рецептов.

https://github.com/user-attachments/assets/b90322b8-b8dd-4c38-820f-17b7ab0a30bb

2024-08-24 11:32 UTC, JustKekc commented
давай, сри ошибками.

2024-08-24 12:13 UTC, JustKekc commented
![image](https://github.com/user-attachments/assets/91931aca-db44-4b72-950b-60d48b18705b)
huh.

2024-08-24 12:14 UTC, JustKekc commented
![image](https://github.com/user-attachments/assets/2ae1089e-bf62-4221-aea5-3884d9f5a544)
вы зачем вонючесть почистили.

2024-08-24 14:35 UTC, JustKekc commented
![image](https://github.com/user-attachments/assets/a34d45e6-ece3-4332-bfba-0df301e50671)
huh
![well uh welal uhj](https://github.com/user-attachments/assets/dcf2e992-510e-45f3-9142-687c02dded78)

2024-08-24 20:31 UTC, Bolper reviewed
Да я просто повтыкаю посмотрю

2024-08-24 20:31 UTC, Bolper commented on Content.Server/ADT/EntityEffects/Effects/Embalm.cs
> +namespace Content.Server.ADT.Chemistry.ReagentEffects;
Мне кажется что reagenteffects это немного не то но да не мне решать а котьке
Ps entity effect

2024-08-24 21:22 UTC, JustKekc commented on Content.Server/ADT/EntityEffects/Effects/Embalm.cs
> +namespace Content.Server.ADT.Chemistry.ReagentEffects;
в действительности.

2024-08-25 08:14 UTC, JustKekc commented on Content.Server/ADT/EntityEffects/Effects/Embalm.cs
> +namespace Content.Server.ADT.Chemistry.ReagentEffects;
спасибо, что подметил.

2024-08-25 09:08 UTC, KashRas2 requested changes

2024-08-25 09:08 UTC, KashRas2 commented on Resources/Prototypes/Entities/Mobs/NPCs/simplemob.yml
> +    - Adrenaline
ГДЕ КОММЕНТАРИИ

2024-08-25 09:08 UTC, KashRas2 commented on Resources/Prototypes/Entities/Mobs/NPCs/simplemob.yml
> +    - Adrenaline
ГДЕ КОММЕНТАРИИ

2024-08-25 09:08 UTC, KashRas2 commented on Resources/Prototypes/Entities/Mobs/Player/dragon.yml
> +    - Adrenaline
ГДЕ КОММЕНТАРИИ

2024-08-25 09:08 UTC, KashRas2 commented on Resources/Prototypes/status_effects.yml
> +- type: statusEffect
ЭТО МОЖНО К НАМ В ПАПКУ ВООБЩЕ-ТО

2024-08-25 09:08 UTC, KashRas2 commented on Resources/Prototypes/Alerts/alerts.yml
> +- type: alert
ЭТО МОЖНО К НАМ В ПАПКУ

2024-08-25 09:08 UTC, KashRas2 commented on Resources/Locale/ru-RU/reagents/meta/physical-desc.ftl
> +reagent-physical-desc-skunky = вонючее
К НАМ

2024-08-25 09:08 UTC, KashRas2 commented on Resources/Locale/ru-RU/medical/components/defibrillator.ftl
> +defibrillator-embalmed = Обнаружено бальзамирование тела: реанимация невозможна.
К НАМ

2024-08-25 09:08 UTC, KashRas2 commented on Resources/Locale/ru-RU/guidebook/chemistry/statuseffects.ftl
> +reagent-effect-status-effect-Adrenaline = адреналин
К НАМ

2024-08-25 09:08 UTC, KashRas2 commented on Resources/Locale/ru-RU/disease/miasma.ftl
> +adt-rotting-embalmed = [color=#edad45]Похоже, тело забальзамировано.[/color]
К НАМ

2024-08-25 09:08 UTC, KashRas2 commented on Resources/Locale/ru-RU/alerts/alerts.ftl
> +alerts-adrenaline-name = [color=red]Адреналин[/color]
К НАМ

2024-08-25 09:08 UTC, KashRas2 commented on Resources/Locale/en-US/reagents/meta/physical-desc.ftl
> +reagent-physical-desc-skunky = skunky
зачем англ то

2024-08-25 09:08 UTC, KashRas2 commented on Resources/Locale/en-US/medical/components/defibrillator.ftl
> +defibrillator-embalmed = Body embalmment detected: resuscitation failed.
зачем англ то

2024-08-25 09:08 UTC, KashRas2 commented on Resources/Locale/en-US/guidebook/chemistry/statuseffects.ftl
> +reagent-effect-status-effect-Adrenaline = adrenaline
зачем англ то

2024-08-25 09:08 UTC, KashRas2 commented on Resources/Locale/en-US/disease/miasma.ftl
> +adt-rotting-embalmed = [color=#edad45]Looks like body is embalmed.[/color]
зачем англ то

2024-08-25 09:08 UTC, KashRas2 commented on Resources/Locale/en-US/alerts/alerts.ftl
> +alerts-adrenaline-name = [color=red]Adrenaline[/color]
зачем англ то

2024-08-25 09:08 UTC, KashRas2 commented on Resources/Locale/en-US/ADT/Reagents/Meta/medicine.ftl
> +reagent-name-sodiumizole = sodiumizole
зачем англ то

2024-08-25 09:08 UTC, KashRas2 commented on Resources/Locale/en-US/ADT/Reagents/Effects/medicine_effects.ftl
> +medicine-effect-usual = You feel how your pain is slowly going away.
зачем англ то

2024-08-25 09:08 UTC, KashRas2 commented on Content.Server/Medical/DefibrillatorSystem.cs
> +        if (HasComp<EmbalmedComponent>(target))
КОММЕНТАРИИ

2024-08-25 09:08 UTC, KashRas2 commented on Content.Shared/Damage/Components/IgnoreSlowOnDamageComponent.cs
> +using Robust.Shared.GameStates;
к нам в папку

2024-08-25 09:08 UTC, KashRas2 commented on Content.Shared/Damage/Systems/SlowOnDamageSystem.cs
> +            SubscribeLocalEvent<IgnoreSlowOnDamageComponent, ComponentStartup>(OnIgnoreStartup);
КОММЕНТАРИИ

2024-08-25 09:08 UTC, KashRas2 commented on Content.Shared/Damage/Systems/SlowOnDamageSystem.cs
> +                var ev = new ModifySlowOnDamageSpeedEvent(speed);
КОММЕНТАРИИ (я капсом по приколу пишу ес че, без обид)

2024-08-25 09:08 UTC, KashRas2 commented on Content.Shared/Damage/Systems/SlowOnDamageSystem.cs
> +        private void OnIgnoreStartup(Entity<IgnoreSlowOnDamageComponent> ent, ref ComponentStartup args)
КОММЕНТАРИИ

2024-08-25 09:14 UTC, Bolper commented
Кэш(кэшуля) красавчик~~~

2024-08-25 09:24 UTC, JustKekc commented on Resources/Prototypes/Alerts/alerts.yml
> +- type: alert
https://github.com/space-wizards/space-station-14/pull/31322

2024-08-25 09:26 UTC, JustKekc commented on Resources/Locale/ru-RU/reagents/meta/physical-desc.ftl
> +reagent-physical-desc-skunky = вонючее
это визарды вырезали, я вернул обратно на место.
но справедливо.

2024-08-25 09:27 UTC, JustKekc commented on Resources/Locale/ru-RU/medical/components/defibrillator.ftl
> +defibrillator-embalmed = Обнаружено бальзамирование тела: реанимация невозможна.
создавать целую папку с отдельным файлом чисто на одну строчку?
можно, но не сильно вижу смысла.

2024-08-25 09:27 UTC, JustKekc commented on Resources/Locale/ru-RU/medical/components/defibrillator.ftl
> +defibrillator-embalmed = Обнаружено бальзамирование тела: реанимация невозможна.
вряд ли кто-то ещё будет создавать строчки для дефиба.

2024-08-25 09:27 UTC, JustKekc commented on Resources/Locale/ru-RU/guidebook/chemistry/statuseffects.ftl
> +reagent-effect-status-effect-Adrenaline = адреналин
от визардов.

2024-08-25 09:28 UTC, JustKekc commented on Resources/Locale/ru-RU/disease/miasma.ftl
> +adt-rotting-embalmed = [color=#edad45]Похоже, тело забальзамировано.[/color]
![image](https://github.com/user-attachments/assets/d27017d8-68c2-48ae-946f-5b89debc64bd)

2024-08-25 09:29 UTC, JustKekc commented on Resources/Locale/ru-RU/alerts/alerts.ftl
> +alerts-adrenaline-name = [color=red]Адреналин[/color]
справедливо.

2024-08-25 09:30 UTC, JustKekc commented on Resources/Prototypes/Entities/Mobs/NPCs/simplemob.yml
> +    - Adrenaline
от визардов.

2024-08-25 09:30 UTC, JustKekc commented on Resources/Prototypes/Entities/Mobs/NPCs/simplemob.yml
> +    - Adrenaline
от визардов.

2024-08-25 09:30 UTC, JustKekc commented on Resources/Prototypes/Entities/Mobs/Player/dragon.yml
> +    - Adrenaline
от визардов.

2024-08-25 09:30 UTC, JustKekc commented on Resources/Prototypes/status_effects.yml
> +- type: statusEffect
от визардов.

2024-08-25 09:30 UTC, Bolper commented on Resources/Locale/ru-RU/guidebook/chemistry/statuseffects.ftl
> +reagent-effect-status-effect-Adrenaline = адреналин
Но у тебя в пре. Не спорь с кэшэм~ 
Но всё равно он решает~

2024-08-25 09:32 UTC, JustKekc commented on Resources/Locale/en-US/reagents/meta/physical-desc.ftl
> +reagent-physical-desc-skunky = skunky
ладно, справедливо.

2024-08-25 09:32 UTC, JustKekc commented on Resources/Locale/en-US/guidebook/chemistry/statuseffects.ftl
> +reagent-effect-status-effect-Adrenaline = adrenaline
от визардов.

2024-08-25 09:32 UTC, JustKekc commented on Resources/Locale/en-US/alerts/alerts.ftl
> +alerts-adrenaline-name = [color=red]Adrenaline[/color]
от визардов.

2024-08-25 09:32 UTC, JustKekc commented on Content.Shared/Damage/Components/IgnoreSlowOnDamageComponent.cs
> +using Robust.Shared.GameStates;
от визардов.

2024-08-25 09:32 UTC, JustKekc commented on Content.Shared/Damage/Systems/SlowOnDamageSystem.cs
> +            SubscribeLocalEvent<IgnoreSlowOnDamageComponent, ComponentStartup>(OnIgnoreStartup);
от визардов.

2024-08-25 09:32 UTC, JustKekc commented on Content.Shared/Damage/Systems/SlowOnDamageSystem.cs
> +                var ev = new ModifySlowOnDamageSpeedEvent(speed);
от визардов.

2024-08-25 09:33 UTC, JustKekc commented on Content.Shared/Damage/Systems/SlowOnDamageSystem.cs
> +        private void OnIgnoreStartup(Entity<IgnoreSlowOnDamageComponent> ent, ref ComponentStartup args)
от визардов.

2024-08-25 09:34 UTC, KashRas2 commented on Resources/Locale/ru-RU/medical/components/defibrillator.ftl
> +defibrillator-embalmed = Обнаружено бальзамирование тела: реанимация невозможна.
> вряд ли кто-то ещё будет создавать строчки для дефиба.

всё равно к нам

2024-08-25 09:34 UTC, KashRas2 commented on Resources/Locale/ru-RU/disease/miasma.ftl
> +adt-rotting-embalmed = [color=#edad45]Похоже, тело забальзамировано.[/color]
> ![image](https://private-user-images.githubusercontent.com/120025606/361198914-d27017d8-68c2-48ae-946f-5b89debc64bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1Nzg3NDgsIm5iZiI6MTcyNDU3ODQ0OCwicGF0aCI6Ii8xMjAwMjU2MDYvMzYxMTk4OTE0LWQyNzAxN2Q4LTY4YzItNDhhZS05NDZmLTViODlkZWJjNjRiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNVQwOTM0MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03N2VkN2UxYTNkODQyMDJhNTAxMGI1NGQ2MTc4OTk4NzBiOTQwZDk3Y2ExZTcwYTI5ZGU4ZThkMTM3MmVkOTQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Rcns94qk6SGXAnLIOiQJFRi5jXe0l6c7dt7YcYMTG94)

выше всё сказал

2024-08-25 10:49 UTC, KashRas2 requested changes

2024-08-25 10:49 UTC, KashRas2 commented on Content.Server/Medical/DefibrillatorSystem.cs
> +        if (HasComp<EmbalmedComponent>(target)) //Can't revive embalmed people.
Да не эти комментарии
я про //ADT-Tweak

2024-08-25 10:50 UTC, KashRas2 commented on Content.Server/Medical/DefibrillatorSystem.cs
> +        if (HasComp<EmbalmedComponent>(target)) //Can't revive embalmed people.
и не важно, кому оно принадлежит. Визардам или нет. Всё в нашу папку. У визардов лицензия МИТ. Мы имеем права эти файлы по кругу пустить.

2024-08-25 11:52 UTC, FaDeOkno commented
![image](https://github.com/user-attachments/assets/6d23d6e3-163b-4fc4-81bb-3959e40e5b0c)

2024-08-25 11:52 UTC, FaDeOkno commented on Content.Server/Medical/DefibrillatorSystem.cs
> +        if (HasComp<EmbalmedComponent>(target)) //Can't revive embalmed people.
> и не важно, кому оно принадлежит. Визардам или нет. Всё в нашу папку. У визардов лицензия МИТ. Мы имеем права эти файлы по кругу пустить.

И после апстрима все эти файлы придётся выискивать и удалять вручную у нас

2024-08-27 10:24 UTC, JustKekc commented on Content.Server/Medical/DefibrillatorSystem.cs
> +        if (HasComp<EmbalmedComponent>(target)) //Can't revive embalmed people.
так и что решаем по итогу.

2024-08-27 15:53 UTC, KashRas2 requested changes, later dismissed
сделай то, что не сделал

2024-08-27 15:53 UTC, KashRas2 commented on Content.Shared/Damage/Components/IgnoreSlowOnDamageComponent.cs
> +using Robust.Shared.GameStates;
К НАМ В ПАПКУ

2024-08-27 15:53 UTC, KashRas2 commented on Content.Shared/Damage/Systems/SlowOnDamageSystem.cs
> +            SubscribeLocalEvent<IgnoreSlowOnDamageComponent, ComponentStartup>(OnIgnoreStartup);
комментарии надо всё ещё

2024-08-27 15:53 UTC, KashRas2 commented on Content.Shared/Damage/Systems/SlowOnDamageSystem.cs
> +                var ev = new ModifySlowOnDamageSpeedEvent(speed);
всё ещё актуально

2024-08-27 15:53 UTC, KashRas2 commented on Content.Shared/Damage/Systems/SlowOnDamageSystem.cs
> +        private void OnIgnoreStartup(Entity<IgnoreSlowOnDamageComponent> ent, ref ComponentStartup args)
ну ты понял

2024-08-27 15:53 UTC, KashRas2 commented on Resources/Locale/en-US/alerts/alerts.ftl
> +alerts-adrenaline-name = [color=red]Adrenaline[/color]
да убери ты англ

2024-08-27 15:53 UTC, KashRas2 commented on Resources/Locale/en-US/guidebook/chemistry/statuseffects.ftl
> +reagent-effect-status-effect-Adrenaline = adrenaline
ну убери

2024-08-27 15:53 UTC, KashRas2 commented on Resources/Locale/ru-RU/guidebook/chemistry/statuseffects.ftl
> +reagent-effect-status-effect-Adrenaline = адреналин
к нам

2024-08-27 15:53 UTC, KashRas2 commented on Resources/Prototypes/Alerts/alerts.yml
> +- type: alert
к нам

2024-08-29 18:39 UTC, JustKekc commented
@KashRas2, снесите пжлста ваши просьбы и запустите уже наконец проверки.

2024-08-29 20:04 UTC, JustKekc commented
спасибо.

2024-08-29 21:29 UTC, KashRas2 requested changes
Последнее китайское предупреждение

2024-08-29 21:29 UTC, KashRas2 commented on Content.Shared/Damage/Systems/SlowOnDamageSystem.cs
> +        //
Ну куда это ну емае

2024-08-29 21:30 UTC, KashRas2 commented on Content.Shared/Damage/Systems/SlowOnDamageSystem.cs
> +        //
Это пустой коммент если что.

2024-08-29 21:32 UTC, KashRas2 commented
И бога ради, убери эти EmoGarbage что-то там. Когда же вы поймёте, что при лицензии МИТ мы не обязаны автора указывать. Код можно вертеть как угодно. Комментарии нужны для того, чтобы изменения кода было легко найти. Ну кекс, ну емае.

2024-08-29 21:33 UTC, KashRas2 commented
Да, я может быть чересчур душный, прошу прощения, но такова специфика моей роли.

2024-08-29 21:34 UTC, KashRas2 commented
Насчёт комментов - посмотри как у меня сделано условно. Я не говорю, что надо делать также, но просто для примера. Я очень надеюсь, что все будет как надо.

2024-09-01 09:51 UTC, KashRas2 approved these changes
Убедительно

2024-09-01 09:53 UTC, KashRas2 commented on Resources/Prototypes/Entities/Mobs/Species/base.yml
>      - ADTHallucinations # ADT-Tweak
А тут забыл. Ладно, фиг с тобой. Я тебя достал наверное уже.

2024-09-01 09:54 UTC, JustKekc commented on Resources/Prototypes/Entities/Mobs/Species/base.yml
>      - ADTHallucinations # ADT-Tweak
а, ой

2024-09-01 09:54 UTC, JustKekc commented on Resources/Prototypes/Entities/Mobs/Species/base.yml
>      - ADTHallucinations # ADT-Tweak
ща будет

2024-09-01 10:04 UTC, Schrodinger71 commented
ждёмс

2024-09-01 10:38 UTC, JustKekc commented
о, нифига, даже проверки прошло

2024-09-03 00:36 UTC, Schrodinger71 approved these changes

2024-09-03 00:42 UTC, merged