Хотфикс бригмедика
AdventureTimeSS14/space_station_ADT pull request #349
Opened 2024-08-25 16:45 UTC by AnderFan

Убран халат бригмедика, вместо него есть бронехалат.
Добавлен в консоль заказов шкаф бригмедика

2024-08-25 17:32 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/coats.yml
> -
Это зачем удалять?

2024-08-25 17:34 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/coats.yml
> -
+

2024-08-25 17:34 UTC, Bolper commented on Resources/Prototypes/Corvax/Entities/Clothing/OuterClothing/coats.yml
> -  description: A suit that protects against minor chemical spills.
Я б покомментил Корсаков а не рубил с чистой руки.

2024-08-25 17:36 UTC, Bolper commented on Resources/Prototypes/ADT/Catalog/Cargo/cargo_security.yml
> +
Эмэ кажется тут должно что то быть

2024-08-25 17:41 UTC, Bolper reviewed
И я не вижу добавление в консоль заказов

2024-08-27 08:57 UTC, Bolper requested changes
Исправить о том, что мы писали выше

2024-08-29 20:01 UTC, FaDeOkno requested changes
Ченджлоги не трогать

2024-08-31 08:59 UTC, Schrodinger71 commented
Чейнжлоги ни трогай, просто скопируй как в мастере и всё

Если что-то в них нужно поправить пиши мне

2024-09-03 17:30 UTC, FaDeOkno requested changes

2024-09-03 17:30 UTC, FaDeOkno commented on Resources/Changelog/ChangelogADT.yml
Не.
Трогай.
Ченджлоги

2024-09-03 17:30 UTC, FaDeOkno commented on Resources/Prototypes/ADT/Catalog/Cargo/cargo_security.yml
Убери пустой файл

2024-10-26 15:01 UTC, Darkiich commented
Закрываю PR по причине долгого отсутствия актива

2024-10-26 15:01 UTC, closed without merging