[ПЕРЕНОС] Добавлен страйкбольный лектер
AdventureTimeSS14/space_station_ADT pull request #350
Opened 2024-08-25 17:17 UTC by Darkiich

## Описание PR

Этот ПР переносить  страйкбольный лектер
**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

- add: Добавлен страйкбольный лектер

2024-08-25 17:27 UTC, Bolper reviewed
Понатыкал то что вижу с первого раза. Не воспринимать в серьёз. @1Stepka1 жду тебя.

2024-08-25 17:27 UTC, Bolper commented on Resources/Locale/ru-RU/ADT/Objects/Weapons/Guns/guns.ftl
> +    .desc = Магазин для страйкбольного автомата, с двумя сотнями маленьких шариков.
Лично как я помню, но я не уверен, но магазины, патроны, оружие - отдельные файлы. Проверять мне лень, ибо я с телефона

2024-08-25 17:27 UTC, Bolper commented on Resources/Prototypes/ADT/tags.yml
> +  id: ADTCartridgeBibis
Я не вижу чтобы этот тэг использовался в  sec belts  - он бесполезен

2024-08-25 17:28 UTC, Bolper commented
Потом сделаю нормальное ревью если Стёпка не опередит

2024-08-25 17:51 UTC, Darkiich commented on Resources/Prototypes/ADT/tags.yml
> +  id: ADTCartridgeBibis
Огузок, внимательнее смотри. Убирать я его не буду

2024-08-25 17:52 UTC, Bolper commented on Resources/Prototypes/ADT/tags.yml
> +  id: ADTCartridgeBibis
Да я ж с телефона. Чего сразу огузок

2024-08-25 17:55 UTC, Bolper commented on Resources/Prototypes/ADT/tags.yml
> +  id: ADTCartridgeBibis
Но я всё ещё не вижу чтобы это можно засунуть в то что я говорил, либо я сплю, либо я спя не понял

2024-08-25 17:59 UTC, Darkiich commented on Resources/Prototypes/ADT/tags.yml
> +  id: ADTCartridgeBibis
А я понял о чем ты, это уже не мое дело, чтобы его можно было засунуть в пояс. Моя задача просто перенести страйкбольный лектер, который используется для ивентов

2024-08-25 18:04 UTC, Bolper commented on Resources/Prototypes/ADT/tags.yml
> +  id: ADTCartridgeBibis
Вооо. Это не я огузок!!!

2024-08-25 18:04 UTC, Bolper commented on Resources/Prototypes/ADT/tags.yml
> +  id: ADTCartridgeBibis
_гладит банан_
Добавил туда куда я прошу и всём будет хорошо~

2024-08-25 18:05 UTC, Darkiich commented on Resources/Prototypes/ADT/tags.yml
> +  id: ADTCartridgeBibis
Но я могу это сделать, если ты скажешь какой тэг. Мне лень его искать везде)

2024-08-25 20:23 UTC, Bolper commented on Resources/Prototypes/ADT/tags.yml
> +  id: ADTCartridgeBibis
Воть сюда
Resources/Prototypes/Entities/Clothing/Belt/belts.yml
![Screenshot_2024-08-25-23-22-22-869_com.github.android.png](https://github.com/user-attachments/assets/1e73ab76-d974-46d5-8f20-c3613836ef4a)

2024-08-25 20:25 UTC, Darkiich commented on Resources/Prototypes/ADT/tags.yml
> +  id: ADTCartridgeBibis
> Воть сюда Resources/Prototypes/Entities/Clothing/Belt/belts.yml ![Screenshot_2024-08-25-23-22-22-869_com.github.android.png](https://private-user-images.githubusercontent.com/169089627/361257239-1e73ab76-d974-46d5-8f20-c3613836ef4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2MTc3MjMsIm5iZiI6MTcyNDYxNzQyMywicGF0aCI6Ii8xNjkwODk2MjcvMzYxMjU3MjM5LTFlNzNhYjc2LWQ5NzQtNDZkNS04ZjIwLWMzNjEzODM2ZWY0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNVQyMDIzNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTdhMzNkNmM4MTFjM2U4MTAxMjg0ZjAwZmM3ZTg0OTgxNDQ2ZWMxY2JiZGYyN2U2MmY2YWRhODU1ZDAyYzFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JQ4KkNKcGpsMbdJ6Yi49Foz4EXrCXE5cHf5TIWav3BE)

Я тебя прощаю

2024-08-25 20:27 UTC, Bolper commented on Resources/Prototypes/ADT/tags.yml
> +  id: ADTCartridgeBibis
Уваааа!!!

2024-08-26 07:24 UTC, Darkiich commented on Resources/Prototypes/ADT/tags.yml
> +  id: ADTCartridgeBibis
> Уваааа!!!

Готово

2024-08-26 14:43 UTC, Bolper commented
так Ревью нужно?
тогда сделаю

2024-08-26 15:12 UTC, Bolper reviewed
Ну а все же. Зачем целый отдельный файл strikeball. По базовым почему б не запихать

2024-08-26 15:12 UTC, Bolper commented on Resources/Locale/ru-RU/ADT/Objects/Weapons/Guns/guns.ftl
> +    .desc = Магазин для страйкбольного автомата, с двумя сотнями маленьких шариков.
Вот тут честно за локалку не ебу

2024-08-26 15:12 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
> +    sprite: Objects/Weapons/Guns/Projectiles/projectiles2.rsi
А все.. понял

2024-08-26 15:12 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Rifels/rifles.yml
> +  description: A high end military grade assault rifle. Uses .20 rifle ammo.
Тут наикрутейшее описание. Высококачественная штурмовая винтовка военного класса. Использует винтовочные патроны 20-го калибра.

2024-08-26 15:12 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Rifels/rifles.yml
> +  description: A high end military grade assault rifle. Uses .20 rifle ammo.
И может было легче пронаследовать от этого же лектора?

2024-08-26 15:12 UTC, Bolper commented on Resources/Locale/ru-RU/ADT/Objects/Weapons/Guns/guns.ftl
> +    .desc = Магазин для страйкбольного автомата, с двумя сотнями маленьких шариков.
Но все же я б раскидал по файликам  Magazines Projectiles Cartridges

2024-08-27 10:05 UTC, Darkiich commented on Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
> +  id: BaseBulletRubber
> А не. чтот я затупил. Где буковки ADT если это наша база?

я не знаю наше это или нет, я просто переношу, а не создаю свое

2024-08-27 10:06 UTC, Darkiich commented on Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Rifels/rifles.yml
> +  description: A high end military grade assault rifle. Uses .20 rifle ammo.
> Тут наикрутейшее описание. Высококачественная штурмовая винтовка военного класса. Использует винтовочные патроны 20-го калибра.

похуй, все равно локализация есть. И я переношу, а не создаю свое

2024-08-27 10:10 UTC, Darkiich commented on Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
> +  id: BaseBulletRubber
> > А не. чтот я затупил. Где буковки ADT если это наша база?
> 
> я не знаю наше это или нет, я просто переношу, а не создаю свое

Но раз в папке ADT, то да, скорее всего наше, немного затупил что-то

2024-08-27 10:24 UTC, Darkiich commented on Resources/Locale/ru-RU/ADT/Objects/Weapons/Guns/guns.ftl
> +    .desc = Магазин для страйкбольного автомата, с двумя сотнями маленьких шариков.
> Но все же я б раскидал по файликам Magazines Projectiles Cartridges

Готово

2024-08-27 10:25 UTC, Darkiich commented on Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
> +  id: BaseBulletRubber
> А не. чтот я затупил. Где буковки ADT если это наша база?

Готово

2024-08-27 10:30 UTC, Bolper commented
> Ну а все же. Зачем целый отдельный файл strikeball. По базовым почему б не запихать
Ну по этому поводу всё так же вопрос.

2024-08-27 10:30 UTC, Bolper commented
> > Ну а все же. Зачем целый отдельный файл strikeball. По базовым почему б не запихать
> 
> Ну по этому поводу всё так же вопрос. 
> 
Каждый раз создавать новый файл strike ball не оч хорошо наверно

2024-08-27 10:32 UTC, Darkiich commented
> > Ну а все же. Зачем целый отдельный файл strikeball. По базовым почему б не запихать
> 
> Ну по этому поводу всё так же вопрос.

Ну всмысле зачем, это же файл с прототипами магазинов

2024-08-27 10:35 UTC, Bolper commented
> > > Ну а все же. Зачем целый отдельный файл strikeball. По базовым почему б не запихать
> > 
> > Ну по этому поводу всё так же вопрос.
> 
> Ну всмысле зачем, это же файл с прототипами магазинов

А не. Всё ок. Туплю

2024-08-27 10:36 UTC, Bolper approved these changes
Ну особо бед здесь не вижу

2024-08-27 10:37 UTC, Darkiich commented
> Ну особо бед здесь не вижу

Люблю, целую

2024-08-27 10:46 UTC, Bolper approved these changes
Так. Норм всё же

2024-08-27 10:47 UTC, Darkiich commented
> Так. Норм всё же

XD

2024-08-27 11:02 UTC, Darkiich commented
> > > Так. Норм всё же
> > 
> > 
> > XD
> 
> Да падажди ты

Огузок

2024-08-27 12:06 UTC, Bolper requested changes
Не.. Я тут себе голову сломал. Еще папки плодить не хочу. Ну это пиздец

2024-08-27 12:06 UTC, Bolper commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/strikeball.ftl
Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Weapons/Guns/Ammunition/projectiles.ftl
Не хочу я бля плодить лишние папки в локализации

2024-08-27 12:06 UTC, Bolper commented on Resources/Textures/ADT/Objects/Weapons/Guns/Ammunition/airsoft_bibis.rsi/meta.json
в Resources/Textures/Objects/Weapons/Guns/Ammunition/Casings/

2024-08-27 12:42 UTC, Darkiich commented on Resources/Locale/ru-RU/ADT/Objects/Weapons/Guns/strikeball.ftl
Готово

2024-08-27 12:43 UTC, Darkiich commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/strikeball.ftl
Поменял только название. Путь правильный, смотри как у визардов

2024-08-27 12:44 UTC, Darkiich commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Weapons/Guns/Ammunition/Magazines/strikeball.ftl
Поменял только название. Путь правильный, смотри как у визардов

2024-08-27 12:45 UTC, Darkiich commented on Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
> +  id: ADTBulletBibis
Готово

2024-08-27 12:47 UTC, Darkiich commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/strikeball.ftl
Поменял только название. Путь правильный, смотри как у визардов

2024-08-27 12:47 UTC, Bolper commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Weapons/Guns/Ammunition/Magazines/strikeball.ftl
Это просто тупо будет лишняя папка? Которая содержит 1 файл. Зачем?

2024-08-27 12:47 UTC, Bolper commented on Resources/Locale/ru-RU/ADT/Objects/Weapons/Guns/strikeball.ftl
Блять.. Переименуй в rifles
Скопировал не так

2024-08-27 12:51 UTC, Darkiich commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Weapons/Guns/Ammunition/Magazines/strikeball.ftl
> Это просто тупо будет лишняя папка? Которая содержит 1 файл. Зачем?

Да, Степа отталкивается от визардов, значит я тоже

2024-08-27 12:54 UTC, Bolper commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Weapons/Guns/Ammunition/Magazines/strikeball.ftl
@1Stepka1 как тут сделаем. Я лично не вижу смысла делать папку с одним файлом которые имеют одинаковые название

2024-08-27 12:57 UTC, 1Stepka1 commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Weapons/Guns/Ammunition/Magazines/strikeball.ftl
По факту ближе к конечной папке названия могут вариороваться если же нету аналога того что ты делаешь у видардов, если есть то следуем визардам, если нету то можно своё вписать

2024-08-27 12:58 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/strikball.yml
> +    sprite: ADT/Objects/Weapons/Guns/Ammunition/airsoft_bibis.rsi
У тебя ошибка тут. Путь не поменял

2024-08-27 13:26 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/BulletBibis.yml
> +  id: ADTBaseBulletRubber
Не не не
Я посмотрел. Базы находятся в папке выше, тобишь там где было раньше.

2024-08-27 13:29 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/BulletBibis.yml
> +  id: ADTBaseBulletRubber
Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml

2024-08-27 13:29 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/BulletBibis.yml
> +  id: ADTBaseBulletRubber
Это у них так сделано. В нашем случае это в папке adt

2024-08-27 13:31 UTC, Darkiich commented on Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/BulletBibis.yml
> +  id: ADTBaseBulletRubber
> > Не не не Я посмотрел. Базы находятся в папке выше, тобишь там где было раньше.
> 
> Огузок

Но я тебя прощаю :3

2024-08-27 13:57 UTC, Darkiich commented
@Bolper

2024-08-27 13:57 UTC, Bolper approved these changes
Люблю обожаю

2024-08-27 13:59 UTC, Darkiich commented
> Люблю обожаю

Люблю, целую

2024-08-27 14:14 UTC, merged