Суп из опилок и чокеры
AdventureTimeSS14/space_station_ADT pull request #382
Opened 2024-08-31 15:53 UTC by Us3rn4me228

## Описание PR
Перенос чокеров и супа из опилок по просьбам играющих. Локаль не завезена ибо я её [CENSORED]

**Ссылка на публикацию в Discord**
- [Перенос контента] https://discord.com/channels/901772674865455115/1274727409970581515/1274727409970581515
- [Перенос контента] https://discord.com/channels/901772674865455115/1273039769282023524/1273039769282023524

**Медиа**
![image](https://github.com/user-attachments/assets/17c10306-ff86-4d35-a12c-a86d3a45e3f1)

**Проверки**
- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Username228
- add: Добавлены чокеры с Сирены. Их можете найти в Стильномате.
- add: Добавлен суп из опилок. ЧТО ЭТОТ СУП ЗАБЫЛ В МОИХ ОПИЛКАХ????

2024-08-31 15:56 UTC, Bolper commented
Не ну эт не дело без локали

2024-08-31 16:02 UTC, Us3rn4me228 commented
> Не ну эт не дело без локали

Я НЕНАВИЖУ ЛОКАЛЬ
Я НЕНАВИЖУ ЛОКАЛЬ
Я НЕНАВИЖУ ЛОКАЛЬ
https://images-ext-1.discordapp.net/external/qopqYIHiw4oVMHk7kBKbs5dpCDumBKEE_bt_8VA5x0c/https/media.tenor.com/URHYMXTXmdcAAAPo/venom.mp4

2024-08-31 16:05 UTC, Bolper requested changes
Локаль
_пожимает плечами_
Зачем нам добавление вещей у которых нет перевода? 
Доделать

2024-08-31 16:07 UTC, Bolper commented
> Локаль _пожимает плечами_ Зачем нам добавление вещей у которых нет перевода? Доделать

Да ещё и тесты не пройдены

2024-08-31 16:49 UTC, Bolper commented
![Screenshot_2024-08-31-19-49-28-334_com.discord.png](https://github.com/user-attachments/assets/0ab5b633-a1de-4a9e-b162-e926d130a8b4)

2024-09-10 16:23 UTC, Bolper commented
К сожалению я вынужден закрыть данный ПР по причине того, что в нём слишком много лишнего контента, который не описан в описании ПРа. Данная задача передана другому.

2024-09-10 16:23 UTC, closed without merging