Blood cough
AdventureTimeSS14/space_station_ADT pull request #388
Opened 2024-09-01 17:10 UTC by Schrodinger71

## Описание PR

Как только у сущности с этим компонентом становиться больше 70 общего урона, накидывается AutoEmotePostingChatComponent который постит "Кашляет кровью"

звук также воспроизводиться

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Шрёдька
- add: Добавлены автоэмоции, если у некоторых сущностей больше 70 общего урона будет постинг в чат о его плохом состоянии.

2024-09-01 19:18 UTC, FaDeOkno commented on Content.Server/ADT/BloodCough/BloodCoughSystem.cs
Предлагаю перенести логику из Update в отдельную функцию, плюс добавить саму кровь, появляющуюся после эмоута под персонажем

2024-09-01 21:35 UTC, Schrodinger71 commented on Content.Server/ADT/BloodCough/BloodCoughSystem.cs
какую именно?

2024-09-02 15:44 UTC, KashRas2 commented on Content.Shared/ADT/BloodCough/BloodCoughComponent.cs
> +    public string? PostingSayDamage = "Кашляет кровью";
это че такое
локализацию давай изверг

2024-09-03 00:35 UTC, Schrodinger71 commented on Content.Shared/ADT/BloodCough/BloodCoughComponent.cs
> +    public string? PostingSayDamage = "Кашляет кровью";
уээээ?

2024-09-04 08:03 UTC, 1Stepka1 requested changes
Не знаю в чем прикол добавления кашля каждой расе если это можно просто навесить на BaseMobSpeciesOrganic и изменить там где это нужно

2024-09-04 08:05 UTC, Schrodinger71 commented
> Не знаю в чем прикол добавления кашля каждой расе если это можно просто навесить на BaseMobSpeciesOrganic и изменить там где это нужно

Так он в зависимости от расы мб разный

2024-09-04 08:07 UTC, Schrodinger71 commented
Хотя да, поправлю
Меньше изменений

2024-09-04 11:55 UTC, Schrodinger71 commented on Content.Shared/ADT/BloodCough/BloodCoughComponent.cs
> +    public string? PostingSayDamage = "Кашляет кровью";
Готово

2024-09-04 16:47 UTC, FaDeOkno commented on Content.Server/ADT/BloodCough/BloodCoughSystem.cs
> +            Log.Debug($"Сущность {ToPrettyString(uid)} не имеет компонента BloodCoughComponent.");
DamageableComponent а не BloodCoughComponent

2024-09-04 16:49 UTC, FaDeOkno approved these changes

2024-09-04 17:09 UTC, merged

2024-09-04 17:12 UTC, Schrodinger71 commented on Content.Server/ADT/BloodCough/BloodCoughSystem.cs
> +            Log.Debug($"Сущность {ToPrettyString(uid)} не имеет компонента BloodCoughComponent.");
блятьацацаца