Добавление подносов
AdventureTimeSS14/space_station_ADT pull request #398
Opened 2024-09-03 16:53 UTC by Hyrmik

Добавление подноса в игру, а так же контрабандный "Особо острый поднос" в аплинке для ролей шеф-повар, ботаник, мим, клоун

## Описание PR

**Ссылка на публикацию в Discord**

- [Заказы-разработка](https://discord.com/channels/901772674865455115/1229710928157605960/1229710928157605960)

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлен поднос!
- add: Добавлен "Особо острый поднос" в аплинк агентам синдиката c профессиями: шеф-повар, ботаник, мим, клоун

2024-09-03 17:23 UTC, JustKekc commented
вот бы его респрайтнуть...

2024-09-03 17:24 UTC, JustKekc commented
_а впихнуть его в диннервэйв?_

2024-09-03 17:26 UTC, Hyrmik commented
Диннервейв?

2024-09-03 17:26 UTC, JustKekc commented
ну, вендомат с посудой у поваров.

2024-09-03 17:27 UTC, JustKekc commented
поднос, конечно, хорошо.
_но как его достать-то._

2024-09-03 17:46 UTC, Bolper commented
так
@1Stepka1 уже делаешь ревью?

2024-09-03 18:01 UTC, 1Stepka1 commented
> так @1Stepka1 уже делаешь ревью?

Нет ещё

2024-09-03 18:47 UTC, FaDeOkno requested changes
Вполне себе неплохое начало, но есть пара моментов

2024-09-03 18:47 UTC, FaDeOkno commented on Resources/Locale/ru-RU/ADT/prototypes/Catalog/store/bobr.ftl
> +uplink-ADTAntagIronTray-desc = Железный поднос c очень острыми краями.
Это магазин ОБР, а не аплинк синдиката

2024-09-03 18:47 UTC, FaDeOkno commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Misc/iron_tray.ftl
> +ent-ADTIronTray = Поднос
Имена entity всегда пишем с маленькой буквы

2024-09-03 18:47 UTC, FaDeOkno commented on Resources/Prototypes/ADT/Entities/Objects/Misc/tray.yml
> +#   TODO: ERROR FOOD & Drink нет таких тэгов
Надо править, судя по размерам хранилища

2024-09-03 18:50 UTC, Hyrmik commented on Resources/Locale/ru-RU/ADT/prototypes/Catalog/store/bobr.ftl
> +uplink-ADTAntagIronTray-desc = Железный поднос c очень острыми краями.
Получается вместо папки bobr надо было uplink-catalog?

2024-09-03 20:46 UTC, Schrodinger71 approved these changes
gg

2024-09-03 21:32 UTC, JustKekc commented
![png-transparent-smiley-emoticon-thumb-signal-emoji-dank-face-smiley-thumb-signal](https://github.com/user-attachments/assets/3a1a7dd6-e5a7-4939-afca-35f6a4dff6f4)

2024-09-03 21:32 UTC, JustKekc commented
_капец картинка огромная._

2024-09-03 21:36 UTC, Schrodinger71 commented
Жжжжжжжжжесть

2024-09-03 21:39 UTC, FaDeOkno approved these changes
По моему ревью всё исправлено 👍

2024-09-04 07:13 UTC, Schrodinger71 requested changes

2024-09-04 07:13 UTC, Schrodinger71 commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +    - Botanist
Посмотрел повнимательней, стоит сюда перенести этот прототип для аплинка https://github.com/AdventureTimeSS14/space_station_ADT/blob/master/Resources%2FPrototypes%2FADT%2FCatalog%2Fuplink_catalog.yml

2024-09-04 08:14 UTC, 1Stepka1 reviewed
Такс,а теперь идут мои размышления
Металлический поднос это больше узкоспециализированная штука относительно одного отдела, то есть сервиса. В misc же находятся в основном предметы общего назначения и некоторые другие приколы у которых трудно определить категорию или это связанно с мобами
Здесь же конкретно можно выделить типизацию подо что это. Поэтому предлагаю перенести из Resources/Prototypes/ADT/Entities/Objects/Misc/ в Resources\Prototypes\ADT\Entities\Objects\Specific\Service.
И да к тому же переименовать файлы,а то в locale это iron_tray а в прототипах это tray,не порядок

2024-09-04 17:57 UTC, 1Stepka1 requested changes
Такс,все таки ты прислушался к тому что я сказал,но ты перенес только прототипы,а надо и спрайты тоже перенести

2024-09-04 17:58 UTC, 1Stepka1 commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Specific/Chemistry/iron_tray.ftl
Такс а что это делается в химии?

2024-09-04 18:11 UTC, Hyrmik commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Specific/Chemistry/iron_tray.ftl
Там не совсем папка химии
![image](https://github.com/user-attachments/assets/e2592110-c3a8-4a05-9d8c-e1fd95ff49a8)
Она имеет два названия, но я перетащил локализацию в ту папку по которой и лежит прототипы

2024-09-04 18:19 UTC, Hyrmik commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Specific/Chemistry/iron_tray.ftl
Я вот сижу и не понимаю как такой путь может работать

2024-09-04 18:20 UTC, Hyrmik commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Specific/Chemistry/iron_tray.ftl
Он сразу в химию перекидывает..
![image](https://github.com/user-attachments/assets/193f6c8e-bdf0-4b07-80b9-dc2f2bf5edba)

2024-09-04 18:20 UTC, Hyrmik commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Specific/Chemistry/iron_tray.ftl
Магия не иначе

2024-09-04 18:20 UTC, Bolper commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Specific/Chemistry/iron_tray.ftl
Хм? 
![Screenshot_2024-09-04-21-20-00-256_com android chrome](https://github.com/user-attachments/assets/22bb1f9c-4dd1-4839-b85a-5629593d05aa)
Что у тя там..

2024-09-04 18:21 UTC, Bolper commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Specific/Chemistry/iron_tray.ftl
То то это то, но причём тут серьёзно поднос...

2024-09-04 18:21 UTC, Hyrmik commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Specific/Chemistry/iron_tray.ftl
А кажись понял 
![73094-sadface](https://github.com/user-attachments/assets/5571dfdf-e482-421b-96b7-74a68663d1e5)

2024-09-04 18:21 UTC, Hyrmik commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Specific/Chemistry/iron_tray.ftl
Отличный гитхаб который сразу перекидывает через все папки

2024-09-04 18:23 UTC, Bolper commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Specific/Chemistry/iron_tray.ftl
Твои прототипы лежат по этому пути
Resources/Prototypes/ADT/Entities/Objects/Specific/Service/Iron_tray.yml

2024-09-04 18:25 UTC, Hyrmik commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Specific/Chemistry/iron_tray.ftl
Я знаю, но вот из-за такой фигни и кинул не туда

https://github.com/user-attachments/assets/9087f5ea-c782-4180-badf-895b02a1b8bb

2024-09-05 07:27 UTC, 1Stepka1 approved these changes
Теперь по идее всё в поряде

2024-09-05 07:35 UTC, Schrodinger71 approved these changes

2024-09-05 07:35 UTC, merged