Хачапури ТЗ от Дубика
AdventureTimeSS14/space_station_ADT pull request #400
Opened 2024-09-03 21:10 UTC by Inconnu1337

## Описание PR

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Inconnu
- add: Добавлено Хачапуре, рецепт приготовления и перевод

2024-09-03 21:28 UTC, FaDeOkno requested changes
Всё супер, осталась пара незначительных моментов

2024-09-03 21:28 UTC, FaDeOkno commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/meals.ftl
> +ent-FoodMealKhachapuri = хачапури
Следует перенести в папку ADT
/Locale/re-RU/ADT/prototypes/entities...

2024-09-03 21:28 UTC, FaDeOkno commented on Resources/Prototypes/Entities/Objects/Consumable/Food/meals.yml
> +- type: entity
Перенеси в ADT папку (Prototypes/ADT/Entities...)

2024-09-03 21:28 UTC, FaDeOkno commented on Resources/Prototypes/Recipes/Cooking/meal_recipes.yml
> +- type: microwaveMealRecipe
В ADT папку (Prototypes/ADT/Recipes...)

2024-09-03 21:28 UTC, FaDeOkno commented on Resources/Textures/Objects/Consumable/Food/meals.rsi/meta.json
> +	  "name": "khachapuri"
Нужно сделать отдельный rsi файл в ADT папке

2024-09-03 21:28 UTC, FaDeOkno commented on Resources/Prototypes/Entities/Objects/Consumable/Food/meals.yml
> +  id: FoodMealKhachapuri
В начале айди добавь ADT (ADTFoodMealKhachapuri)

2024-09-04 06:32 UTC, Schrodinger71 commented
Юбилейный пр 🥳

2024-09-04 17:05 UTC, Schrodinger71 commented
@Inconnu1337 
![image](https://github.com/user-attachments/assets/9f1f2dee-66d1-4869-bed5-33b2ec57231a)

2024-09-05 07:34 UTC, 1Stepka1 requested changes
Вкину ещë к тому что котя добавил

2024-09-05 07:34 UTC, 1Stepka1 commented on Resources/Textures/ADT/Objects/Consumable/Food/meals.rsi/meta.json
> +  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/c6e3401f2e7e1e55c57060cdf956a98ef1fefc24, taco from https://github.com/ss220-space/Paradise/commit/6c9bd82
Не правильный копирайт я не вижу нигде такого спрайта, так что сноси всё что есть в copyright и установить правильный копирайт. Скорее всего это риосваоось нашими ребятами так что спроси в дискорде кто автор

2024-09-05 14:03 UTC, Inconnu1337 commented on Resources/Textures/ADT/Objects/Consumable/Food/meals.rsi/meta.json
> +  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/c6e3401f2e7e1e55c57060cdf956a98ef1fefc24, taco from https://github.com/ss220-space/Paradise/commit/6c9bd82
исправил

2024-09-05 17:48 UTC, Bolper commented
@Inconnu1337 
на будущее, если ты решил проблему, то нажимай кнопочке "resolve conservation"
Чтобы знали, ты решил проблему или нет~
![image](https://github.com/user-attachments/assets/db9cd0f8-2796-4013-9895-50c3569ecf45)

2024-09-05 18:43 UTC, FaDeOkno approved these changes

2024-09-06 09:36 UTC, 1Stepka1 submitted a review, later dismissed

2024-09-06 09:36 UTC, 1Stepka1 commented on Resources/Prototypes/Recipes/Cooking/meal_recipes.yml
> +
Убери дубликат рецепта

2024-09-06 09:36 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/meals.yml
> +    sprite: ADT\Objects\Consumable\Food\meals.rsi
не те черты поставил фраерок
надо / а не \ с виндовского проводника, тут нету обратной совместимости

2024-09-07 00:21 UTC, Schrodinger71 approved these changes

2024-09-07 00:22 UTC, merged