Добавлены страйкбольные приводы в исследования РНД и техфаб СБ, а также именная вещь Maki_GG
AdventureTimeSS14/space_station_ADT pull request #434
Opened 2024-09-08 17:52 UTC by Inconnu1337

## Описание PR

**Ссылка на публикацию в Discord**

- [Заказы-разработка](https://discord.com/channels/901772674865455115/1281996202006548521/1281996202006548521)
- [Предложения](https://discord.com/channels/901772674865455115/1279092359849578600/1279092359849578600)

**Медиа**

![2024-9-08_17 47 42](https://github.com/user-attachments/assets/36d521bb-99f9-4ca6-8ff7-ac29025f8ee6)
![2024-9-08_17 48 51](https://github.com/user-attachments/assets/ca972a83-e600-4a45-84ac-72525c0a7bc9)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Inconnu
- add: Добавлена именная вещь Maki_GG - Пальто Хонкоматери
- add: Добавлены страйкбольные приводы в техфаб СБ и исследования РНД на первый тир за 5000 и.о.

2024-09-08 18:02 UTC, Bolper commented
пон

2024-09-08 18:13 UTC, Ratyyy submitted a review, later dismissed
вроде, всё хорошо. Мета - в норме, комментарии есть где нужно

2024-09-08 18:15 UTC, Bolper requested changes
![image](https://github.com/user-attachments/assets/ef12da71-7ae6-4670-8044-c6b31d9789bd)
И зачем мы хотим в чейнджлоги добавлять то, что в игру добавлена именная вещь? Переделатц

2024-09-08 18:15 UTC, Bolper commented on Resources/Prototypes/Recipes/Lathes/security.yml
> +    Plastic: 50
те не кажется что ты тут цифоркамии ошибся?
Как бы пулька - 50, а целый магазин 150? Серьезно?

2024-09-08 18:15 UTC, Bolper commented on Resources/Prototypes/Recipes/Lathes/security.yml
И тебе куда было сказано это добавлять? в папку ADT

2024-09-08 18:15 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Personalization/Clothing/personalization_clothing.yml
> +  description: Maki coat.
насрал в именах и описании, ужс..

2024-09-08 18:17 UTC, Ratyyy requested changes
а, точно, если добавлять страйкбол то и к нему броню соответствующею, которая будет давать отрицательный резист к урону по стамине. Вместе с этим и уменьшить стамина урон у страйкбольного оружия

2024-09-08 18:21 UTC, Bolper commented
> а, точно, если добавлять страйкбол то и к нему броню соответствующею, которая будет давать отрицательный резист к урону по стамине. Вместе с этим и уменьшить стамина урон у страйкбольного оружия

Я не вижу ни слова об этом в ПРе, следовательно как то это не является особо предметом чейндж ревеста, но как бы ок, было бы не плохо добавить

2024-09-08 18:26 UTC, Ratyyy commented
> > а, точно, если добавлять страйкбол то и к нему броню соответствующею, которая будет давать отрицательный резист к урону по стамине. Вместе с этим и уменьшить стамина урон у страйкбольного оружия
> 
> Я не вижу ни слова об этом в ПРе, следовательно как то это не является особо предметом чейндж ревеста, но как бы ок, было бы не плохо добавить

добавить скорее обязательно. Без неё страйкбольное оружие быстрое станет заменой резины

2024-09-08 18:29 UTC, Inconnu1337 commented on Resources/Prototypes/ADT/Entities/Personalization/Clothing/personalization_clothing.yml
> +  description: Maki coat.
че насрал? я смотрел как это сделано в пальто эйдана

2024-09-08 18:29 UTC, Inconnu1337 commented on Resources/Prototypes/Recipes/Lathes/security.yml
> +    Plastic: 50
по такой логике 1 магазин должен стоит 100 стали

2024-09-08 18:48 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Personalization/Clothing/personalization_clothing.yml
> +  description: Maki coat.
![Screenshot_2024-09-08-21-47-42-585_com.android.chrome.png](https://github.com/user-attachments/assets/dc7dcf01-e566-4c3c-adb5-9cc7d2014d72)

Сравнил же ведь...

2024-09-08 18:50 UTC, Bolper commented on Resources/Prototypes/Recipes/Lathes/security.yml
> +    Plastic: 50
По такой логике, это пульке должна меньше стоить, а не возрастать цена магазина

2024-09-08 18:59 UTC, Bolper commented
> > > а, точно, если добавлять страйкбол то и к нему броню соответствующею, которая будет давать отрицательный резист к урону по стамине. Вместе с этим и уменьшить стамина урон у страйкбольного оружия
> > 
> > Я не вижу ни слова об этом в ПРе, следовательно как то это не является особо предметом чейндж ревеста, но как бы ок, было бы не плохо добавить
> 
> добавить скорее обязательно. Без неё страйкбольное оружие быстрое станет заменой резины

Наверно. И да. У нас нет резины. Вхах

2024-09-09 20:00 UTC, Inconnu1337 commented on Resources/Prototypes/ADT/Entities/Personalization/Clothing/personalization_clothing.yml
> +  description: Maki coat.
Так это перевод уже, у пальта маки тоже есть перевод

2024-09-09 20:01 UTC, Inconnu1337 commented
Страйкбольная броня в коммите с фиксом перевода ОБР медика туда случайно попала не обращайте внимания

2024-09-10 06:45 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/armor.yml
> +        Blunt: 4
Не тот коэффициент

2024-09-10 06:51 UTC, Schrodinger71 commented on Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/armor.yml
> +        Blunt: 4
0.1 это 90 % защиты
0.9 соответственно 10% защиты

2024-09-10 06:53 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/armor.yml
> +        Blunt: 4
Да знает это все он

2024-09-14 09:07 UTC, Bolper commented on Resources/Locale/ru-RU/ADT/armor/armor.ftl
Не в том месте. Найдешь сам. Папочка прототипы есть так то

2024-09-15 07:39 UTC, Bolper approved these changes

2024-09-15 10:07 UTC, merged