Little things update
AdventureTimeSS14/space_station_ADT pull request #442
Opened 2024-09-09 16:35 UTC by AnderFan

Перенесены:
- Обручальные кольца
- Банный веник
- Деревянный лежак
- Свадебные платья
- Свадебные букеты
- Добавлен в список заказов: набор колец, свадебный набор.

2024-09-10 18:17 UTC, 1Stepka1 requested changes
В Resources/Textures/ADT/Objects/Weapons/ находятся букеты,хоть сами букеты находятся в Resources/Prototypes/ADT/Entities/Objects/Specific/Service/bouquets.yml значит путь у них должен быть Resources/Textures/ADT//Objects/Specific/Service/bouquets.rsi

2024-09-10 18:17 UTC, 1Stepka1 commented on Resources/Locale/ru-RU/ADT/Catalog/Cargo/cargo_fun.ftl
Неверное расположение, переместить в Resources/Locale/ru-RU/ADT/prototypes/Catalog/cargo/

2024-09-10 18:17 UTC, 1Stepka1 commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Clothing/Hand/gloves.ftl
Папка должна называться Hands а не Hand

2024-09-10 18:17 UTC, 1Stepka1 commented on Resources/Prototypes/Recipes/Construction/Graphs/furniture/bed.yml
> +              doAfter: 1
С днем комментариев

2024-09-10 18:17 UTC, 1Stepka1 commented on Resources/Prototypes/Recipes/Construction/Graphs/furniture/bed.yml
> +              doAfter: 1
С днем комментариев 2

2024-09-23 16:31 UTC, Bolper requested changes
че то хотел сказать но забыл... Чекни свой ПР на актуальность

2024-09-23 16:31 UTC, Bolper commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Clothing/Uniforms/jumpskirts.ftl
> +    .desc = Оно не слишком короткое? Мою попу не видно?
АХАХАХАХАХХАХАХХА. Шикарно.

2024-09-23 16:31 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Objects/Misc/ring_box.yml
Пупупу... Так как оно заполнено то в Resources\Prototypes\ADT\Catalog\Fills\Boxes\service.yml
Но там как, там оно будет парентится. так что заполнение там всего лишь добавляешь а тут его убираешь

2024-09-23 16:31 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Clothing/Hands/gloves.yml
Я уж честно не помню чьи эти кольца. Но если наши, то добавить ADT к id

2024-09-23 16:31 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Objects/Misc/ring_box.yml
И эт вообще в сервис, ибо относится к священнику, тобишь в Resources/Prototypes/ADT/Entities/Objects/Specific/Service/

2024-09-23 16:31 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Objects/Specific/Service/bouquets.yml
к чему в id WeaponsMelee?

2024-09-23 16:31 UTC, Bolper commented on Resources/Prototypes/Recipes/Construction/Graphs/furniture/bed.yml
> +              doAfter: 1
С днем коомментариев номер два.  Да и вообще сделай лучше свой граф. А кстати. ты кажись опоздал и такая фигня уже есть

2024-09-23 16:31 UTC, Bolper commented on Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/airy_white_suit.rsi/meta.json
ваще класс, 2 спрайта ез inhand. прикольно будет в руках смотрется целый костюм, тобишь никак

2024-09-24 14:53 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Entities/Objects/Specific/Service/bouquets.yml
Примечание довольно верное,никак не описывающие предмет вещь

2024-10-02 22:49 UTC, PyotrIgn commented on Resources/Textures/ADT/Objects/Weapons/Melee/black_bouquet.rsi/meta.json
Решено

2024-10-02 23:00 UTC, PyotrIgn commented on Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/airy_white_suit.rsi/meta.json
Ну тут вопрос к Луне, почему без инхэнда, с Андерфана и меня взятки гладки, спрайту 10 000 лет

2024-10-02 23:04 UTC, PyotrIgn commented on Resources/Prototypes/ADT/Entities/Clothing/Hands/gloves.yml
Добавил

2024-10-02 23:04 UTC, PyotrIgn commented on Resources/Prototypes/ADT/Entities/Objects/Specific/Service/bouquets.yml
Убрал WeaponsMelee, перенес спрайт

2024-10-02 23:07 UTC, PyotrIgn commented on Resources/Prototypes/ADT/Entities/Objects/Misc/ring_box.yml
Переношу заполненную коробку в ADT/Entities/Objects/Specific/Service/

2024-10-02 23:08 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Clothing/Uniforms/jumpskirts.ftl
> +    .desc = Оно не слишком короткое? Мою попу не видно?
Старые описания. Жили тут 1000 лет, пусть и дальше

2024-10-02 23:10 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Clothing/Hand/gloves.ftl
> +ent-RingBox = коробка с кольцами
Перенес в \Locale\ru-RU\ADT\prototypes\Entities\Objects\Specific\Service\Ring_box.ftl

2024-10-02 23:11 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Clothing/Hand/gloves.ftl
Сделал handa, переименовал gloves в rings

2024-10-02 23:14 UTC, PyotrIgn commented on Resources/Prototypes/Recipes/Construction/Graphs/furniture/bed.yml
> +              doAfter: 1
утратило актуальность, так как вещь была добавлена в другом ПР. Убрал её

2024-10-02 23:15 UTC, PyotrIgn commented on Resources/Prototypes/Recipes/Construction/Graphs/furniture/bed.yml
> +              doAfter: 1
Утратила актуальность так как вещь добавлена в другом ПР, убрал этот крафт

2024-10-02 23:15 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Clothing/Hand/gloves.ftl
Переименовано

2024-10-02 23:26 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/Catalog/Cargo/cargo_fun.ftl
Переместил спрайты букетов в сервис
Локализация для карго утратила актуальность - теперь оно называется как называется заказываемый груз, потому удалил лишние файлы

2024-10-02 23:27 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/Catalog/Cargo/cargo_fun.ftl
Локализация для карго утратила актуальность - теперь оно называется как называется заказываемый груз, потому удалил лишние файлы

2024-10-02 23:34 UTC, PyotrIgn commented
@Bolper @1Stepka1 
Взял на доведение до конца этот пулл реквест
Поработал по вашим ревью, проверяйте

2024-10-03 15:25 UTC, 1Stepka1 approved these changes

2024-10-03 15:41 UTC, merged