Добавил проверку, не держат ли при рандомном телепорте в системе Shadekin
AdventureTimeSS14/space_station_ADT pull request #470
Opened 2024-09-13 13:39 UTC by Mirokko

## Описание PR

Не буду повторяться, это баг и надо было как-то его пофиксить

**Ссылка на публикацию в Discord**

- [Баги](https://discord.com/channels/901772674865455115/1283294949328294022)

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- fix: Теперь когда сумеречник

2024-09-13 19:36 UTC, FaDeOkno commented on Content.Server/ADT/Shadekin/ShadekinSystem.cs
> +        if (TryComp<PullableComponent>(uid, out var mainEntityPullable) && mainEntityPullable.BeingPulled)
Уж лучше проверять на наручники, а для телепорта просто убирать таскание

2024-09-13 19:47 UTC, Mirokko commented on Content.Server/ADT/Shadekin/ShadekinSystem.cs
> +        if (TryComp<PullableComponent>(uid, out var mainEntityPullable) && mainEntityPullable.BeingPulled)
тоже можно, но это только для рандомного телепорта. поэтому посчитал этот способ вполне логичным

2024-09-15 06:42 UTC, Bolper commented on Content.Server/ADT/Shadekin/ShadekinSystem.cs
> +        if (TryComp<PullableComponent>(uid, out var mainEntityPullable) && mainEntityPullable.BeingPulled)
Ребят, вы решайте, что по итогу будет. Потому что лично для меня, очень серьеный вопрос: почему, если тебя держат то ты не можешь телепортироватся. Я соглашусь с Котькой в этом вопросе. Проверка на наручники.

2024-09-16 06:27 UTC, Mirokko commented on Content.Server/ADT/Shadekin/ShadekinSystem.cs
> +        if (TryComp<PullableComponent>(uid, out var mainEntityPullable) && mainEntityPullable.BeingPulled)
Просто на наручники? Без держания?

2024-09-16 07:10 UTC, Mirokko commented on Content.Server/ADT/Shadekin/ShadekinSystem.cs
> +        if (TryComp<PullableComponent>(uid, out var mainEntityPullable) && mainEntityPullable.BeingPulled)
Сделал, в общем. Если не так - скажете.

2024-09-16 09:32 UTC, Bolper commented
Как я смотрю все ок. Но подожду мнение котьки

2024-09-16 19:32 UTC, FaDeOkno approved these changes

2024-09-16 19:33 UTC, FaDeOkno commented
Проблем нет

2024-09-16 19:59 UTC, KashRas2 requested changes

2024-09-16 19:59 UTC, KashRas2 commented on Content.Server/ADT/Shadekin/ShadekinSystem.cs
> +        if (TryComp<CuffableComponent>(uid, out var cuffable) && _cuffable.IsCuffed((uid, cuffable), true))
Комментарии извольте

2024-09-16 20:03 UTC, KashRas2 commented on Content.Server/ADT/Shadekin/ShadekinSystem.cs
> +        if (TryComp<CuffableComponent>(uid, out var cuffable) && _cuffable.IsCuffed((uid, cuffable), true))
Ладно, ошибся

2024-09-16 20:03 UTC, KashRas2 approved these changes

2024-09-16 20:58 UTC, merged