Добавление неко арка
AdventureTimeSS14/space_station_ADT pull request #471
Opened 2024-09-13 15:12 UTC by daniloedc4

## Описание PR

**Ссылка на публикацию в Discord**

- [Технические проблемы](ссылка)
- [Баги](ссылка)
- [Заказы-разработка](ссылка)
- [Предложения](ссылка)
- [Перенос контента](ссылка)

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: daniloedc4
- add: Добавлено плюшевая игрушка Неко-Арка

2024-09-15 12:40 UTC, Bolper commented
Я считай эт делал. Не буду я тут ревью делать

2024-09-15 12:42 UTC, Darkiich commented
> Я считай эт делал. Не буду я тут ревью делать

Ну нихуя себе предъява

2024-09-16 23:42 UTC, Schrodinger71 requested changes
Атрибуты к звукам, хде? откуда

2024-09-17 14:30 UTC, 1Stepka1 requested changes
Все аудиофайлы переместить в Resources/Audio/ADT/Items/Toys а так же добавить файл attributions.yml

2024-09-17 14:30 UTC, 1Stepka1 commented on Resources/Textures/ADT/Objects/Fun/nekoArc.rsi/meta.json
У нас игрушки находятся по другому пути,а именно Resources/Textures/ADT/Objects/Fun/toys.rsi
Поэтому туда перенеси спрайт и фрагмент из меты

2024-10-13 09:02 UTC, Darkiich commented
Закрываю PR, по причине отсутствия активности более месяца для такой маленькой вещицы

2024-10-13 09:02 UTC, closed without merging