Перенос мебели со старой сборки.
AdventureTimeSS14/space_station_ADT pull request #485
Opened 2024-09-16 00:27 UTC by Filokini

Перенёс мебель с прошлой сборки.
Если есть вопросы по рецептам, я их не трогал, но если есть предложение и аргументы, то почему бы и нет.
Вроде всё работало при проверках
:cl: Filo
- add: Были возвращены в массы потерянные знания о создании некоторой мебели.

2024-09-16 00:34 UTC, Filokini commented
Чинить уже завтра

2024-09-16 00:39 UTC, Filokini commented
А я локаль забыл закинуть...

2024-09-16 13:15 UTC, Filokini commented
поторопился с запросом ревью, щас закину еще мебель

2024-09-16 21:02 UTC, PyotrIgn commented
ну судя по проверкам - надо починить что-то в крафте костерка

2024-09-16 22:53 UTC, Filokini commented
Да ёб

2024-09-16 23:03 UTC, Filokini commented
Она ДОЛЖНА пройти

2024-09-16 23:24 UTC, Filokini commented
Проверки прошли!

2024-09-17 04:29 UTC, Bolper commented
Класс

2024-09-17 08:10 UTC, Filokini commented
Жду ревью

2024-09-17 14:48 UTC, 1Stepka1 requested changes
К тому же всему что находится в Resources/Prototypes/ADT/Entities/Structures/Furniture/ надо в названии файлов писать их во множественном числе там где внутри них больше одной сущности(за исключением базы и заполненных версий если имеются)
Так же заметил что по мимо названия файлов Stool используются и прочие написание данного слово в других местах,было бы лучше изменить его на chair везде где оно упоминяется

2024-09-17 14:48 UTC, 1Stepka1 commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Structures/Furniture/stools.ftl
Stool конечно прикольное название,но надо изменить на chairs.ftl

2024-09-17 14:48 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Entities/Structures/Furniture/chair.yml
Угу,то есть в locale мы файлы отдельно,а в yml вместе?
Не порядок, лучше уж в отдельные файлы то что определили там armchair а именно chair(у вас это Stool) оставить в этом файле

2024-09-18 16:48 UTC, Bolper requested changes

2024-09-18 16:48 UTC, Bolper commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Structures/Furniture/armchairs.ftl
Описания без точек. Найс

2024-09-18 16:48 UTC, Bolper commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Structures/Furniture/sofas.ftl
тож самое. чудо инженерной мысли и точки.

2024-09-18 16:48 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Structures/Furniture/armchairs.yml
Создать Базу для кресла видимо была не судьба... Но раз перенос то как бы и ладно, но как бы и не есть гуд

2024-09-18 16:48 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Structures/Furniture/beds.yml
???

2024-09-18 16:48 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Structures/Furniture/chairs.yml
Про базу думаю бессмысленно говорить

2024-09-18 16:48 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Structures/Furniture/sofas.yml
> +  id: ADTChurchBenchLeftSide
че это тут делает

2024-09-18 16:48 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Structures/Furniture/sofas.yml
> +  id: ADTChurchBenchMiddle
+

2024-09-18 16:48 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Structures/Furniture/sofas.yml
> +  id: ADTChurchBenchRightSide
+

2024-09-18 16:48 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Structures/Furniture/sofas.yml
че с ID диванов? Почему половина хрен пойми что? не должно быть никаких Black, White между ADT и Sofa. Это все после. Как тут ADTSofaWhiteLeftSide

2024-09-18 16:48 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Structures/Furniture/tables.yml
Че у нас опять с ID столов?

2024-09-18 16:48 UTC, Bolper commented on Resources/Prototypes/ADT/Recipes/Construction/Graph/furniture/beds.yml
???

2024-09-18 16:48 UTC, Bolper commented on Resources/Prototypes/ADT/Recipes/Construction/Graph/fun/discoball.yml
Если работает то ок. Но жду для подтверждения этого в ПРе медиа инфу об этом

2024-09-18 16:48 UTC, Bolper commented on Resources/Prototypes/ADT/Recipes/Construction/Graph/furniture/roundtables.yml
Я уже говорил насчет id

2024-09-18 16:48 UTC, Bolper commented on Resources/Textures/ADT/Personalization/gold-crowbar.rsi/meta.json
Я уже говорил. Нет в описании ПРа.
Во вторых. Почему мету так перекосило? 
![image](https://github.com/user-attachments/assets/cc0f0f6d-dc68-46f4-b421-a135ca8b7b4b)
называется найди 1 отличие

2024-09-18 16:48 UTC, Bolper commented on Resources/Textures/ADT/Structures/Furniture/armchairsluna.rsi/meta.json
Мы либо делаем отдельную папку для всех кресел либо пихаем в 1 файл.

2024-09-18 16:48 UTC, Bolper commented on Resources/Textures/ADT/Structures/Furniture/chairs.rsi/meta.json
Тож самое касается стульев

2024-09-18 16:48 UTC, Bolper commented on Resources/Textures/ADT/Structures/Furniture/bed_double.rsi/meta.json
???

2024-09-18 16:48 UTC, Bolper commented on Resources/Textures/ADT/Structures/Furniture/oktoberfest_table.rsi/meta.json
И столов

2024-09-19 01:24 UTC, Filokini commented
короче я что то сделал
и не могу найти, я заебался уже пока искал почему он не может найти пути.

2024-09-19 01:24 UTC, Filokini commented
пути в строительстве если шо

2024-09-19 01:24 UTC, Filokini commented
помогите пж, я idk

2024-09-19 14:17 UTC, Filokini commented
@Bolper Готово

2024-09-19 14:19 UTC, Bolper commented
@Filokini не вижу по меток о том что они решены![Screenshot_2024-09-19-17-19-12-311_com.github.android.png](https://github.com/user-attachments/assets/02261aa9-0b6e-495f-a421-0bef003e3b44)

2024-09-19 15:20 UTC, Bolper commented
у тя ямл упавший

2024-09-19 16:19 UTC, Filokini commented
Как бы я сам не упал

2024-09-19 23:21 UTC, PyotrIgn requested changes
В целом все неплохо. По комментариям сделай небольшую сортировку и можно заливать.

2024-09-19 23:21 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Structures/Furniture/armchairs.ftl
для точного воспроизведения и сохранения структуры файлов как у оффов/корваксов (для удобства поиска потом) лучше перенести это все в chairs

2024-09-19 23:21 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Structures/Furniture/sofas.ftl
Немного отклоняемся от визардской структуры файлов, с одной стороны. С другой - диванов там нет. Так что софы оставляем.

2024-09-19 23:21 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Structures/Furniture/armchairs.ftl
Перенеси локализации в chairs отсюда. Ну и этот файл потом удали, т.к. он пустой будет

2024-09-19 23:21 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Structures/Furniture/sofas.ftl
У оффов такого нет. Но и диванов у них тоже нет. Оставляй.

2024-09-19 23:21 UTC, PyotrIgn commented on Resources/Prototypes/ADT/Entities/Structures/Furniture/armchairs.yml
Перенеси содержимое в chairs.yml

2024-09-19 23:21 UTC, PyotrIgn commented on Resources/Prototypes/ADT/Entities/Structures/Furniture/party.yml
Переименуй файл в misc.yml. Будет использоваться для "разного" из мебели

2024-09-19 23:21 UTC, PyotrIgn commented on Resources/Prototypes/ADT/Entities/Structures/Furniture/armchairs.yml
И аналогично сделай с папками спрайтов. Не забудь потом поменять ссылки

2024-09-19 23:21 UTC, PyotrIgn commented on Resources/Prototypes/ADT/Entities/Structures/Furniture/tables.yml
В ADTTableRedWood ссылка имеет лишний слэш

2024-09-19 23:21 UTC, PyotrIgn commented on Resources/Prototypes/ADT/Recipes/Construction/Graph/furniture/roundtables.yml
Перенеси этот крафт в tables.yml

2024-09-19 23:21 UTC, PyotrIgn commented on Resources/Prototypes/ADT/Recipes/Construction/furniture.yml
Не забудь и тут поменять ссылки, когда содержимое папки текстур Armchair будешь переносить в Chair

2024-09-19 23:22 UTC, PyotrIgn commented
Ну и нельзя не сказать, что ты большой молодец, проделал такую непростую работу.

2024-09-20 12:03 UTC, PyotrIgn approved these changes

2024-09-20 20:59 UTC, PyotrIgn approved these changes

2024-09-20 20:59 UTC, merged