Добавил обычные фоны в лобби
AdventureTimeSS14/space_station_ADT pull request #495
Opened 2024-09-17 19:03 UTC by Darkiich

## О пулл реквесте

## Почему / Баланс

**Ссылка на публикацию в Discord**

## Техническая информация

## Медиа

## Требования

- [ ] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [ ] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

## Критические изменения

**Чейнджлог**

2024-09-19 15:19 UTC, Bolper requested changes
![изображение](https://github.com/user-attachments/assets/b216ab96-f1fc-4b58-81ae-aaaa092a63d9)
Пон
И я не понял как то прикола. animatedLobbyScreen?

2024-09-20 07:27 UTC, Darkiich commented
> ![изображение](https://private-user-images.githubusercontent.com/169089627/369062196-b216ab96-f1fc-4b58-81ae-aaaa092a63d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MTc0MDMsIm5iZiI6MTcyNjgxNzEwMywicGF0aCI6Ii8xNjkwODk2MjcvMzY5MDYyMTk2LWIyMTZhYjk2LWYxZmMtNGI1OC04MWFlLWFhYWEwOTJhNjNkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQwNzI1MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjZiYTczZjNkZTg0ZWFmMjdkOWRhOGU0MmQ0NWM3NmZiN2NiY2RkOTQ4MzZlNzJmNjA2OWYxMjE4NjEyYjY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jzLMs9jEg6pBa1kH8T4dImogDjVDPLxvWT_HnbeuwYI) Пон И я не понял как то прикола. animatedLobbyScreen?

Это я сам сделаю, я жду ревью только по файлам. И да, animatedLobbyScreen

2024-09-23 16:53 UTC, Bolper requested changes

2024-09-23 16:53 UTC, Bolper commented on Resources/Prototypes/ADT/lobbyscreensanimated.yml
Хоть и у нас тип animatedLobbyScreen, но как ты сказал эт не важно, по этому в Resources/Prototypes/ADT/lobbyscreens.yml
А лучше бы вообще починил посредством того, что ты бы поставил в Resources/Prototypes/lobbyscreens.yml просто другой тип и указал ADT Tweak

2024-09-24 14:50 UTC, 1Stepka1 commented
> > ![изображение](https://private-user-images.githubusercontent.com/169089627/369062196-b216ab96-f1fc-4b58-81ae-aaaa092a63d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MTc0MDMsIm5iZiI6MTcyNjgxNzEwMywicGF0aCI6Ii8xNjkwODk2MjcvMzY5MDYyMTk2LWIyMTZhYjk2LWYxZmMtNGI1OC04MWFlLWFhYWEwOTJhNjNkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQwNzI1MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjZiYTczZjNkZTg0ZWFmMjdkOWRhOGU0MmQ0NWM3NmZiN2NiY2RkOTQ4MzZlNzJmNjA2OWYxMjE4NjEyYjY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jzLMs9jEg6pBa1kH8T4dImogDjVDPLxvWT_HnbeuwYI) Пон И я не понял как то прикола. animatedLobbyScreen?
> 
> Это я сам сделаю, я жду ревью только по файлам. И да, animatedLobbyScreen

Ревью не будет пока ты не даешь понятия ревьюрерам что ты хотел сделать этими изменениями,для этого и оформляется пр

2024-09-25 11:01 UTC, Darkiich commented
> > > ![изображение](https://private-user-images.githubusercontent.com/169089627/369062196-b216ab96-f1fc-4b58-81ae-aaaa092a63d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MTc0MDMsIm5iZiI6MTcyNjgxNzEwMywicGF0aCI6Ii8xNjkwODk2MjcvMzY5MDYyMTk2LWIyMTZhYjk2LWYxZmMtNGI1OC04MWFlLWFhYWEwOTJhNjNkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQwNzI1MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjZiYTczZjNkZTg0ZWFmMjdkOWRhOGU0MmQ0NWM3NmZiN2NiY2RkOTQ4MzZlNzJmNjA2OWYxMjE4NjEyYjY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jzLMs9jEg6pBa1kH8T4dImogDjVDPLxvWT_HnbeuwYI) Пон И я не понял как то прикола. animatedLobbyScreen?
> > 
> > 
> > Это я сам сделаю, я жду ревью только по файлам. И да, animatedLobbyScreen
> 
> Ревью не будет пока ты не даешь понятия ревьюрерам что ты хотел сделать этими изменениями,для этого и оформляется пр

Ну а по названию ПРа видимо не понятно, что я сделал

2024-09-27 19:06 UTC, closed without merging