Перенесы слизне-котики, а также добавлены именные вещи Syrel
AdventureTimeSS14/space_station_ADT pull request #515
Opened 2024-09-23 02:23 UTC by Inconnu1337

## Описание PR

Перенесы слизне-котики со старой сборки и улучшены по заказу sadboiiiiiiiiiiiiiiiiiiiii
Добавлен именной боевой топор и чехол для него [Syrel]
## Почему / Баланс

**Ссылка на публикацию в Discord**

## Медиа

![2024-9-23_04 54 15](https://github.com/user-attachments/assets/5b53ca86-ced0-48bc-a8eb-a6fae813e9fa)
![2024-9-23_04 55 44](https://github.com/user-attachments/assets/a8c91bfb-0d71-4280-bdae-ac7411f9ab02)
## Требования

- [x] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [x] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

**Чейнджлог**

:cl: 
- add: Добавлены слизне-котики. Мяу >-<

2024-09-23 02:28 UTC, Inconnu1337 commented
если кто-то знает как упростить локаль слизне-котика подскажите

2024-09-23 10:28 UTC, FaDeOkno submitted a review, later dismissed

2024-09-23 10:28 UTC, FaDeOkno commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Mobs/SlugCats/slugcat.ftl
> +ent-ADTMobSlugCatCreek = Слизне-кот
С маленькой буквы

2024-09-23 10:28 UTC, FaDeOkno commented on Resources/Prototypes/ADT/Entities/Mobs/SlugCats/slugcat.yml
> +        Slash: 0
Пусть все же будет урон, а то как-то не очень выходит

2024-09-23 10:28 UTC, FaDeOkno commented on Resources/Prototypes/tags.yml
> +  id: ADTSyrelBattleAxe
Зачем этот тэг?

2024-09-23 10:28 UTC, FaDeOkno commented on Resources/Prototypes/ADT/Entities/Mobs/SlugCats/slugcat.yml
> +  - type: Hands
У него точно в игре руки есть?

2024-09-23 10:33 UTC, FaDeOkno commented on Resources/Prototypes/tags.yml
> +  id: ADTSyrelBattleAxe
Все, уже понял

2024-09-23 11:54 UTC, Inconnu1337 commented on Resources/Prototypes/ADT/Entities/Mobs/SlugCats/slugcat.yml
> +        Slash: 0
Котик слишком скользкий чтобы наносить какой-то урон своими когтяшками поэтому взамен на 0 урона у него есть руки

2024-09-23 11:54 UTC, Inconnu1337 commented on Resources/Prototypes/ADT/Entities/Mobs/SlugCats/slugcat.yml
> +  - type: Hands
да, есть

2024-09-23 11:57 UTC, Inconnu1337 commented
На данный момент стоит **НЕ МЕРДЖИТЬ** потому-что возникает краш клиента при попытке найти предмет в меню спавна, и я пока не знаю как это решить
`[ERRO] go.comp.sprite: Unable to load RSI '/Textures/ADT/Personalization/syrel_sheath.rsi'.
[ERRO] go.comp.sprite: Layer has no RSI to load states from. Cannot use 'state' property. (sheath)`

2024-09-23 12:01 UTC, FaDeOkno commented on Resources/Prototypes/ADT/Entities/Mobs/SlugCats/slugcat.yml
> +        Slash: 0
> Котик слишком скользкий чтобы наносить какой-то урон своими когтяшками поэтому взамен на 0 урона у него есть руки

Ну значит по канону будет копьями кидаться

2024-09-23 12:06 UTC, FaDeOkno commented
> На данный момент стоит **НЕ МЕРДЖИТЬ** потому-что возникает краш клиента при попытке найти предмет в меню спавна, и я пока не знаю как это решить `[ERRO] go.comp.sprite: Unable to load RSI '/Textures/ADT/Personalization/syrel_sheath.rsi'.` `[ERRO] go.comp.sprite: Layer has no RSI to load states from. Cannot use 'state' property. (sheath)` @FaDeOkno если есть идеи подскажи

Перепиши названия файлов, в мете и прототипе вручную, мало ли

2024-09-23 17:01 UTC, Bolper commented
Ути какие слаймики

2024-09-24 09:15 UTC, Inconnu1337 commented
помогите 😭 😭
 😭 😭
 😭

2024-09-24 10:42 UTC, Inconnu1337 commented
ошибка с крашем клиента исправлена

2024-09-24 14:46 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Entities/Personalization/Clothing/personalization_clothing.yml
Эм,ты же просто удалил а не пофиксил?

2024-09-24 15:12 UTC, 1Stepka1 requested changes
Относительно изменений указанных в Resources/Prototypes/ADT/Entities/Mobs/SlugCats/slugcat.yml изменить Locale и Textures соответствующим образом

2024-09-24 15:12 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Entities/Mobs/SlugCats/slugcat.yml
Отдельная папочка лишняя тут
Перенести в Resources/Prototypes/ADT/Entities/Mobs/NPCs

2024-09-24 15:12 UTC, 1Stepka1 commented on Resources/Prototypes/tags.yml
Перенести в файл в нашей папке

2024-09-25 09:39 UTC, FaDeOkno commented
Теперь чини тесты

2024-09-25 16:49 UTC, Schrodinger71 commented
ПОЧИНЕНО

2024-09-25 20:08 UTC, Schrodinger71 approved these changes

2024-09-25 20:08 UTC, Schrodinger71 commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Mobs/NPCs/slugcat.ftl
> +    .desc = { ent-ADTMobSlugCatCreek.desc }
В целом всё ок, но у тебя слизне-коты разного цвета, наверн можно было бы и имя каждому прописать, красный, синий, зелёный и т.д.

крит. ошибок не заметил

2024-09-25 20:10 UTC, merged