Костюмчик для мя!
AdventureTimeSS14/space_station_ADT pull request #516
Opened 2024-09-23 10:15 UTC by RipZoro1

## Описание PR

Сделал себе костюмчик!
!

## Почему / Баланс

**Ссылка на публикацию в Discord**

## Техническая информация

## Медиа

## Требования

- [ ] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [ ] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

## Критические изменения

**Чейнджлог**

2024-09-23 10:17 UTC, RipZoro1 commented
ой бля, я опять что-то намудрил...

2024-09-23 10:23 UTC, Inconnu1337 commented
Зоро сделал ветку не от мастера поэтому катана и костюмчик теперь будут в этом ПРе
_прошлый закрыт_

2024-09-23 10:33 UTC, FaDeOkno submitted a review, later dismissed
Остальное вроде работает

2024-09-23 10:33 UTC, FaDeOkno commented on Resources/Locale/ru-RU/ADT/personalization.ftl
> +ent-ADTZoroKatana = Легендарная катана
С маленькой буквы

2024-09-23 10:33 UTC, FaDeOkno commented on Resources/Locale/ru-RU/ADT/personalization.ftl
> +ent-ADTClothingBeltZoroSheath = Ножны легендарной катаны
С маленькой буквы

2024-09-23 10:33 UTC, FaDeOkno commented on Resources/Locale/ru-RU/ADT/personalization.ftl
> +ent-ADTClothingZoroJumpsuit = Легендарный деловой костюм
С маленькой буквы

2024-09-24 07:30 UTC, Bolper requested changes

2024-09-24 07:30 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Personalization/Clothing/personalization_clothing.yml
> +  id: ADTClothingZoroJumpsuit
Uniform в id

2024-09-24 07:30 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Personalization/Objects/personalization_items.yml
> +        Slash: 17
Ахерел, больше чем у меня дамаг

2024-09-24 07:31 UTC, RipZoro1 commented on Resources/Prototypes/ADT/Entities/Personalization/Objects/personalization_items.yml
> +        Slash: 17
а чо...

2024-09-24 07:33 UTC, Bolper commented on Resources/Prototypes/ADT/Entities/Personalization/Objects/personalization_items.yml
> +        Slash: 17
Пон?

2024-09-24 07:41 UTC, Bolper approved these changes
Не маладца

2024-09-24 08:22 UTC, merged