Фиксы ХорниМух, заменяем урон от удушения при суициде на другой
AdventureTimeSS14/space_station_ADT pull request #531
Opened 2024-09-25 21:48 UTC by Schrodinger71

## Описание PR

Теперь сумеречники при суициде будут получать урон от кровотечения, а не от удушения. Замена.
Руководитель проекта @Filokini Все вопросы к нему!

## Почему / Баланс

У суммеров не должно быть дамага от удушения, что логично.

## Техническая информация

Добавлено небольшое условие в оффициальный код `Content.Server/Ghost/GhostSystem.cs`, на проверку ХорниМуха ли(Сумеречник) данное существо прожавшее суицид.

## Требования

- [ ] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [ ] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

## Критические изменения

**Чейнджлог**
NO CL, NO FUN!! FUCK!

2024-09-26 11:44 UTC, Mirokko commented
Чтобы не было щиткодинга, просто сделайте новый компонент - AlternativeDeathDamageComponent (название не оч, но я долго и не думал). И по нему уже определяйте, добавив всем сумеречникам.

2024-09-26 21:01 UTC, Schrodinger71 commented
а ну тупо пустой компонент как метка

2024-09-26 21:01 UTC, Schrodinger71 commented
ну можно

2024-09-28 17:21 UTC, Mirokko requested changes

2024-09-28 17:21 UTC, Mirokko commented on Content.Server/Ghost/GhostSystem.cs
> +                    if (TryComp<ShadekinNoAsphyxiationComponent>(playerEntity, out var _))
Название компонента должно быть не привязано к системе, лучше сделать его более нейтральным. Что-то типа "OnGhostAttemtpDamageComponent" или придумай что-то более удачное.

2024-09-28 17:21 UTC, Mirokko commented on Content.Server/Ghost/GhostSystem.cs
> +                        damage = new(_prototypeManager.Index<DamageTypePrototype>("Bloodloss"), dealtDamage);
`"Bloodloss"` - хардкод, должно быть в компоненте

2024-09-28 18:26 UTC, Mirokko commented on Content.Shared/ADT/OnGhostAttemtpDamage/OnGhostAttemtpDamageComponent.cs
> +    public string? DamageType = "Bloodloss";
Вроде не string?, а ProtorypeId<DamageTypePrototype>

2024-09-28 18:27 UTC, Schrodinger71 commented on Content.Shared/ADT/OnGhostAttemtpDamage/OnGhostAttemtpDamageComponent.cs
> +    public string? DamageType = "Bloodloss";
ну..... один фиг оно там преобразовывается

2024-09-28 18:31 UTC, Mirokko commented on Content.Shared/ADT/OnGhostAttemtpDamage/OnGhostAttemtpDamageComponent.cs
> +    public string? DamageType = "Bloodloss";
арбайтен. Надо чтобы хорошо выглядело. Вдруг кто будет в будущем делать, так проверится автоматом на опечатку и прочее.

2024-09-28 18:49 UTC, Schrodinger71 commented on Content.Shared/ADT/OnGhostAttemtpDamage/OnGhostAttemtpDamageComponent.cs
> +    public string? DamageType = "Bloodloss";
ладно ладно...сделаю

2024-09-28 19:17 UTC, Mirokko commented on Content.Shared/ADT/OnGhostAttemtpDamage/OnGhostAttemtpDamageComponent.cs
> +    public ProtoId<DamageGroupPrototype> BloodlossDamageGroup = "Bloodloss";
Вот старое название было лучше. Ты ж не знаешь наперёд что будет.

2024-09-28 19:18 UTC, Schrodinger71 commented on Content.Shared/ADT/OnGhostAttemtpDamage/OnGhostAttemtpDamageComponent.cs
> +    public ProtoId<DamageGroupPrototype> BloodlossDamageGroup = "Bloodloss";
т-т

2024-09-29 05:35 UTC, Mirokko approved these changes

2024-09-29 05:36 UTC, merged