Activate Brigmedic Loadout.
AdventureTimeSS14/space_station_ADT pull request #540
Opened 2024-09-26 16:11 UTC by BitBoxxxer

## Описание PR
Появление Loadout для Brigmedic с внушительным списком вещей ( под командованием руководства )

## Почему / Баланс

1. Не было в существовании самого loadout для игроков.
2. Это контрольное задание для вступления в команду разработчиков.

## Техническая информация

+ пометки для определения начала кода brigmedic
- Resources\Prototypes\ADT\Loadouts\Jobs\Security\brigmedic.yml
- Resources\Prototypes\ADT\Loadouts\loadout_groups.yml
- Resources\Prototypes\ADT\Loadouts\role_loadouts.yml

- [ X ] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [ X ] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

![Screenshot_28](https://github.com/user-attachments/assets/a4421149-0eed-4357-9fd4-e038c3ae0f71)
![Screenshot_29](https://github.com/user-attachments/assets/db1e8b0f-74e3-44ad-8021-ae60d4edacdb)

- add: добавлен список ***Инвентарь***
- add: добавлен список Головных уборов ***[Берет Бригмедика 3x, Шлем Бригмедика]***
- add: добавлен список Уборов на Шею ***[ Жетон СБ ]***
- add: добавлен список Комбинезонов ***[Комбинезон Бригмедика, Юбка-Комбинезон, brigmedic turtleneck 2x]***
- add: добавлен список Вверхней одежды ***[Ветровка Бригмедика, жилет Бригмедика, лабораторный халат]***
- add: добавлен список Сумок ***[Рюкзак бригмедика, Вещмешок бригмедика, brigmedic satchel]***
- add: добавлен список Поясов ***[пояс медика, РПС охраны, пояс охраны]***
- add: добавлен список Очков ***[ Медицинские солнцезащитные очки, очки охраны, солнцезащитные очки]***
- add: добавлен список Перчаток ***[Латексные, Нитриловые, Боевые]***
- add: добавлен список PDA ***[КПК Бригмедика]***
- add: добавлен список Обуви СБ ***[Подкованные сапоги 2x, зимние ботинки охраны]***
- add: добавлен список ***Безделушки.***

:cl:Kasey

2024-09-26 17:34 UTC, Bolper requested changes
Первое - насрано в чейнджлоги. Сделать этот add одним сообщением.
Второе.

2024-09-26 17:34 UTC, Bolper commented on Resources/Prototypes/ADT/Loadouts/loadout_groups.yml
> -  name: loadout-group-blueshield-jumpsuit
Ты зачем это трогал? Да еще и поменял не правильно. Поясняю что тебе надо сейчас сделать. нажать на cntrl shift f, а после найти в FTL файлике то что ты удаляешь и изменяешь. И тебе станет все понятно. Что существуют отдельные файлы для локализации

2024-09-26 17:35 UTC, Inconnu1337 commented
не очень нравится что написано Бриг**М**ед и PDA вместо КПК

2024-09-26 17:38 UTC, BitBoxxxer commented on Resources/Prototypes/ADT/Loadouts/loadout_groups.yml
> -  name: loadout-group-blueshield-jumpsuit
Ок, понятно

2024-09-27 10:27 UTC, BitBoxxxer commented
> Первое - насрано в чейнджлоги. Сделать этот add одним сообщением. Второе.

Ок, в следующий раз постараюсь оставлять историю чище.

2024-09-27 11:40 UTC, FaDeOkno submitted a review, later dismissed
Названия пунктов лоадаута сделай наподобие: "Бригмедик, 'слот'"
Ченджлог нечитаем, упрости до того, что бригмед получил свои ловдауты

2024-09-27 11:46 UTC, BitBoxxxer commented
> Названия пунктов лоадаута сделай наподобие: "Бригмедик, 'слот'" Ченджлог нечитаем, упрости до того, что бригмед получил свои ловдауты

Наподобии: " loadout-neck-brigmedic " ?

2024-09-27 12:08 UTC, Mirokko commented
Вероятно, он об №1.
Так же добавь переводы для №2:

![image](https://github.com/user-attachments/assets/1facaa11-10f9-461a-ae01-cac4a4afaa06)

2024-09-27 12:32 UTC, BitBoxxxer commented
> Вероятно, он об №1. Так же добавь переводы для №2:
> 
> ![image](https://private-user-images.githubusercontent.com/11059471/371525691-1facaa11-10f9-461a-ae01-cac4a4afaa06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MzkzMzIsIm5iZiI6MTcyNzQzOTAzMiwicGF0aCI6Ii8xMTA1OTQ3MS8zNzE1MjU2OTEtMWZhY2FhMTEtMTBmOS00NjFhLWFlMDEtY2FjNGE0YWZhYTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDEyMTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmNDZmNTEyYWE2Y2Y0NTI0ZWRjZTg4NmIwMmFlZWE2Mzk5ZDI4ODZiNzExMzJjZWNlNDkyMzE4OGQ5MDI4ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uFtD69m_p4mc5Qn_ULFYHx58saWbfMWlpWT1V4vphCU)

Кажется

2024-09-27 12:34 UTC, BitBoxxxer commented
> Вероятно, он об №1. Так же добавь переводы для №2:
> 
> ![image](https://private-user-images.githubusercontent.com/11059471/371525691-1facaa11-10f9-461a-ae01-cac4a4afaa06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MzkzMzIsIm5iZiI6MTcyNzQzOTAzMiwicGF0aCI6Ii8xMTA1OTQ3MS8zNzE1MjU2OTEtMWZhY2FhMTEtMTBmOS00NjFhLWFlMDEtY2FjNGE0YWZhYTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDEyMTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmNDZmNTEyYWE2Y2Y0NTI0ZWRjZTg4NmIwMmFlZWE2Mzk5ZDI4ODZiNzExMzJjZWNlNDkyMzE4OGQ5MDI4ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uFtD69m_p4mc5Qn_ULFYHx58saWbfMWlpWT1V4vphCU)

2-ое можно будет сделать на ином пуле
Над 1-ым сейчас займусь

2024-09-27 15:31 UTC, BitBoxxxer commented
> 2-ое можно будет сделать на ином пуле Над 1-ым сейчас займусь

Локализаторы готовы

2024-09-27 19:12 UTC, 1Stepka1 approved these changes

2024-09-27 22:28 UTC, Schrodinger71 commented
ЯМЛИИинтер

2024-09-29 03:04 UTC, BitBoxxxer commented
> Вероятно, он об №1. Так же добавь переводы для №2:
> 
> ![image](https://private-user-images.githubusercontent.com/11059471/371525691-1facaa11-10f9-461a-ae01-cac4a4afaa06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NzkwNzIsIm5iZiI6MTcyNzU3ODc3MiwicGF0aCI6Ii8xMTA1OTQ3MS8zNzE1MjU2OTEtMWZhY2FhMTEtMTBmOS00NjFhLWFlMDEtY2FjNGE0YWZhYTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDAyNTkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkODM5Y2JhNDU4Zjg4NTEzNTlmNjc3NDRlOGJhYmU3OTMzOTBhZjE0MWRkMDVkOWZhNDNjYjUyZWQ0NDQxZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cef7L1WPTAG_i7ab3QVmfzPF83LUU2dE66tbrWJjjqE)

Я посмотрела, То, что вы пометили как №2 надо дописывать на C#, это не работает даже на сервере ВП, пока, как и у оффов. (Хотя как нистранно локализаторы есть, но ссылки на локализаторы нету)
В коде оно прописывается просто как "Title = jobProto?.ID + "-loadout"," - без ссылки на локалы

2024-09-29 07:44 UTC, Bolper requested changes
![Screenshot_2024-09-29-10-37-03-478_com android chrome](https://github.com/user-attachments/assets/2b6798b8-e5b8-46ec-992a-a539e830a77c)
Пон? Не надо так срать. Кратко, коротко, ясно. Это для игроков херня. 
Так надо в описании пра писать.

2024-09-29 07:44 UTC, Bolper commented on Resources/Locale/ru-RU/ADT/Job/job-names.ftl
> +job-name-ADTBrigmedic = Бригмедик
![Screenshot_2024-09-29-10-41-26-386_com github android](https://github.com/user-attachments/assets/8ad38acd-73f0-4b56-8e91-208c9de16c80)
Пон?

2024-09-29 07:45 UTC, Bolper commented on Resources/Locale/ru-RU/ADT/Job/job-names.ftl
> +job-name-ADTBrigmedic = Бригмедик
![Uploading Screenshot_2024-09-29-10-45-07-988_com.github.android.png…]()

2024-09-29 07:45 UTC, Bolper commented on Resources/Locale/ru-RU/ADT/Job/job-names.ftl
> +job-name-ADTBrigmedic = Бригмедик
![Screenshot_2024-09-29-10-45-07-988_com github android](https://github.com/user-attachments/assets/d6dfe81b-965a-47c5-8a3b-4a4e06678fff)

2024-09-29 07:47 UTC, BitBoxxxer commented on Resources/Locale/ru-RU/ADT/Job/job-names.ftl
> +job-name-ADTBrigmedic = Бригмедик
Понятно, сейчас перепишууу

2024-09-29 11:22 UTC, Bolper approved these changes
Гуляй

2024-09-29 11:22 UTC, merged

2024-09-29 11:32 UTC, BitBoxxxer commented
Хобит будет спать ура ура ураа

2024-10-08 18:09 UTC, BitBoxxxer commented
Правки все сломали, придется переделывать.