Новый Состав Шкафчика Бригмедика
AdventureTimeSS14/space_station_ADT pull request #555
Opened 2024-09-29 07:31 UTC by BitBoxxxer

## Описание PR
Поменяла комплект вещей в заполненном шкафчике бригмедика (вещ-мешок)
+ Создание duffelbag [full]
+ Изменение снаряжения в шкафу
+ Локализаторы

## Почему
Заказ из ДС
(https://discord.com/channels/901772674865455115/1289579050305851422)

## Техническая информация
+ был создан ID RedBrigmedicDuffelbagClothing
+ создан локализатор нового вещ-мешка
+ изменен вещмешок бригмедика (черный - красный) на вещмешок бригмедика (красный-белый)

- [X] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [X] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

![Screenshot_5](https://github.com/user-attachments/assets/c55df71a-eb66-4f97-a2e7-7f6482139890)
![Screenshot_6](https://github.com/user-attachments/assets/83638bac-e76a-41fd-90ee-dd8b154fe54d)

:cl: Kasey [Adnoda] Bitboxxer

- tweak: Набор шкафчика Бригмедика
- add: Новый вещ-мешок Бригмедика

2024-09-29 12:51 UTC, Bolper requested changes
![image](https://github.com/user-attachments/assets/49565651-90a1-4e2c-85ae-e3f1e15d1225)
Маладца, но прибавь к этому слова: Добавлено, Изменено. Так просто надо. 

### Во вторых, нахуя, если есть лодауты?

2024-09-29 12:51 UTC, Bolper commented on Resources/Prototypes/ADT/Catalog/Fills/Backpacks/duffelbag.yml
> +  id: RedBrigmedicDuffelbagClothing
ID говна. ADTClothingBackpackDuffelBrigmedicFilled

2024-09-29 12:51 UTC, Bolper commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Clothing/Back/duffels.ftl
> +ent-RedBrigmedicDuffelbagClothing = вещмешок бригмедика
локализация говна. Используй { ent-ClothingBackpackDuffelBrigmedic } и { ent-ClothingBackpackDuffelBrigmedic.desc }

2024-09-29 12:51 UTC, Bolper commented on Resources/Prototypes/ADT/Catalog/Fills/Backpacks/duffelbag.yml
> +  id: RedBrigmedicDuffelbagClothing
И то бля, нахуя ему рюкзак с одеждой если есть лодауты. И Добавь тогда чтоб еще путаницы не было Clothing наверно на конце. Хуйней честно слово занимаетесь когда такое говно выдумываете. Есть лодауты.

2024-09-29 12:51 UTC, Bolper commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Clothing/Back/duffels.ftl
Местоположение говна. Resources\Locale\ru-RU\ADT\prototypes\Catalog\Fills\backpacks\starter_gear\duffelbag.ftl
Хуй с этим. Пусть будет в стартер гир.

2024-09-29 14:40 UTC, BitBoxxxer commented on Resources/Prototypes/ADT/Catalog/Fills/Backpacks/duffelbag.yml
> +  id: RedBrigmedicDuffelbagClothing
> И то бля, нахуя ему рюкзак с одеждой если есть лодауты. И Добавь тогда чтоб еще путаницы не было Clothing наверно на конце. Хуйней честно слово занимаетесь когда такое говно выдумываете. Есть лодауты.

Так там уже был в существовании вещ-мешок с вещами. С нуля делать было бы, да, глупо.

2024-09-29 14:45 UTC, Bolper commented
Второй вопрос до сих пор открыт

2024-09-29 14:51 UTC, Bolper commented
Подожди пока с выполнением этого ПРа @BitBoxxxer

2024-09-29 14:58 UTC, BitBoxxxer commented
> ![image](https://private-user-images.githubusercontent.com/169089627/371854005-49565651-90a1-4e2c-85ae-e3f1e15d1225.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MjIwMzAsIm5iZiI6MTcyNzYyMTczMCwicGF0aCI6Ii8xNjkwODk2MjcvMzcxODU0MDA1LTQ5NTY1NjUxLTkwYTEtNGUyYy04NWFlLWUzZjFlMTVkMTIyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQxNDU1MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTM0MDlhN2RlMjA1NDFhYjI2MTliZjhhOWZkN2U2NDYwZDU3NGUzYzg3ZTc5Yzc5MzEyZDViNzE5NTA1YTM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._t1GNCpTDCZ5sahbvgTv2dUOAXmal1Dx_3zS8CCopSs) Маладца, но прибавь к этому слова: Добавлено, Изменено. Так просто надо.
> 
> ### Во вторых, нахуя, если есть лодауты?

Эти наборы вещ-мешков уже существовали)
Мало ли на станции не будет бригмедика, а у замены не будет вещей бригмеда ?

2024-09-29 14:59 UTC, BitBoxxxer commented
> Подожди пока с выполнением этого ПРа @BitBoxxxer

Ммм, ок

2024-09-29 15:01 UTC, Bolper commented
> > ![image](https://private-user-images.githubusercontent.com/169089627/371854005-49565651-90a1-4e2c-85ae-e3f1e15d1225.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MjIwMzAsIm5iZiI6MTcyNzYyMTczMCwicGF0aCI6Ii8xNjkwODk2MjcvMzcxODU0MDA1LTQ5NTY1NjUxLTkwYTEtNGUyYy04NWFlLWUzZjFlMTVkMTIyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQxNDU1MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTM0MDlhN2RlMjA1NDFhYjI2MTliZjhhOWZkN2U2NDYwZDU3NGUzYzg3ZTc5Yzc5MzEyZDViNzE5NTA1YTM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._t1GNCpTDCZ5sahbvgTv2dUOAXmal1Dx_3zS8CCopSs) Маладца, но прибавь к этому слова: Добавлено, Изменено. Так просто надо.
> > ### Во вторых, нахуя, если есть лодауты?
> 
> Эти наборы вещ-мешков уже существовали) Мало ли на станции не будет бригмедика, а у замены не будет вещей бригмеда ?

рукалицо, Хм.  Хммммм. Тогда добавляй в одеждомат СБ. Или ты хочешь сказать что бригмед как глава должен иметь у себя в шкафу хуеву тучу одежды?

2024-09-29 15:15 UTC, BitBoxxxer commented
> > > ![image](https://private-user-images.githubusercontent.com/169089627/371854005-49565651-90a1-4e2c-85ae-e3f1e15d1225.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MjIwMzAsIm5iZiI6MTcyNzYyMTczMCwicGF0aCI6Ii8xNjkwODk2MjcvMzcxODU0MDA1LTQ5NTY1NjUxLTkwYTEtNGUyYy04NWFlLWUzZjFlMTVkMTIyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQxNDU1MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTM0MDlhN2RlMjA1NDFhYjI2MTliZjhhOWZkN2U2NDYwZDU3NGUzYzg3ZTc5Yzc5MzEyZDViNzE5NTA1YTM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._t1GNCpTDCZ5sahbvgTv2dUOAXmal1Dx_3zS8CCopSs) Маладца, но прибавь к этому слова: Добавлено, Изменено. Так просто надо.
> > > ### Во вторых, нахуя, если есть лодауты?
> > 
> > 
> > Эти наборы вещ-мешков уже существовали) Мало ли на станции не будет бригмедика, а у замены не будет вещей бригмеда ?
> 
> рукалицо, Хм. Хммммм. Тогда добавляй в одеждомат СБ. Или ты хочешь сказать что бригмед как глава должен иметь у себя в шкафу хуеву тучу одежды?

Ага, Тогда сделать проще доп вещи одеждомату СБ.

2024-09-30 14:03 UTC, BitBoxxxer commented
Идея изменилась на 180. Пул закрыт.

2024-09-30 14:03 UTC, closed without merging