Добавил кнопку "Панель" в АХ
AdventureTimeSS14/space_station_ADT pull request #561
Opened 2024-09-30 08:12 UTC by Mirokko

## Описание PR

Добавил кнопку в АХ, при нажатии на которую можно вызвать панель игрока

## Почему / Баланс

**Ссылка на публикацию в Discord**
- [Заказы-разработка](https://discord.com/channels/901772674865455115/1289524219868090419)

## Техническая информация

## Медиа

## Требования

- [x] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [x] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

## Критические изменения

**Чейнджлог**

:cl:
- add: Добавлена кнопка, открывающая панель игрока админам в АХ

2024-09-30 20:02 UTC, Schrodinger71 requested changes

2024-09-30 20:02 UTC, Schrodinger71 commented on Resources/Locale/ru-RU/administration/ui/actions.ftl
> +admin-player-actions-open-playerpanel = Панель
Всё таки в отдельный файл

2024-09-30 20:09 UTC, Bolper commented on Resources/Locale/ru-RU/administration/ui/actions.ftl
> +admin-player-actions-open-playerpanel = Панель
Хуяк. @Mirokko тогда и в прошлом пре поменяй.

2024-09-30 20:16 UTC, Schrodinger71 commented on Resources/Locale/ru-RU/administration/ui/actions.ftl
> +admin-player-actions-open-playerpanel = Панель
можно прям тут)

2024-10-01 11:08 UTC, Mirokko commented on Resources/Locale/ru-RU/administration/ui/actions.ftl
> +admin-player-actions-open-playerpanel = Панель
Фу.

2024-10-01 11:22 UTC, Mirokko commented on Resources/Locale/ru-RU/administration/ui/actions.ftl
> +admin-player-actions-open-playerpanel = Панель
Давайте без страдания фигней. В этом хер с ним, но это уже бред.

2024-10-01 11:37 UTC, Schrodinger71 commented on Resources/Locale/ru-RU/administration/ui/actions.ftl
> +admin-player-actions-open-playerpanel = Панель
:>

2024-10-01 11:39 UTC, Schrodinger71 commented on Resources/Locale/ru-RU/administration/ui/actions.ftl
> +admin-player-actions-open-playerpanel = Панель
Ладно..

2024-10-01 11:40 UTC, Schrodinger71 approved these changes

2024-10-01 11:55 UTC, merged