Клоуны антагонисты научились стрелять
AdventureTimeSS14/space_station_ADT pull request #573
Opened 2024-10-01 09:44 UTC by Inconnu1337

## Описание PR

Синдикат научил клоунов стрелять из оружия

## Требования

- [х] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [х] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

**Чейнджлог**

2024-10-01 09:47 UTC, Inconnu1337 commented
_залил для коти чтобы ему было понятнее_

2024-10-02 20:06 UTC, KashRas2 commented
Если клоун антаг - его раскроют, так как компонент отсутствует. В него помимо стрельбы также входят удары об стол. Рано или поздно, но это станет метой. Можно просто вынести систему запрета стрельбы в отдельный компонент или вырубить переменную, отвечающую за это, если она конечно имеется.

2024-10-05 19:11 UTC, Schrodinger71 requested changes

2024-10-05 19:11 UTC, Schrodinger71 commented on Content.Shared/Interaction/SharedInteractionSystem.Clumsy.cs
> -
Зачем удалил

2024-10-05 19:25 UTC, Bolper commented
Кто это маленький полез в код?

2024-10-06 00:04 UTC, Inconnu1337 commented
ХУЙНЯ ПЕРЕДЕЛЫВАЙ

2024-10-10 10:44 UTC, Mirokko commented on Content.Shared/Interaction/SharedInteractionSystem.Clumsy.cs
> -
ОН ТЕБЕ КАКОЕ ЗЛОЕ ЗЛО СДЕЛАЛ?!

2024-10-10 10:46 UTC, Mirokko commented on Content.Shared/ADT/CCVar/ADTCCVars.cs
> +        CVarDef.Create("boombox.volume", 1f, CVar.CLIENTONLY | CVar.REPLICATED);
Должно быть CVar.CLIENTONLY | CVar.ARCHIVE

2024-10-10 10:47 UTC, Mirokko commented on Resources/Prototypes/Entities/Objects/Devices/boombox.yml
> +  components:
А где тэг, раз ты его вводил? Ты тестировал, всё работает?

2024-10-10 10:52 UTC, Mirokko commented on Content.Server/ADT/Boombox/BoomBoxComponent.cs
> +    public Dictionary<string, ItemSlot> Slots = new();
Это уже есть в ItemSlots, зачем дублировать?

2024-10-10 11:38 UTC, Mirokko commented on Content.Server/Radio/Components/RadioMicrophoneComponent.cs
> +// [Access(typeof(RadioDeviceSystem))] ADT-Boombox-tweak
Не надо так делать, добавь систему просто свою

2024-10-10 11:39 UTC, Mirokko commented on Resources/Prototypes/tags.yml
> +  id: BoomBoxTape
у нас есть свой файл для тэгов, его используй лучше

2024-10-27 11:55 UTC, Inconnu1337 commented
закрываю ибо никто не собирается доделывать ййй

2025-03-29 11:44 UTC, Unlumy commented
@Schrodinger71 @KashRas2 Выбирайте закрываем или нет

2025-03-29 11:48 UTC, Schrodinger71 commented
Вообще бумбокс тема суперская

2025-03-29 11:49 UTC, Schrodinger71 commented
Учитывая что с этим прекрасно сочитается https://github.com/AdventureTimeSS14/space_station_ADT/pull/1240

2025-04-08 19:49 UTC, Unlumy commented
Blackout

2025-04-08 19:49 UTC, closed without merging