Добавление МузМат
AdventureTimeSS14/space_station_ADT pull request #575
Opened 2024-10-01 13:42 UTC by Mirokko

## Описание PR

Добавлен музмат (вендинговый аппарат), где можно купить музыкальные инструменты.
## Почему / Баланс

**Ссылка на публикацию в Discord**
- [Заказы-разработка](https://discord.com/channels/901772674865455115/1283535377616998552/1289582281064841269)

## Техническая информация

## Медиа

## Требования

- [ ] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [ ] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

## Критические изменения

**Чейнджлог**

2024-10-06 11:46 UTC, 1Stepka1 requested changes

2024-10-06 11:46 UTC, 1Stepka1 commented on Resources/Prototypes/Catalog/Cargo/cargo_fun.yml
> +# ADT-Tweak-End
Я думаю это лишнее, даже когда будут карты с расставленными на них автоматами, ни
К тому же не ясно что противоречит существованию автомата и отдельных заказов на определенные музыкальные инструменты их существованию ничего не мешает

2024-10-06 11:46 UTC, 1Stepka1 commented on Resources/Textures/ADT/Objects/Specific/Service/vending_machine_restock.rsi/meta.json
не правильное расположение
все файлы переместить в Resources/Textures/ADT/Structures/Machines/VendingMachines

2024-10-06 11:46 UTC, 1Stepka1 commented on Resources/Textures/ADT/Objects/Specific/Service/vending_machine_restock.rsi/meta.json
> +    "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/1516a728931b4985c1e86f0c5995a5aa1554a1ad",
Что это за источник,он никак не отсылает на то откуда это взято. Изменить на релевантный источник

2024-10-06 11:46 UTC, 1Stepka1 commented on Resources/Textures/Objects/Specific/Service/vending_machine_restock.rsi/meta.json
Это что за произвольное изменение файлов официалов? Я точно знаю что тут можно обойтись и без этого,и тем более у нас есть и свои автоматы,поэтому будет лучше сделать у нас это все

2024-10-06 11:46 UTC, 1Stepka1 commented
И ошибку цены пофиксить,соответственно,цену можно поставить 12000 к примеру

2024-10-07 09:20 UTC, Mirokko commented
Ладно, с этим вижу кучу проблем, поэтому может кто-то другой перенесёт контент.

2024-10-07 09:20 UTC, closed without merging