Перенос вещей ТСФ и AR-12
AdventureTimeSS14/space_station_ADT pull request #592
Opened 2024-10-03 08:29 UTC by Filokini

Перенесены со старой репы вещи ТСФ, Военные и торговцев. AR-12 Красотка. Добавил шанс на спавн шарфа анробаста в техах
:cl: Filo
- add: Ходят слухи что в тех-помещениях можно найти необычный шарф
- add: Вернул вещи ТСФ

2024-10-03 08:30 UTC, Filokini commented
блять кот проник сюда сука

2024-10-03 08:32 UTC, Filokini commented
просто уберу тот ПР и всё

2024-10-03 16:51 UTC, 1Stepka1 requested changes
А потом мы рядом править.Ты сначала редачишь файлы,а потом строки, символы, я тоже все их редачу. Я смотрю на твои изменения а ты на мои запросы изменений. С начала ты правишь, а потом аппрув

2024-10-03 16:51 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Entities/Mobs/NPCs/carpcat.yml
вот есть locale carp.ftl а это carpcat.yml
определитесь с названиями, тоже самое в текстурах если будут какие-то изменения

2024-10-03 16:51 UTC, 1Stepka1 commented on Resources/Textures/ADT/Clothing/Neck/armytoken.rsi/meta.json
Если yml находится в specific.yml то и текстуры тоже должны быть в папке предшествующий с этим названиеним
Neck/Specific/armytoken.rsi

2024-10-03 16:51 UTC, 1Stepka1 commented on Resources/Textures/ADT/Mobs/Aliens/carpcat.rsi/meta.json
> +  "copyright": "Taken from https://github.com/tgstation/tgstation/blob/master/icons/mob/animal.dmi, edited 'dead' to create 'crit' and 'dead' states",
edited 'dead' to create 'crit' and 'dead' states
Это что такое? Кажись это лишние и не отсылает к тому что есть в действительности,состояние crit здесь нету значит и комментарий не состоятельный

2024-10-03 16:51 UTC, 1Stepka1 commented on Resources/Textures/ADT/Objects/Consumable/Drinks/armyflask.rsi/meta.json
> +{"version": 1, "size": {"x": 32, "y": 32}, "license": "CC-BY-SA-3.0", "copyright": "https://github.com/discordia-space/CEV-Eris/raw/f7aa28fd4b4d0386c3393d829681ebca526f1d2d/icons/obj/drinks.dmi", "st
Эта што такое? Давай преобразовывай в человека-читаемый формат

2024-10-03 16:51 UTC, 1Stepka1 commented on Resources/Textures/ADT/Objects/Devices/trader_pda.rsi/meta.json
Вот ты и попался нефор,переместить все связанные файлы в Resources/Textures/ADT/Objects/Devices/pda.rsi
пути в прототипах поменять соответственно

2024-10-03 16:51 UTC, 1Stepka1 commented on Resources/Textures/ADT/Objects/Misc/trader_id.rsi/meta.json
попался за руку как дешевка
перемесить в Resources/Textures/ADT/Objects/Misc/id_cards.rsi и все связные файла и изменить пути в прототипах

2024-10-03 16:51 UTC, 1Stepka1 commented on Resources/Textures/ADT/Structures/Decoration/tsf_banner.rsi/meta.json
переместить в Resources/Textures/ADT/Structures/Decoration/banners  и все связные файла и изменить пути в прототипах

2024-10-03 16:51 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Entities/Clothing/Neck/specific.yml
> +      sprite: ADT/Clothing/Neck/tsf_patch.rsi
а ещё мне интересно а что это,чем оно является,типо значок или нашивка?

2024-10-03 16:55 UTC, Filokini commented on Resources/Textures/ADT/Objects/Consumable/Drinks/armyflask.rsi/meta.json
> +{"version": 1, "size": {"x": 32, "y": 32}, "license": "CC-BY-SA-3.0", "copyright": "https://github.com/discordia-space/CEV-Eris/raw/f7aa28fd4b4d0386c3393d829681ebca526f1d2d/icons/obj/drinks.dmi", "st
честно не мое

2024-10-03 16:56 UTC, Filokini commented on Resources/Textures/ADT/Objects/Consumable/Drinks/armyflask.rsi/meta.json
> +{"version": 1, "size": {"x": 32, "y": 32}, "license": "CC-BY-SA-3.0", "copyright": "https://github.com/discordia-space/CEV-Eris/raw/f7aa28fd4b4d0386c3393d829681ebca526f1d2d/icons/obj/drinks.dmi", "st
мне подложили

2024-10-03 16:56 UTC, Filokini commented on Resources/Prototypes/ADT/Entities/Clothing/Neck/specific.yml
> +      sprite: ADT/Clothing/Neck/tsf_patch.rsi
нашивка

2024-10-03 16:56 UTC, Filokini commented on Resources/Prototypes/ADT/Entities/Clothing/Neck/specific.yml
> +      sprite: ADT/Clothing/Neck/tsf_patch.rsi
точнее типо наклейка как я понял

2024-10-03 17:00 UTC, 1Stepka1 commented on Resources/Textures/ADT/Objects/Consumable/Drinks/armyflask.rsi/meta.json
> +{"version": 1, "size": {"x": 32, "y": 32}, "license": "CC-BY-SA-3.0", "copyright": "https://github.com/discordia-space/CEV-Eris/raw/f7aa28fd4b4d0386c3393d829681ebca526f1d2d/icons/obj/drinks.dmi", "st
но это делает у тебя в пр,так что меняй

2024-10-03 17:20 UTC, Filokini commented on Resources/Textures/ADT/Clothing/Neck/armytoken.rsi/meta.json
так всё итак гуд же

2024-10-03 18:06 UTC, 1Stepka1 commented on Resources/Textures/ADT/Clothing/Neck/armytoken.rsi/meta.json
![изображение](https://github.com/user-attachments/assets/fdf00f3b-6b11-4a2b-9589-7d3a3526e598)
![изображение](https://github.com/user-attachments/assets/990fe39f-8105-469c-8bdf-751a0fa6bd34)
Сравни изображение

2024-10-03 23:53 UTC, Filokini commented
@1Stepka1 Готово вроде

2024-10-04 13:09 UTC, 1Stepka1 approved these changes

2024-10-04 13:09 UTC, merged