Добавил возможность вешать значки на броню
AdventureTimeSS14/space_station_ADT pull request #608
Opened 2024-10-05 13:34 UTC by Mirokko

## Описание PR

Название

## Почему / Баланс

**Ссылка на публикацию в Discord**
- [Баги](https://discord.com/channels/901772674865455115/1284125054375825439)

## Техническая информация

## Медиа

![изображение](https://github.com/user-attachments/assets/7e688ad2-3527-4af3-93f7-56d9c9ebc01f)
![изображение](https://github.com/user-attachments/assets/33454da1-06b9-47ea-b9ee-c023f8daaf1f)
![изображение](https://github.com/user-attachments/assets/2a707438-945b-4b3d-9f57-01eeab520810)
![изображение](https://github.com/user-attachments/assets/affd712b-b2d0-4654-8c98-d8e99910d828)
![изображение](https://github.com/user-attachments/assets/e26a5bf1-3d73-46e9-b32d-8d6b6d4825af)
![изображение](https://github.com/user-attachments/assets/109fd75f-4161-4aa2-ab47-888a7fd76b9b)

## Требования

- [ ] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [ ] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

## Критические изменения

**Чейнджлог**

:cl:
- add: Добавлена возможность закреплять значок на броне СБ

2024-10-05 13:42 UTC, Mirokko commented on Resources/ConfigPresets/Build/debug.toml
> +api_url = ""
Вот этого вообще не должно быть, эта штука только для тех, кто понимает зачем это вообще.

2024-10-06 06:09 UTC, Mirokko commented
В общем, мне нужна помощь. Если подскажете, почему тесты упали, будет хорошо (и желательно хоть приблизительно как исправить).

2024-10-06 09:03 UTC, Ratyyy commented on Resources/ConfigPresets/Build/debug.toml
> +api_url = ""
это надо оставить, через это работает спонсорка. Если удалять стоит только на локалке

2024-10-06 10:16 UTC, Mirokko commented on Resources/ConfigPresets/Build/debug.toml
> +api_url = ""
это в конфиге "дебаг". Врядли используется он на проде. А если используется - то это надо поправить.

2024-10-06 10:17 UTC, Ratyyy commented on Resources/ConfigPresets/Build/debug.toml
> +api_url = ""
ну, тогда, думаю, можно удалить. Хотя тут лучше у кэша спросить, он чинил спонсорку

2024-10-07 06:28 UTC, Mirokko commented
Вроде тебя имели ввиду, нужно твоё мнение. Ща конфликт поправлю.

2024-10-07 09:23 UTC, Mirokko commented on Resources/ConfigPresets/Build/debug.toml
> +api_url = ""
Вернул этот файл

2024-10-09 09:38 UTC, Mirokko commented
@FaDeOkno  возможно ты сможешь обьяснить что именно тесты хотят от меня, я не понимаю. Есть только примерное понимание проблемы

2024-10-13 15:38 UTC, Darkiich commented
@Mirokko На такие тесты с нулевой локалью забивай болт, почему? Потому что это база у нас и так сказал Котя

2024-10-28 14:37 UTC, PyotrIgn requested changes
Добавь в комментарии к пэренту вне АДТшных папок - что это наше улучшение

2024-10-30 18:19 UTC, PyotrIgn approved these changes

2024-10-30 18:19 UTC, merged