Мехи снова с нами!
AdventureTimeSS14/space_station_ADT pull request #609
Opened 2024-10-05 15:29 UTC by FaDeOkno

## Описание PR

Перенёс и исправил часть щиткода мехов со старой сборки

## Почему / Баланс

Ну а чёб и нет

**Ссылка на публикацию в Discord**

## Техническая информация

Добавлена проверка на оружие меха в GunSystem и SharedGunSystem
Добавлены новые ивенты в MechSystem, отвечающие за ЭМИ, модификаторы урона, уничтожение оборудования меха и два новых акшон ивента туда же
Добавлен ивент MechSetupEvent, он вызывается на меха для работы с пилотом в момент выдачи базовых акшонов (см. добавление действий фазона и гайгэкса)

## Медиа

Только видео с фазоном есть: https://youtu.be/T5vs1YsggtY

## Требования

- [ ] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [ ] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

## Критические изменения

Критического нет, всё либо мелкое и самобытное, либо в отдельных файлах 

**Чейнджлог**

:cl:
- add: Перенесены мехи со старой сборки. еееееееееееее
- tweak: Спрайт фазона теперь меняется во время фазирования

2024-11-04 12:09 UTC, Schrodinger71 submitted a review, later dismissed
Только начал с клиента

2024-11-04 12:09 UTC, Schrodinger71 commented on Content.Client/Mech/MechSystem.cs
>      }
Ничего не прокоментированно

2024-11-04 12:15 UTC, FaDeOkno commented on Content.Client/ADT/Mech/Systems/MedMechSystem.cs
> +        if (!_entityManager.HasComponent<ShowHealthBarsComponent>(playerEntity))
А, капец
Я мед. меха не починил вообще

2024-11-06 14:54 UTC, Schrodinger71 requested changes
Правим

2024-11-06 14:54 UTC, Schrodinger71 commented on Content.Server/ADT/Mech/Components/CanEscapeMechComponent.cs
> +{
конечно прикольно было xml кодом каждый компонент объяснить в этой обнове и каждую переменную что содержит 
хотя бы в кратце

2024-11-06 14:54 UTC, Schrodinger71 commented on Content.Server/ADT/Mech/Systems/MechCatapultSystem.cs
> +        args.Handled = true;
стоит ли прям в коде напрямую путь..
можно в компоненте по умолчанию поле задать

2024-11-06 14:54 UTC, Schrodinger71 commented on Content.Server/ADT/Mech/Systems/MechDrillSystem.cs
> +
47 строка, лишний ENDTER
Хехе можно убрать :з

2024-11-06 14:54 UTC, Schrodinger71 commented on Content.Server/ADT/Mech/Systems/MechSystem.cs
> +        Spawn("EffectSparks", Transform(uid).Coordinates);
тоже напрямую вписан "EffectSparks", предлагаю на ваше усмотрение создать отдельное поле эффекта в MechComponent

2024-11-06 14:54 UTC, Schrodinger71 commented on Content.Server/ADT/Mech/Systems/MechSystem.cs
> +        Spawn("EffectEmpPulse", Transform(uid).Coordinates);
И тут тоже самое

2024-11-06 14:54 UTC, Schrodinger71 commented on Content.Server/ADT/Mech/Systems/MechSystem.cs
> +            return;
Вроде ошибки так и вписываються, ладно

2024-11-06 14:54 UTC, Schrodinger71 commented on Content.Server/Mech/Equipment/EntitySystems/MechGrabberSystem.cs
> +using Content.Server.Body.Systems;
// ADT Tweak: mech

2024-11-06 14:54 UTC, Schrodinger71 commented on Content.Server/Mech/Equipment/EntitySystems/MechGrabberSystem.cs
>      }
// ADT Tweak: Mech!!

2024-11-06 14:54 UTC, Schrodinger71 commented on Content.Server/Mech/Equipment/EntitySystems/MechGrabberSystem.cs
>          var offset = mechPos + mechRot.RotateVec(component.DepositOffset);
не подписано, давайте вокруг комментами

2024-11-06 14:54 UTC, Schrodinger71 commented on Content.Server/Mech/Equipment/EntitySystems/MechGrabberSystem.cs
тут чёрти что, давайте тоже комментируем всё

2024-11-06 14:54 UTC, Schrodinger71 commented on Content.Server/Mech/Equipment/EntitySystems/MechGrabberSystem.cs
>          _mech.UpdateUserInterface(equipmentComponent.EquipmentOwner.Value);
И тут комментарии

2024-11-06 14:54 UTC, Schrodinger71 commented on Content.Server/Mech/Equipment/EntitySystems/MechGrabberSystem.cs
>  }
Давайте тут по нормальней коммент, а ни так сяк

2024-11-06 14:54 UTC, Schrodinger71 commented on Content.Server/Mech/Systems/MechSystem.cs
можно в блок комментов выделить

2024-11-06 14:54 UTC, Schrodinger71 commented on Content.Server/Mech/Systems/MechEquipmentSystem.cs
>  using Content.Shared.Mech.Components;
красиво вынести бы это в 
// adt start
// adt end

2024-11-06 14:54 UTC, Schrodinger71 commented on Content.Server/Mech/Systems/MechSystem.cs
ну и тут, хрен ли
не обязательно правда

2024-11-06 14:54 UTC, Schrodinger71 commented on Content.Server/Mech/Systems/MechSystem.cs
> +        UpdateUserInterface(uid);
Подписать

2024-11-06 14:54 UTC, Schrodinger71 commented on Content.Server/Mech/Systems/MechSystem.cs
> +
Неподписано!!! АУУУ

2024-11-06 14:54 UTC, Schrodinger71 commented on Content.Server/Mech/Systems/MechSystem.cs
>          _ui.SetUiState(uid, MechUiKey.Key, state);
Подписываем

2024-11-06 14:54 UTC, Schrodinger71 commented on Content.Server/Weapons/Ranged/Systems/GunSystem.cs
Подписать

2024-11-06 14:54 UTC, Schrodinger71 commented on Content.Server/Weapons/Ranged/Systems/GunSystem.cs
>                      }
Ну чёт так сяк

2024-11-06 14:54 UTC, Schrodinger71 commented on Content.Server/Weapons/Ranged/Systems/GunSystem.cs
>                      break;
ПОДПИСЫВАЕМ

2024-11-06 15:05 UTC, Schrodinger71 requested changes
ЕЩЁ ОДНА ПАЧКА В ЛИЦО.
Тут Шейрад

2024-11-06 15:05 UTC, Schrodinger71 commented on Content.Shared/Mech/Components/MechComponent.cs
> +    [DataField("maxintegrity"), AutoNetworkedField, ViewVariables(VVAccess.ReadWrite)]
Не подписано!!

2024-11-06 15:05 UTC, Schrodinger71 commented on Content.Shared/Mech/Components/MechComponent.cs
Можно в блок

2024-11-06 15:05 UTC, Schrodinger71 commented on Content.Shared/Mech/Components/MechComponent.cs
> -
зачем удалённая строка

2024-11-06 15:05 UTC, Schrodinger71 commented on Content.Shared/Mech/Components/MechComponent.cs
> -
И тут ни надо удалять

2024-11-06 15:05 UTC, Schrodinger71 commented on Content.Shared/Mech/Components/MechComponent.cs
> +    [DataField("equipmentWhitelist")]
Подписать

2024-11-06 15:05 UTC, Schrodinger71 commented on Content.Shared/Mech/Components/MechComponent.cs
> -
Не удалять строку

2024-11-06 15:05 UTC, Schrodinger71 commented on Content.Shared/Mech/EntitySystems/SharedMechSystem.cs
> +using System.Linq;
в блок можно выделить

2024-11-06 15:05 UTC, Schrodinger71 commented on Content.Shared/Mech/EntitySystems/SharedMechSystem.cs
>  {
Не подписано

2024-11-06 15:05 UTC, Schrodinger71 commented on Content.Shared/Mech/EntitySystems/SharedMechSystem.cs
> +        // SubscribeLocalEvent<MechComponent, MechToggleEquipmentEvent>(OnToggleEquipmentAction);
не подписали, что наш коммент

2024-11-06 15:05 UTC, Schrodinger71 commented on Content.Shared/Mech/EntitySystems/SharedMechSystem.cs
>      }
Тож не подписано

2024-11-06 15:05 UTC, Schrodinger71 commented on Content.Shared/Mech/EntitySystems/SharedMechSystem.cs
> +
Подпишите

2024-11-06 15:05 UTC, Schrodinger71 commented on Content.Shared/Mech/EntitySystems/SharedMechSystem.cs
> -
не теребите строки

2024-11-06 15:05 UTC, Schrodinger71 commented on Content.Shared/Mech/EntitySystems/SharedMechSystem.cs
>  }
НЕ ПОДПИСАНО

2024-11-06 15:05 UTC, Schrodinger71 commented on Content.Shared/Mech/MechUI.cs
>  }
Многое не подписано

2024-11-06 15:10 UTC, FaDeOkno commented on Content.Server/Weapons/Ranged/Systems/GunSystem.cs
Юзинги не комментируем

2024-11-06 15:11 UTC, FaDeOkno commented on Content.Server/Mech/Equipment/EntitySystems/MechGrabberSystem.cs
> +using Content.Server.Body.Systems;
ЮЗИНГТ БЛЯТЬ 
мы не подписываем

2024-11-06 15:11 UTC, FaDeOkno commented on Content.Server/Mech/Equipment/EntitySystems/MechGrabberSystem.cs
>      }
а не очевидно? коммент есть

2024-11-06 15:12 UTC, FaDeOkno commented on Content.Server/Mech/Systems/MechSystem.cs
ЮЗИНГИИИИИИИИИИИИИИИИИИИИИИИИИИИ

2024-11-06 15:13 UTC, Schrodinger71 requested changes
В ПРОТОТИПАХ НАСРАЛИ

2024-11-06 15:13 UTC, Schrodinger71 commented on Resources/Audio/ADT/Mecha/attributions.yml
> +  source: "https://github.com/tgstation/tgstation/commit/45123dd06cb6dc7c56e8004c528230682ea559b2"
малова то атрибутов правда

2024-11-06 15:13 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
Ну ни очень подписали

2024-11-06 15:13 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Mobs/base.yml
> +  - type: CanEscapeMech
НЕ ПОДПИСАНО

2024-11-06 15:13 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Objects/Specific/Mech/mecha_equipment.yml
НЕ ПОДПИСАНО

2024-11-06 15:13 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Objects/Specific/Mech/mechs.yml
>    - type: MeleeWeapon
НУ СОЙДЁТ

2024-11-06 15:13 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Objects/Specific/Mech/mechs.yml
>    - type: Damageable
СОЙДЁТ

2024-11-06 15:13 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Objects/Specific/Mech/mechs.yml
>      baseState: ripley
Имба

2024-11-06 15:13 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Objects/Specific/Mech/mechs.yml
НУ ПОЙДЁТ

2024-11-06 15:13 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Objects/Specific/Mech/mechs.yml
ИМБА

2024-11-06 15:13 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Boxes/mech.yml
> +      ballistic-ammo: !type:Container
ПОЧЕМУ НОВЫЙ ФАЙЛ НЕ В ADT

2024-11-06 15:13 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Structures/Specific/Anomaly/cores.yml
НУ такое себе

2024-11-06 15:13 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Structures/Specific/Anomaly/cores.yml
Давайте получше

2024-11-06 15:13 UTC, Schrodinger71 commented on Resources/Textures/Objects/Weapons/Guns/Projectiles/projectiles2.rsi/meta.json
> -    {
нафиг тут удалили пробел?

2024-11-06 15:13 UTC, Schrodinger71 commented on Resources/Textures/Objects/Weapons/Guns/Projectiles/projectiles2.rsi/meta.json
>        "name": "grapeshot"
и тут

2024-11-06 15:13 UTC, Schrodinger71 commented on Resources/Textures/Objects/Weapons/Guns/Projectiles/projectiles2.rsi/meta.json
> +    {
Ни трогайте пробелы)

2024-11-06 15:13 UTC, Schrodinger71 commented on Resources/Textures/Objects/Weapons/Guns/SMGs/dnasyringegun.rsi/meta.json
> +    "license": "CC-BY-SA-3.0",
ПОЧЕМУ НОВЫЙ ФАЙЛ НЕ В ADT

2024-11-06 17:00 UTC, FaDeOkno commented on Resources/Textures/Objects/Weapons/Guns/Projectiles/projectiles2.rsi/meta.json
> +    {
Сам попробуй сохранить пробел в VSC

2024-11-06 17:10 UTC, FaDeOkno commented on Content.Server/ADT/Mech/Systems/MechCatapultSystem.cs
> +        args.Handled = true;
Эту систему всё равно я потом реворкать буду
или не я

Короче, оно не используется щас нигде

2024-11-06 17:21 UTC, FaDeOkno commented on Resources/Textures/Objects/Weapons/Guns/Projectiles/projectiles2.rsi/meta.json
> +    {
Дудка, это _физически_ невозможно

2024-11-06 17:52 UTC, Schrodinger71 commented on Content.Server/ADT/Mech/Systems/MechCatapultSystem.cs
> +        args.Handled = true;
хм..

2024-11-15 12:17 UTC, KashRas2 approved these changes
Гойда

2024-11-15 12:30 UTC, merged