ы
AdventureTimeSS14/space_station_ADT pull request #610
Opened 2024-10-05 17:44 UTC by FaDeOkno

## Описание PR

Ченджлог

## Почему / Баланс

Багфикс

**Ссылка на публикацию в Discord**

## Техническая информация

## Медиа

## Требования

- [ ] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [ ] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

## Критические изменения

**Чейнджлог**

:cl: Котя
- fix: Теперь при наведении на лежачего персонажа, даже если он под столом и предметами, пули будут попадать.

2024-10-05 22:01 UTC, Schrodinger71 commented
ссылку бы на то обсуждение в дисе

2024-10-06 05:47 UTC, Mirokko commented
А для станбатонов еще бы, если уже не сделано.

2024-10-10 12:53 UTC, Mirokko commented
Я затестил, работает норм. Но опять же, еще надо для удара пофиксить и будет огонь. Хотябы для того, который через ЛКМ.

2024-10-10 13:07 UTC, Mirokko requested changes
Я затестил (локально), работает норм. Но опять же, еще надо для удара пофиксить и будет огонь. Хотябы для того, который через ЛКМ.

Это нужно в большинстве своём для станбатона.

2024-10-14 19:44 UTC, Ratyyy submitted a review, later dismissed
только тесты починить надо
и реквест мирокко
сама же бед не нашла

2024-10-20 19:16 UTC, Schrodinger71 submitted a review, later dismissed

2024-10-20 19:16 UTC, Schrodinger71 commented on Content.Server/Weapons/Ranged/Systems/GunSystem.cs
> +            targeted.TargetCoords = gun.ShootCoordinates;
ГДЕ комментрарияй нахуй

2024-10-20 19:32 UTC, Mirokko approved these changes
LGTM

2024-10-20 19:47 UTC, merged