Возвращение старых вещей в аплинк, и небольшое изменение аплинка обр
AdventureTimeSS14/space_station_ADT pull request #611
Opened 2024-10-05 18:53 UTC by Filokini

:cl:
- add: Добавлено веселье!
- remove: Удалено веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!
-->

2024-10-05 23:51 UTC, Filokini commented
Верю в силу степки

2024-10-06 00:02 UTC, Inconnu1337 commented
чейнджлог поправь и пиши хотя бы что конкретно добавил

2024-10-06 00:22 UTC, Filokini commented
ты кто такой

2024-10-06 12:55 UTC, 1Stepka1 requested changes

2024-10-06 12:55 UTC, 1Stepka1 commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Weapons/Bombs/bombs.ftl
Неверное распроложение, переместить в ADT/prototypes/entities/objects/weapons/bombs/funny.ftl
Тоже самое проделать со своими другими относящиемся к этому файлам вещам

2024-10-06 12:55 UTC, 1Stepka1 commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Weapons/Guns/Ammunition/Magazines/rifles.ftl
неверное название файла,имя файла должно быть в единственном числе

2024-10-06 12:55 UTC, 1Stepka1 commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Weapons/Guns/Ammunition/Magazines/shotguns.ftl
неверное название файла,имя файла должно быть в единственном числе

2024-10-06 12:55 UTC, 1Stepka1 commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Weapons/Guns/Ammunition/Magazines/snipers.ftl
неверное название файла,имя файла должно быть в единственном числе

2024-10-06 12:55 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Catalog/Fills/Items/syndicate.yml
> +      - id: ClothingMaskGasSyndicate
Если это toolbox то его надо переместить Resources\Prototypes\ADT\Catalog\Fills\Items\toolboxes.yml

2024-10-06 12:55 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Catalog/Fills/Items/syndicate.yml
> +      - id: DnaScramblerImplanter
Неверное расположение, это должно находится Resources\Prototypes\ADT\Catalog\Fills\Items\syndicate.yml

2024-10-06 12:55 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Bombs/pizzabox.yml
Неверный путь, переместить в ADT/Entities/Objects/Weapons/Bombs/pizzabox.yml или можно можно переименовать в funny.yml

2024-10-06 12:55 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Entities/Objects/Weapons/Shotguns/caneshotgun.yml
По аналогии файлы связанные с этим называются или идентифицируются как shotguns,но тут другое название,так что определитесь с тем как называть, так же изменить все файлы связанные с этим если изменение имени их затрагивает

2024-10-06 12:55 UTC, 1Stepka1 commented on Resources/Textures/ADT/Objects/Specific/Medical/defibsyndi.rsi/meta.json
> +  "copyright": "Created by EmoGarbage404 (github) for Space Staiton 14",
Ты точно уверен что хочешь поставить лицензию позволяющая кому угодно и без упоминания брать эти материалы(CC0-1.0)?
К тому же не верный источник,надо поменять

2024-10-06 12:55 UTC, 1Stepka1 commented on Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/xc67.rsi/meta.json
Неправильное название пути,правильно Rifles а не Rifels

2024-10-06 13:20 UTC, Filokini commented on Resources/Prototypes/ADT/Catalog/Fills/Items/syndicate.yml
> +      - id: DnaScramblerImplanter
Так он же тут и находится

2024-10-06 13:25 UTC, Filokini commented on Resources/Prototypes/ADT/Catalog/Fills/Items/syndicate.yml
> +      - id: DnaScramblerImplanter
так он тута и лежит

2024-10-06 13:31 UTC, 1Stepka1 commented on Resources/Prototypes/ADT/Catalog/Fills/Items/syndicate.yml
> +      - id: DnaScramblerImplanter
Пипец я нефор, сейчас изменю комментарий

2024-10-06 14:13 UTC, Filokini commented
@1Stepka1 
Готово вроде

2024-10-06 16:09 UTC, 1Stepka1 approved these changes

2024-10-06 16:44 UTC, merged