ДНК Замок для скафандров
AdventureTimeSS14/space_station_ADT pull request #626
Opened 2024-10-09 08:02 UTC by Inconnu1337

## Описание PR

Добавлен компонент DNALocker позволяющий наделить любой скафандр ДНК Замком
Скафандры ОБР и ЯО имеют встроенный ДНК Замок
Фултоны можно цеплять на гуманоидов. **УРА!**
## Почему / Баланс

Перенос со старой сборки и небольшое улучшение от меня 

**Ссылка на публикацию в Discord**
- [Предложения](https://discord.com/channels/901772674865455115/1293258570997174322/1293258570997174322)
- [Перенос контента](https://github.com/AdventureTimeSS14/space_station/pull/561)

## Техническая информация

Добавлен компонент DNALockComponent и DNALockerSystem для биозамка скафандров

## Требования

- [х] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [х] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

**Чейнджлог**

:cl: Inconnu (Тянка Шрёди:3)
- add: Добавлен ДНК замок для скафандров ОБР и ЯО
- tweak: Фултоны вновь цепляются на гуманоидов

2024-10-09 09:42 UTC, Mirokko commented
Для ожидания тестирования надо чтоб шрёдя залил на дев

2024-10-09 09:53 UTC, Mirokko commented on Content.Shared/Salvage/Fulton/FultonComponent.cs
> +            "Anchorable",
У меня подозрение что это не часть этого ПРа, но если да - комменты

2024-10-09 09:53 UTC, Mirokko commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +  - type: DNALocker
Тут и ниже в этом файле - комменты `#ADT-Tweak`

2024-10-09 09:53 UTC, Mirokko commented on Content.Server/ADT/DNALocker/DNALockComponent.cs
> +        }
Выше этой строчки лучше сделать просто ретурн и удалить иф который ниже. Так же, возможно, ктото будет использовать эту систему для своих целей, поэтому хорошо бы выделить публичные методы сразу, которые залокают компонент. Да и, возможно, будет в будущем прикольно сделать чтобы система поддерживала не только хардсьюиты, но и пистолеты (когда берёшь в руку). Тогда это будет проще сделать.

2024-10-09 09:53 UTC, Mirokko commented on Content.Server/ADT/DNALocker/DNALockComponent.cs
> +        }
Это тоже можно в функцию выделить публичную

2024-10-09 09:53 UTC, Mirokko commented on Content.Server/ADT/DNALocker/DNALockComponent.cs
> +    private void OnGotEmagged(EntityUid uid, DNALockerComponent component, ref GotEmaggedEvent args)
А что будет если ты емагнешь во время того, как сработал уже твой локер? По идее, должно успешно обезвредить.

2024-10-09 09:56 UTC, Mirokko commented
А вроде бы у КПБ нет ДНК (и не должно быть). Затести локально как это работает вообще с ними

2024-10-09 10:16 UTC, Inconnu1337 commented on Content.Server/ADT/DNALocker/DNALockComponent.cs
> +    private void OnGotEmagged(EntityUid uid, DNALockerComponent component, ref GotEmaggedEvent args)
Не.. Будет и должен быть взрыв потому что замок уже отправил сигнал о несовпадении цепочки ДНК и система самоуничтожения запущена

2024-10-09 11:03 UTC, Mirokko commented on Content.Server/ADT/DNALocker/DNALockerSystem.cs
> +using Robust.Shared.Audio;
ТАк бляха, файл назван как система, а у тебя внутри компонент!

2024-10-09 11:03 UTC, Mirokko commented on Content.Server/ADT/DNALocker/DNALockComponent.cs
> +using Content.Server.Forensics;
ТАк бляха, файл назван как компонент, а у тебя внутри система!

2024-10-10 06:52 UTC, Inconnu1337 commented on Content.Server/ADT/DNALocker/DNALockComponent.cs
> +        }
не особо много желания есть чтобы переделывать все потому.. наверно не буду делать то что ты сказал

2024-10-10 14:20 UTC, Mirokko commented
А зачем от меня ревью? Я уже всё отписал, ты отказался делать.

2024-10-10 14:21 UTC, Mirokko requested changes
Ну я написал в прошлом ревью что нужно сделать, если нет - пусть кто-то другой аппрув даёт.

2024-10-12 17:41 UTC, Mirokko commented on Content.Server/ADT/DNALocker/DNALockerSystem.cs
> +        else
Вот не будущее - тут елс не нужен. Просто ретурн сделай и всё. Старайся чтобы код был максимально без вложенностей.

2024-10-12 17:42 UTC, Mirokko commented on Content.Server/ADT/DNALocker/DNALockerSystem.cs
> +        if (component.Locked)
If (!component.Locked)
    return;
    
И всё..

2024-10-12 17:43 UTC, Mirokko commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +  - type: DNALocker # ADT-Tweak
Ты уверен в том, что это надо удалять?

2024-10-12 17:44 UTC, Mirokko commented on Resources/Locale/ru-RU/ADT/syndicate.ftl
> +dna-locker-explode = Ваш ДНК не совпал с требуемым!
нелогично назван ключ строки (dna-locker-explode)

2024-10-12 17:46 UTC, Mirokko commented on Content.Server/ADT/DNALocker/DNALockerSystem.cs
> +    private void OnGotEmagged(EntityUid uid, DNALockerComponent component, ref GotEmaggedEvent args)
По идее, в этом методе ты должен что-то сделать с args. Как минимум, `args.Handled = true;`. Почитай коммент EmagSystem (или как там система называется, по памяти пишу)

2024-10-12 17:47 UTC, Mirokko requested changes
надо было сделать ревью, а я делал комменты, так как подумал что всё норм. Так же нужно пересмотреть где должны находиться твои компонент и система (я о пути). Но это к более опытным коллегам

2024-10-12 18:32 UTC, Inconnu1337 commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +  - type: DNALocker # ADT-Tweak
случайно вышло видимо

2024-10-12 19:41 UTC, Inconnu1337 commented on Content.Server/ADT/DNALocker/DNALockerSystem.cs
> +    private void OnGotEmagged(EntityUid uid, DNALockerComponent component, ref GotEmaggedEvent args)
**args.Repeatable = true;
args.Handled = true;**
по приколу будто там

2024-10-14 14:20 UTC, Inconnu1337 commented
пон

2024-10-16 18:40 UTC, Darkiich requested changes
Так, по путям вроде все ок, но есть одно большое НО. ДНК замок срабатывает на КПБ, а у кпб нет ДНК

2024-10-16 18:40 UTC, Darkiich commented on Content.Server/ADT/DNALocker/DNALockerSystem.cs
> +using Content.Server.Forensics;
Системы лучше занести в отдельную папку, чтобы не было каши. Например - Content.Server/ADT/DNALocker/Systems/DNALockerSystem.cs

2024-10-20 11:53 UTC, Mirokko requested changes
В целом хорошо, ожидаем новые изменения)

2024-10-20 11:53 UTC, Mirokko commented on Content.Server/ADT/DNALocker/Components/DNALockerComponent.cs
> +    public bool Locked = false;
Эта переменная не нужна, ведь наличие или отсутствие замка можно определить по наличию или отсутствию значения в DNA. Лучше сделай что-то похожее на:
```c#
public bool IsLocked 
{
    get => DNA != string.Empty; 
}
```

И поменять тип DNA просто на string, задав по умолчанию string.Empty

2024-10-20 11:53 UTC, Mirokko commented on Content.Server/ADT/DNALocker/Systems/DNALockerSystem.cs
> +        if (component.CanBeEmagged)
иф не это, ретурн

2024-10-20 11:53 UTC, Mirokko commented on Content.Server/ADT/DNALocker/Systems/DNALockerSystem.cs
> +            component.Locked = false;
Так, а вот к моему первому комменту - почему ДНК не обнуляется?

2024-10-20 11:53 UTC, Mirokko commented on Content.Server/ADT/DNALocker/Systems/DNALockerSystem.cs
> +            _popup.PopupEntity(selfMessage, equipee, equipee, PopupType.LargeCaution);
раз уж будешь вносить изменения, то попробуй в течении этих трёх секунд емагнуть, если снялся заряд то по логике всё должно отмениться, а этого не произойдёт и взорвётся

2024-10-22 07:32 UTC, Mirokko approved these changes
LGTM

2024-10-22 08:17 UTC, Darkiich approved these changes
Молодец, заслужил апрув)

2024-10-22 08:22 UTC, merged