Medupdate
AdventureTimeSS14/space_station_ADT pull request #629
Opened 2024-10-11 10:53 UTC by Filokini

:cl:
- add: Добавлено веселье!
- remove: Удалено веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2024-10-11 10:58 UTC, FaDeOkno commented
Описание?

2024-10-11 11:05 UTC, Filokini commented
так не готово ещё

2024-10-16 17:00 UTC, JustKekc commented
![image](https://github.com/user-attachments/assets/48120a41-b6bc-49c4-b2e8-4b4b677c581c)
👍

2024-10-17 04:01 UTC, Darkiich requested changes
А так видно?

2024-10-17 09:10 UTC, Filokini commented on Resources/Prototypes/Hydroponics/seeds.yml
> +    - ADTCannabisWhite
Ужас, как так

2024-10-17 09:10 UTC, Filokini commented on Resources/Prototypes/Entities/Structures/Storage/morgue.yml
> +# ADT tweak
Своровали гады

2024-10-17 09:10 UTC, Filokini commented on Resources/Prototypes/ADT/Recipes/Crafting/Graphs/smokeables.yml
> +- type: construction
понято

2024-10-17 14:10 UTC, Darkiich commented
Таак, а теперь в ченджлог напиши о том, что парамедик не может стать антагом

2024-10-19 11:20 UTC, Bolper commented
ееее бать

2024-10-19 17:14 UTC, Darkiich approved these changes
Ну ты молодчина

2024-10-19 17:14 UTC, Darkiich commented
Для справки: PR был протестирован вчера тестерами, а точнее armorkilled, изъяны были только в локализации

2024-10-19 17:17 UTC, Darkiich commented
> Для справки: PR был протестирован вчера тестерами, а точнее armorkilled, изъяны были только в локализации

Которые уже решены

2024-10-19 17:41 UTC, merged