Cердечно-лёгочная реанимация
AdventureTimeSS14/space_station_ADT pull request #643
Opened 2024-10-15 13:49 UTC by Schrodinger71

## Описание PR
Добавил новое действие при критическом состоянии сущности. Можно проводить теперь сердечно-лёгочную реанимацию

**Ссылка на публикацию в Discord**

## Техническая информация

## Медиа
![image](https://github.com/user-attachments/assets/c33eb71f-c18c-4a28-ac48-8e6f3d4cc771)

## Требования

- [ ] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [ ] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

## Критические изменения

**Чейнджлог**

2024-10-15 15:33 UTC, FaDeOkno requested changes

2024-10-15 15:33 UTC, FaDeOkno commented on Content.Server/ADT/ReliveResuscitation/ReliveResuscitationSystem.cs
> +        if (TryComp<MobStateComponent>(uid, out var mobState) && TryComp<MetaDataComponent>(args.User, out var metaDataUser) && TryComp<MetaDataComponent>(uid, out var metaDataTarget))
Не используй MetaDataComponent. Используй Identity.Entity(uid) в функции Relive (возможно, надо будет добавить какой-то юзинг)

2024-10-15 15:33 UTC, FaDeOkno commented on Content.Server/ADT/ReliveResuscitation/ReliveResuscitationSystem.cs
> +        //SubscribeLocalEvent<ReliveResuscitationComponent, ReliveDoAfterEvent>(ReliveEvent);
Ещё не доделано?

2024-10-15 15:33 UTC, FaDeOkno commented on Content.Shared/ADT/ReliveResuscitation/ReliveResuscitationComponent.cs
> +    public float SelfHealPenaltyMultiplier = 3f;
я извиняюсь, А КАК ты СЕБЕ будешь СЛР делать??

2024-10-15 16:07 UTC, Schrodinger71 commented on Content.Shared/ADT/ReliveResuscitation/ReliveResuscitationComponent.cs
> +    public float SelfHealPenaltyMultiplier = 3f;
это вообще там не нужно хуйню впихнул которая нигде не используется

2024-10-15 17:39 UTC, Schrodinger71 commented on Content.Server/ADT/ReliveResuscitation/ReliveResuscitationSystem.cs
> +        if (TryComp<MobStateComponent>(uid, out var mobState) && TryComp<MetaDataComponent>(args.User, out var metaDataUser) && TryComp<MetaDataComponent>(uid, out var metaDataTarget))
угу

2024-10-15 18:20 UTC, FaDeOkno requested changes

2024-10-15 18:20 UTC, FaDeOkno commented on Content.Server/ADT/ReliveResuscitation/ReliveResuscitationSystem.cs
> +            Relive(uid, args.Used.Value, component);
Во-первых добавь проверку на состояние цели
Во-вторых вместо этого используй args.Repeat

2024-10-15 18:27 UTC, Schrodinger71 commented on Content.Server/ADT/ReliveResuscitation/ReliveResuscitationSystem.cs
> +            Relive(uid, args.Used.Value, component);
https://github.com/AdventureTimeSS14/space_station_ADT/pull/643/commits/163958cc130ef7bbda8daecb869b76808efe83f9
Ну вроде готово

2024-10-15 18:31 UTC, Schrodinger71 commented on Content.Server/ADT/ReliveResuscitation/ReliveResuscitationSystem.cs
> +            Relive(uid, args.Used.Value, component);
а не

2024-10-15 18:32 UTC, FaDeOkno commented on Content.Server/ADT/ReliveResuscitation/ReliveResuscitationSystem.cs
> +            Relive(uid, args.Used.Value, component);
А проверка на состояние?

2024-10-15 18:54 UTC, Schrodinger71 commented on Content.Server/ADT/ReliveResuscitation/ReliveResuscitationSystem.cs
> +            Relive(uid, args.Used.Value, component);
Добавил же

2024-10-15 19:26 UTC, FaDeOkno commented on Content.Server/ADT/ReliveResuscitation/ReliveResuscitationSystem.cs
> +            Relive(uid, args.Used.Value, component);
Только оно не остановится даже когда человек поднимется, ибо рипит ничто не выключает

2024-10-15 19:32 UTC, Schrodinger71 commented on Content.Server/ADT/ReliveResuscitation/ReliveResuscitationSystem.cs
> +            Relive(uid, args.Used.Value, component);
Так сделать?
```cs
    private void DoRelive(EntityUid uid, ReliveResuscitationComponent component, ref ReliveDoAfterEvent args)
    {
        if (TryComp<MobStateComponent>(uid, out var mobState) && mobState.CurrentState == MobState.Critical)
        {
            if (args.Handled || args.Cancelled)
                return;

            FixedPoint2 asphyxiationHeal = -20;
            FixedPoint2 bluntDamage = 3;
            DamageSpecifier damageAsphyxiation = new(_prototypeManager.Index<DamageTypePrototype>("Asphyxiation"), asphyxiationHeal);
            DamageSpecifier damageBlunt = new(_prototypeManager.Index<DamageTypePrototype>("Blunt"), bluntDamage);
            _damageable.TryChangeDamage(uid, damageAsphyxiation, true);
            _damageable.TryChangeDamage(uid, damageBlunt, true);

            args.Handled = true;
            args.Repeat = true;
        }
        else
        {
            args.Repeat = false;
        }
    }
    ```

2024-10-15 19:55 UTC, FaDeOkno commented on Content.Server/ADT/ReliveResuscitation/ReliveResuscitationSystem.cs
> +            Relive(uid, args.Used.Value, component);
Без лесенок

```
        if (!TryComp<MobStateComponent>(uid, out var mobState) || mobState.CurrentState != MobState.Critical)
        {
                args.Repeat = false;
                return;
        }
```

2024-10-15 19:56 UTC, FaDeOkno commented on Content.Server/ADT/ReliveResuscitation/ReliveResuscitationSystem.cs
> +            Relive(uid, args.Used.Value, component);
И в основных DoAfterArgs поставь Repeat на true

2024-10-15 20:13 UTC, Mirokko requested changes

2024-10-15 20:13 UTC, Mirokko commented on Content.Server/ADT/ReliveResuscitation/ReliveResuscitationSystem.cs
> +            if (mobState.CurrentState == MobState.Critical)
Лучше обьединить эти 2 ифа и не надо тройную вложенность. Просто напиши, что если не вот это всё, то ретурн.

2024-10-15 20:13 UTC, Mirokko commented on Content.Server/ADT/ReliveResuscitation/ReliveResuscitationSystem.cs
> +        if (TryComp<MobStateComponent>(uid, out var mobState) && mobState.CurrentState == MobState.Critical)
эта проверка должна быть и в функции Revive в самом начале. И так же эта проверка должна быть тут в начале и вокруг args.Repeat = true.  И аналогично - если нет то ретурн, не надо делать громадные ифы.

2024-10-15 20:17 UTC, Schrodinger71 commented on Content.Server/ADT/ReliveResuscitation/ReliveResuscitationSystem.cs
> +            Relive(uid, args.Used.Value, component);
ну допустим, лесенок нет

2024-10-15 20:17 UTC, Schrodinger71 commented on Content.Server/ADT/ReliveResuscitation/ReliveResuscitationSystem.cs
> +            if (mobState.CurrentState == MobState.Critical)
готово

2024-10-15 20:59 UTC, Schrodinger71 commented on Content.Server/ADT/ReliveResuscitation/ReliveResuscitationSystem.cs
> +        if (TryComp<MobStateComponent>(uid, out var mobState) && mobState.CurrentState == MobState.Critical)
yes

2024-10-16 08:41 UTC, Schrodinger71 commented
мб кину всё шейрад

2024-10-16 12:26 UTC, JustKekc commented
cool.

2024-10-16 13:50 UTC, Mirokko requested changes
В целом хорошо движемся

2024-10-16 13:50 UTC, Mirokko commented on Content.Shared/ADT/ReliveResuscitation/ReliveResuscitationComponent.cs
> +    public ProtoId<DamageTypePrototype> DamageBlunt = "Blunt";
нет нет нет нет, одно поле типа DamageSpecifier. Если хочешь рандом, то 2 поля мин и макс.

2024-10-16 13:50 UTC, Mirokko commented on Content.Shared/ADT/ReliveResuscitation/SharedReliveResuscitationSystem.cs
> +        if (TryComp<MobStateComponent>(uid, out var mobState) && mobState.CurrentState == MobState.Critical)
опять лестницы. Если не вот это всё - то ретурн и всё. Избегай лишних вложенностей

2024-10-16 13:50 UTC, Mirokko commented on Content.Shared/ADT/ReliveResuscitation/SharedReliveResuscitationSystem.cs
> +        args.Repeat = true;
эта строчка не нужна, он у тебя по умолчанию репит из-за кода на 81 строчке

2024-10-16 13:50 UTC, Mirokko commented on Content.Shared/ADT/ReliveResuscitation/SharedReliveResuscitationSystem.cs
> +            var locReliveAbort = Loc.GetString("relive-abort-message",
раз уж всеравно изменения есть, то сделай 2 сообщения - ваш пациент умер когда о Dead и ваш пациент с громким вдохом ожил когда Alive

2024-10-16 13:50 UTC, Mirokko commented on Resources/Prototypes/ADT/Entities/Mobs/Species/Drask.yml
> +  - type: ReliveResuscitation
Тут и далее вопрос на подумать - а все ли должны уметь делать слр или только врачи? Возможно, следует привязать к роли СБ, Меда и НИО, а не к рассе.

2024-10-16 13:56 UTC, Schrodinger71 commented on Content.Shared/ADT/ReliveResuscitation/SharedReliveResuscitationSystem.cs
> +        args.Repeat = true;
А вот кстати повтор не работал... Я тестил..

2024-10-16 13:57 UTC, Schrodinger71 commented on Resources/Prototypes/ADT/Entities/Mobs/Species/Drask.yml
> +  - type: ReliveResuscitation
Да базовая мед помощь..

2024-10-16 13:58 UTC, Schrodinger71 commented on Content.Shared/ADT/ReliveResuscitation/ReliveResuscitationComponent.cs
> +    public ProtoId<DamageTypePrototype> DamageBlunt = "Blunt";
Я тут пытался по всякому

2024-10-16 13:58 UTC, Schrodinger71 commented on Content.Shared/ADT/ReliveResuscitation/ReliveResuscitationComponent.cs
> +    public ProtoId<DamageTypePrototype> DamageBlunt = "Blunt";
_prototypeManager по моему придется юзать?

2024-10-16 14:15 UTC, Mirokko commented on Content.Shared/ADT/ReliveResuscitation/ReliveResuscitationComponent.cs
> +    public ProtoId<DamageTypePrototype> DamageBlunt = "Blunt";
Пример DamageOnTriggerComponent

2024-10-16 17:33 UTC, Schrodinger71 commented
![image](https://github.com/user-attachments/assets/a3fbfe80-04f6-431a-8876-5047e0a23ea6)

2024-10-27 07:24 UTC, Schrodinger71 commented
Переведу пока в драфт

2024-10-29 21:20 UTC, Schrodinger71 commented
https://github.com/Schrodinger71/Develop_ADT/pull/22  -  чтобы не валялось просто так, перенесу сюда, ветку с основной репы удалю

2024-10-29 21:20 UTC, closed without merging