гостбар
AdventureTimeSS14/space_station_ADT pull request #651
Opened 2024-10-16 06:40 UTC by Ratyyy

## Описание PR

добавила гостбар и пулл для него
## Почему / Баланс

**Ссылка на публикацию в Discord**

веселье гостов

## Медиа

## Требования

- [x] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [x] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

## Критические изменения

**Чейнджлог**

:cl: Ratyyy
- add: Призраки нашли для себя целое кафе, в котором они могут отдыхать после смерти!

2024-10-16 14:06 UTC, Mirokko commented on Content.Server/ADT/Ghostbar/GhostBarMapPoolPrototype.cs
> +    public HashSet<string> Maps = new(0);
Тут не string должен быть 100%

2024-10-16 14:07 UTC, Mirokko commented on Content.Server/ADT/Ghostbar/GhostBarSystem.cs
> +    private static readonly List<JobComponent> _jobComponents = new()
это должно быть в прототипе карты

2024-10-17 16:19 UTC, Mirokko submitted a review, later dismissed
Ну по верхам отписал, но нет предела совершенству.

2024-10-17 16:19 UTC, Mirokko commented on Content.Client/UserInterface/Systems/Ghost/GhostUIController.cs
> +        Gui.GhostBarPressed += GhostBarPressed; // Goobstation - Ghost Bar
Отпишу тут, но относится ко всему. Подумай над тем, как вынести это всё в класс через partial. Это же и к Content.Client/Ghost/GhostSystem.cs.

2024-10-17 16:19 UTC, Mirokko commented on Content.Server/ADT/Ghostbar/GhostBarSystem.cs
> +    public GhostBarMapPrototype? _GhostBarMap;
эта строка должна быть над методом Initialize и сеттится там тоже должна. Нет смысла каждый раз по всем прототипам проходить, рандомя один. Кстати, этот функционал весь можно вынести в отдельный класс GhostBarMapManager. И будет что-то в стиле manager.GetNextMap(). Можно в будущем будет дописать, чтобы не было 2 гостбара одинаковых подряд или добавить веса по какому-недь алгоритму.

2024-10-17 16:19 UTC, Mirokko commented on Content.Server/ADT/Ghostbar/GhostBarSystem.cs
> +        if (mapProto == null) /// тут проверки и загрузки переменных
лишний коммент тут и ниже, но забавно

2024-10-17 16:19 UTC, Mirokko commented on Content.Server/ADT/Ghostbar/GhostBarSystem.cs
> +    }
Ну в целом отпишу тут, а будут ли работать ивенты на этой карте и можно ли их отключить? Типа забившихся скрубберов и т д.

2024-10-17 16:19 UTC, Mirokko commented on Content.Server/ADT/Ghostbar/GhostBarSystem.cs
> +        if (spawnPoints.Count == 0)
Хорошо бы было добавить какойнедь тест, который бы убеждался, что хотябы 1 позиция для спавна присутствует.

2024-10-17 16:19 UTC, Mirokko commented on Content.Server/ADT/Ghostbar/GhostBarSystem.cs
> +        _entityManager.EnsureComponent<AntagImmuneComponent>(mobUid);
Вот идеи чтобы сделать что-то уникальное:
1. Можно тут еще добавить компонент, который добавит стелз с низкой прозрачностью, который не сбивается при ходьбе. Призраки!
2. Всем добавить компонент, который добавит прикольную подпись к имени. Достаточно будет изменить имя на "Призрак Бесстрашной Велайс" и добавить описание что это призрак, который никак не может попасть на тот свет. Почему бы и не поинтересоваться о его страшной судьбе? И дальше описание персонажа пусть будет.

2024-10-17 16:19 UTC, Mirokko commented on Content.Server/ADT/Ghostbar/GhostBarSystem.cs
> +        _entityManager.DeleteEntity(uid);
Прикольно было бы сделать еще попап что призрак отправился на следующий круг перерождения. Чисто РП момент.

2024-10-17 16:19 UTC, Mirokko commented on Resources/Prototypes/Goobstation/Entities/Markers/Spawners/ghost_roles.yml
> +  - type: GhostBarSpawn
Имеет смысл поменять название компонента на GhostBarSpawnPoint, чтобы было чуть очевиднее.

2024-10-17 16:24 UTC, Ratyyy commented on Content.Server/ADT/Ghostbar/GhostBarSystem.cs
> +        _entityManager.EnsureComponent<AntagImmuneComponent>(mobUid);
идеи... сомнительные. Я вынесу их в отдельную переменную, пусть маперы делают, если хотят

2024-10-17 16:24 UTC, Ratyyy commented on Content.Server/ADT/Ghostbar/GhostBarSystem.cs
> +        if (spawnPoints.Count == 0)
если позиции нет - игрока просто не спавит. По факту уже есть, вроде

2024-10-17 16:25 UTC, Ratyyy commented on Content.Server/ADT/Ghostbar/GhostBarSystem.cs
> +    }
не будут. Это такая же карта как арума и подобные

2024-10-17 16:44 UTC, Ratyyy commented on Content.Server/ADT/Ghostbar/GhostBarSystem.cs
> +        _entityManager.DeleteEntity(uid);
это будет странновато... особенно, если человек вышел просто чтобы сменить профессию, после чего вернулся обратно. А вот сделать какую-нибудь анимацию призрака можно будет попробовать

2024-10-17 17:55 UTC, Ratyyy commented on Content.Server/ADT/Ghostbar/GhostBarSystem.cs
> +    public GhostBarMapPrototype? _GhostBarMap;
я просто постараюсь вырезать часть, чтобы слегка укоротить код. Не вижу сильной надобности в отдельном менеджере для этого

2024-10-17 18:12 UTC, Ratyyy commented on Content.Server/ADT/Ghostbar/GhostBarSystem.cs
> +    public GhostBarMapPrototype? _GhostBarMap;
нет, идея была плохая. Нельзя вызвать метод, который не инициализировало, потому лучше оставить так как сейчас.

2024-10-18 09:53 UTC, Ratyyy commented on Content.Client/UserInterface/Systems/Ghost/GhostUIController.cs
> +        Gui.GhostBarPressed += GhostBarPressed; // Goobstation - Ghost Bar
это перенести не выйдет. Если поменять одно - надо будет поменять всё, в следствии чего надо будет чуть ли не свой контроллер для интерфеса гостов выписывать.

2024-10-19 22:05 UTC, FaDeOkno commented on Content.Client/UserInterface/Systems/Ghost/GhostUIController.cs
> +        Gui.GhostBarPressed += GhostBarPressed; // Goobstation - Ghost Bar
> Отпишу тут, но относится ко всему. Подумай над тем, как вынести это всё в класс через partial. Это же и к Content.Client/Ghost/GhostSystem.cs.

УИ перенесён, а ради того несчастного метода в GhostSystem делать файл смысла ноль

2024-10-19 23:29 UTC, FaDeOkno commented
@Ratyyy пожалуйста, хватит использовать EntityManager в EntitySystem, есть гораздо более короткие функции с тем же функционалом

2024-10-20 11:26 UTC, Mirokko commented on Content.Server/ADT/Ghostbar/GhostBarSystem.cs
> +        if (_mapLoader.TryLoad(mapId, mapProto.Path, out _, options))
Полагаю, сейчас уже ладно (если не найду еще проблем, то лучше всё же попровить), но не надо плодить вложенности. Просто:

```
if (!_mapLoader.TryLoad(mapId, mapProto.Path, out _, options))
    return;
```

2024-10-20 11:27 UTC, Mirokko commented on Content.Server/ADT/Ghostbar/GhostBarSystem.cs
> +            if (mapProto.Weather.HasValue)
аналогично как и выше

2024-10-20 11:39 UTC, Mirokko requested changes
Как-то так

2024-10-20 11:39 UTC, Mirokko commented on Content.Server/ADT/Ghostbar/GhostBarSystem.cs
> +    public GhostBarMapPrototype? GhostBarMap; /// его значение нельзя объявить методом. Много проб, ни одна из них не успешна, даже в гугле информации про такое нету.
Нафига тебе метод? Я говорил совершенно про другое. Я говорил о менеджере, в котором будет... Просто перечитайте моё сообщение, там отписано. Если вопросы или непонятно что именно я имел ввиду - в чате спросите

2024-10-20 11:39 UTC, Mirokko commented on Content.Server/ADT/Ghostbar/GhostBarSystem.cs
> +        Spawn("PolymorphAshJauntAnimation", Transform(uid).Coordinates);    // Спавн пепла при удалении, дабы выглядело чутка лучше
Не пепла, а плазмы, как от приведения фиолетового (фантом)

2024-10-20 11:39 UTC, Mirokko commented on Content.Server/ADT/Ghostbar/GhostBarSystem.cs
> +        if (spawnPoints.Count == 0)
Идея была в другом - чтобы при добавлении карты чтобы некто не проебался эпично и не краснел потом

2024-10-20 12:03 UTC, FaDeOkno commented on Content.Server/ADT/Ghostbar/GhostBarSystem.cs
> +        Spawn("PolymorphAshJauntAnimation", Transform(uid).Coordinates);    // Спавн пепла при удалении, дабы выглядело чутка лучше
Мне кажется это излишним, да и пепел получше выглядит

2024-10-22 07:49 UTC, FaDeOkno approved these changes
Проверено и исправлено на локалке

2024-10-22 20:43 UTC, merged