Изменил защиту экзокостюмов и комплектацию вещмешков РХБЗЗ
AdventureTimeSS14/space_station_ADT pull request #662
Opened 2024-10-21 22:18 UTC by RipZoro1

## Описание PR

Изменил комплектацию вещей и статистику экзокостюмов отряда РХБЗЗ
## Почему / Баланс

**Ссылка на публикацию в Discord**

- [Заказик](https://discord.com/channels/901772674865455115/1292482551444803604)
## Техническая информация

## Медиа

![dgfdfgdfgd](https://github.com/user-attachments/assets/e10cbb21-b955-4999-a962-25c6763e6c8f)
![sdfdfdsf](https://github.com/user-attachments/assets/f6bb48b5-9da4-4054-ae57-1a088ebeb77d)
![gfdfdgdf](https://github.com/user-attachments/assets/79723269-83c1-42e2-b22f-da2481ffabb0)
![sfddsdf](https://github.com/user-attachments/assets/46f50e18-6cc6-420d-821e-25b65f30c83a)
## Требования

- [X] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [X] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

## Критические изменения

**Чейнджлог**

:cl: Rip_Zoro
- tweak: НТ Изменило комплектацию вещей в вещмешке отряда РХБЗЗ
- tweak: НТ усилило экзокостюмы отряда РХБЗЗ

2024-10-22 05:30 UTC, Darkiich requested changes
Ревью

2024-10-22 05:30 UTC, Darkiich commented on Resources/Prototypes/ADT/StartingGear/ERT/ert_leader.yml
> +    - WeaponShotgunBulldog #ADT-tweak
Если прототип находится в папке ADT, то эти комментарии не обязательные

2024-10-22 05:30 UTC, Darkiich commented on Resources/Prototypes/Corvax/Entities/Clothing/OuterClothing/hardsuits.yml
> +        Blunt: 0.3 #ADT-tweak
Если ты изменяет цифры, то надо писать с какого значения ты изменил. По типу # ADT Tweak 0.7 -> 0.3 и так с каждым

2024-10-22 05:30 UTC, Darkiich commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +        Blunt: 0.4 #ADT-tweak
Тут такая же ситуация

2024-10-22 05:30 UTC, Darkiich commented on Resources/Prototypes/Roles/Jobs/CentComm/cburn.yml
> +    - BoxSurvivalEngineering
Тут пропустил вообще комментарий

2024-10-22 05:30 UTC, Darkiich commented on Resources/Prototypes/Roles/Jobs/CentComm/cburn.yml
> +    - WeaponShotgunEnforcer #ADT-tweak
А здесь уровень ADT-Tweak зашкаливает. Можно просто добавленные прототипы заключить в один комментарий. По типу

#ADT Tweak start
- прототип
- прототип
- прототип и.т.д

#ADT-Tweak end

2024-10-22 05:33 UTC, Darkiich commented
С днём комментариев!!

2024-10-22 07:07 UTC, RipZoro1 commented on Resources/Prototypes/Roles/Jobs/CentComm/cburn.yml
> +    - WeaponShotgunEnforcer #ADT-tweak
всмысле. Я не понял

2024-10-23 04:18 UTC, Darkiich commented
Все, молодец. А тесты я чиню сам, так что не трогай их

2024-10-23 13:46 UTC, merged