Перевод :)
AdventureTimeSS14/space_station_ADT pull request #676
Opened 2024-10-26 09:38 UTC by RipZoro1

## Описание PR

Добавил перевод ионной винтовки и товарной единицы
## Почему / Баланс

**Ссылка на публикацию в Discord**

- [forum-translator](hhtps://discord.com/channels/901772674665455115/1297383071141724251)
- [forum-translator](hhtps://discord.com/channels/901772674665455115/1284603884215603320)
## Техническая информация

## Медиа

## Требования

- [X] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [X] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

## Критические изменения

**Чейнджлог**

:cl: Rip_Zoro
- tweak: Добавлен перевод ионной винтовки.
- tweak: Добавлен перевод валюты аплинка ОБР.

2024-10-26 18:43 UTC, Inconnu1337 commented
+ мне кажется лучше написать в чейнджлоге
add: Добавлен перевод ионной винтовки, и валюты аплинка ОБР.

2024-10-27 07:52 UTC, Schrodinger71 requested changes
YAML Linter

2024-10-27 10:37 UTC, Inconnu1337 commented on Resources/Locale/ru-RU/ADT/Objects/Weapons/Guns/rifles.ftl
> +ent-Productunit = ионная винтовка
какой Productunit?

2024-10-27 10:37 UTC, Inconnu1337 commented on Resources/Locale/ru-RU/ADT/Objects/Specific/product-unit.ftl
> +ent-Productunit = торговая единица
фигня название подумай над лучшим

2024-10-27 10:38 UTC, Inconnu1337 commented on Resources/Locale/ru-RU/ADT/Objects/Weapons/Guns/rifles.ftl
> +ent-Productunit = ионная винтовка
из за этого _ямл линтер_ падает

2024-10-27 10:46 UTC, RipZoro1 commented on Resources/Locale/ru-RU/ADT/Objects/Specific/product-unit.ftl
> +ent-Productunit = торговая единица
Мне крыса сказала, что так переводится

2024-10-27 11:02 UTC, Inconnu1337 commented on Resources/Locale/ru-RU/ADT/Objects/Specific/product-unit.ftl
> +ent-Productunit = торговая единица
ну так оно так и переводится, но какая разница как переводится? Звучит шакально и бредово

2024-10-27 12:07 UTC, Darkiich approved these changes
Теперь все ок

2024-10-27 21:48 UTC, merged