Пушка гонка
AdventureTimeSS14/space_station_ADT pull request #693
Opened 2024-10-28 21:47 UTC by RipZoro1

## Описание PR

Вернул агосту слот под очки, добавил бодикамеры в сбтех и добавил возможность положить телескопичку в рпс и пояс охраны
## Почему / Баланс

Так нужно

## Техническая информация

## Медиа

## Требования

- [X] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [X] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

## Критические изменения

**Чейнджлог**

:cl: Rip_Zoro
- add: Добавлен слот очков админ призраку.
- add: НТ добавило бодикамеры в СБтех.
- add: Теперь телескопическую дубинку можно положить в рпс и пояс охраны.

2024-10-28 22:14 UTC, Inconnu1337 commented on Resources/Prototypes/InventoryTemplates/aghost_inventory_template.yml
> +    - name: eyes #ADT-Tweak
# ADT-Tweak-Start
**
# ADT-Tweak-End

2024-10-28 22:15 UTC, Inconnu1337 requested changes
ямл линтер

2024-10-28 22:22 UTC, Inconnu1337 commented
касательно бодикамер в сбтехе - сомнительно
слишком имба будто

2024-10-29 04:30 UTC, Schrodinger71 commented
Ссылки на публикации в дисе пжж

2024-10-29 05:29 UTC, Darkiich commented
> касательно бодикамер в сбтехе - сомнительно слишком имба будто

Пойдет

2024-10-29 05:31 UTC, Darkiich requested changes
А теперь надо добавить бодикамеры в коробку пополнения сбтеха

2024-10-29 22:42 UTC, RipZoro1 commented
Оке

2024-10-30 05:21 UTC, Filokini commented
теперь надо все в игре ADTtelescopicBaton заменить на ADTTelescopicBaton

2024-10-30 05:44 UTC, Filokini approved these changes
Good work man

2024-10-30 05:53 UTC, merged