Вещи ЦК и суперсинтезатор в лодауте музыканта.
AdventureTimeSS14/space_station_ADT pull request #712
Opened 2024-10-30 21:19 UTC by RipZoro1

## Описание PR

Вещи ЦК и суперсинтезатор в лодауте музыканта.
## Почему / Баланс

**Ссылка на публикацию в Discord**

- [Предложения](https://discord.com/channels/901772674865455115/1300964874012069999)
- [Заказик](https://discord.com/channels/901772674865455115/1300964874012069999)
## Техническая информация

## Медиа

## Требования

- [Х] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [Х] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

## Критические изменения

**Чейнджлог**

:cl: Rip_Zoro
- add: Добавлен пальто и сумка ПЦК
- add: Вещи ПЦК добавлены в ЦентШкаф
- add: Добавлен суперсинтезатор в лодаут музыканта

2024-10-31 12:55 UTC, Darkiich requested changes
Так, во-первых спрайты должны быть в папке ADT

2024-11-01 23:44 UTC, Inconnu1337 requested changes
ямл линтер!

2024-11-03 23:08 UTC, KashRas2 reviewed
Я боюсь потом забыть про этот пр, поэтому оставлю это просто как комментарий, а не требование.

2024-11-03 23:08 UTC, KashRas2 commented on Resources/Prototypes/Loadouts/Jobs/Civilian/musician.yml
> +      role: Musician
Он тебе тут ошибку пишет, мол, нет такого трекера времени для роли. Они обычно начинаются с приписки Job.

2024-12-06 16:11 UTC, Filokini approved these changes

2024-12-06 16:57 UTC, merged