Дракон, LobbyScreens, Фамилии, ДНК
AdventureTimeSS14/space_station_ADT pull request #716
Opened 2024-10-31 11:15 UTC by jungarikjan

## Описание PR
Новый фон лобби
ДНК для скафов РХБЗЗ
Бафф дракона
Удалены спорные человеческие мужские и женские фамилии во избежание использования недоброжелателями и ЛРПшерами
Карпы, вылезающие из портала дракона, не могут гореть
удален фон лобби с рекламой другого проекта

• Бафф дракона:
Дракона нельзя усыпить и ослепить
Дальность удара с 1.5 до 2
Скорость бега: 5 -> 5.5
Скорость ходьбы: 3 -> 3.5
Вес дракона со 100 до 200
Устойчивость к холоду: -800, к теплу: 800
То же самое с температурой у карпов дракона (именно тех, кто вылезает из портала)
Повышен дамаг фаербола. СБшник в броне будет при прямом попадании получать 70 хп, при непрямом 30. В скафе - 18 при непрямом, 50-60 при прямом

Изменено замедление дракона:
- 250 хп - замедление 15%, было 30
- 350 хп - замедление 30% (новое значение)
- 430 хп - замедление 50% (было от 400хп)
-

## Почему / Баланс
Фамилии против ЛРП и набегеров, ищущих лазейки в правилах
Лобби арты просто
Дракона бафф потому что его фаерболы никому не страшны, аж пассажиры на него кидаются
ДНК для скафов РХБЗЗ ибо забыли

**Ссылка на публикацию в Discord**
Собственная инициатива

## Техническая информация
ЯМЛики только

## Медиа
Медиа в комментариях

## Требования
- [x] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [x] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

## Критические изменения
Не имеются

**Чейнджлог**
:cl: eddiemercury
- add: Новый фон лобби
- add: ДНК для скафов РХБЗЗ
- tweak: Бафф дракона (в описании к ПРу)
- tweak: Удалены спорные человеческие мужские и женские фамилии во избежание использования недоброжелателями и ЛРПшерами
- tweak: Карпы, вылезающие из портала дракона, не могут гореть
- remove: удален фон лобби с рекламой другого проекта

2024-10-31 11:38 UTC, Inconnu1337 requested changes
остальное вроде норм чутка отписал ниже

2024-10-31 11:38 UTC, Inconnu1337 commented on Resources/Prototypes/Entities/Mobs/Player/dragon.yml
> +  - type: Damageable
комментарии

2024-10-31 11:38 UTC, Inconnu1337 commented on Resources/Prototypes/Entities/Mobs/Player/dragon.yml
> +    range: 2
комментарии

2024-10-31 11:38 UTC, Inconnu1337 commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/magic.yml
> +    intensitySlope: 10
комментарии

2024-10-31 12:01 UTC, Inconnu1337 approved these changes
ну вроде еорммально

2024-10-31 19:19 UTC, COTE-LAPYX commented
Если дракона нельзя усыпить или ослепить, может тогда и действие пакса и замедление от реагентов ему отключите? 
Можно иначе его убить через 10 унц. пакса 

Да и замедление от снотворного типа раз уж у него на сон иммунитет, то чего на это нет?

2024-10-31 22:58 UTC, Inconnu1337 commented
@jungarikjan котя лапух правильно говорит

2024-11-02 01:53 UTC, merged

2024-11-02 12:03 UTC, Schrodinger71 commented
Хорош пупус