Морожемат
AdventureTimeSS14/space_station_ADT pull request #727
Opened 2024-11-02 02:10 UTC by sh4zik

## Описание PR
Добавление морожемата

## Почему / Баланс
На данный момент получить мороженное игрокам нельзя никаким образом, Также когда-то давно я заметил это в предложениях для сервера, Поэтому, Встречайте, Морожемат

## Требования

- [Х] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [Х] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

**Чейнджлог**

:cl: Sh4zik
- add: Добавлен Морожемат с большим количеством мороженного!

2024-11-02 04:32 UTC, Darkiich requested changes
Ревью

2024-11-02 04:32 UTC, Darkiich commented on Resources/Locale/ru-RU/ADT/Adverisements/icecreammat.yml
> +advertisement-IceCreammatAds-1 = Лучшее мороженное, Из натурального молока!
Все слова после запятой, должны быть с маленькой буквы

2024-11-02 04:32 UTC, Darkiich commented on Resources/Locale/ru-RU/ADT/Adverisements/icecreammat.yml
> +advertisement-IceCreammatAds-5 = МО-РО-ЖЕ-НН-ОЕ!
В слове мороженое одна буква "н"

2024-11-02 04:32 UTC, Darkiich commented on Resources/Prototypes/ADT/Entities/Structures/Machines/vending_machines.yml
> +  - type: AccessReader
Так и задумано было, что доступ только у медиков?

2024-11-02 08:43 UTC, sh4zik commented
> Ревью

Всё починил, вроде как..

2024-11-02 11:08 UTC, Inconnu1337 approved these changes
гуд

2024-11-02 11:21 UTC, Filokini commented
не мержите дайте глянуть

2024-11-04 21:18 UTC, Filokini approved these changes
Забыл отписать, молодец, если цена вендомата будет большой, нужно будет настроить потом.

2024-11-05 10:42 UTC, merged