Тестовое Задание
AdventureTimeSS14/space_station_ADT pull request #729
Opened 2024-11-02 10:59 UTC by NameLunar

Шрёдька, не бей

2024-11-02 11:01 UTC, Bolper commented
Кто эт

2024-11-02 11:02 UTC, Darkiich commented
> Кто эт

Чш, это лунар сосиска

2024-11-02 11:03 UTC, Darkiich commented
> Кто эт

Ревью этому PR не проводи

2024-11-02 11:04 UTC, Bolper requested changes

2024-11-02 11:04 UTC, Bolper commented on Resources/Locale/ru-RU/ADT/prototypes/Catalog/Fills/Crates/food.ftl
> +ent-ADTFoodVulpix = Вульпикс
дублирование вижу

2024-11-02 11:04 UTC, Bolper commented on Resources/Prototypes/Catalog/Fills/Crates/food.yml
> +  id: ADTFoodVulpix
id говно

2024-11-02 11:04 UTC, Bolper commented on Resources/Prototypes/Catalog/Fills/Crates/food.yml
> +  id: ADTFoodVulpix
И расположение тоже видимо

2024-11-02 11:04 UTC, Bolper commented on Resources/Prototypes/Catalog/Fills/Crates/food.yml
> +  id: ADTFoodVulpix
расположение - говна да

2024-11-02 11:04 UTC, Bolper commented on Resources/Prototypes/Corvax/Recipes/Cooking/meat_recipes.yml
расположение говна

2024-11-02 11:04 UTC, Bolper commented on Resources/Textures/Objects/Consumable/Food/Vulpix.rsi/meta.json
Тож самое не то расположение и я спрайта не вижу

2024-11-02 11:05 UTC, Bolper commented
> > Кто эт
> 
> Ревью этому PR не проводи

ой ой
Ну я чуток сделал не особо заморачивался

2024-11-02 11:07 UTC, Darkiich commented
> > > Кто эт
> > 
> > 
> > Ревью этому PR не проводи
> 
> ой ой Ну я чуток сделал не особо заморачивался

Мда..

2024-11-02 11:44 UTC, Darkiich requested changes
Ревью

2024-11-02 11:44 UTC, Darkiich commented on Resources/Locale/ru-RU/ADT/prototypes/Catalog/Fills/Crates/food.ftl
> +ent-ADTFoodVulpix = Вульпикс
Тут надо убрать дубликат
```
ent-ADTFoodVulpix = Вульпикс
    .desc = Это помогает улучшить кровообращение. 
```
и переместить это по пути - Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Consumable/Food/meals.ftl

2024-11-02 11:44 UTC, Darkiich commented on Resources/Prototypes/Catalog/Fills/Crates/food.yml
> +- type: entity
Во-первых, этот комментарий тут не нужен.

Во-вторых, ты забыл добавить вкус блюду(всплывающий текст когда ты что-то ешь, по типу "на вкус сырно и горько"). 

В третьих, этот прототип должен быть по пути - Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/твой файл.yml(например - vulpix.yml)

2024-11-02 11:44 UTC, Darkiich commented on Resources/Prototypes/Corvax/Recipes/Cooking/meat_recipes.yml
> +#Тестовое заданеи
Во-первых, комментарий тоже не нужен

Во-вторых, перенеси это по пути - Resources/Prototypes/ADT/Recipes/Cooking/meal_recipes.yml

2024-11-02 11:44 UTC, Darkiich commented on Resources/Textures/Objects/Consumable/Food/Vulpix.rsi/meta.json
> +{
Ты забыл добавить спрайт. Спрайт так же добавляй в папку Vulpix.rsi ,ОБЯЗАТЕЛЬНО с названием icon, потому что в мете ты прописал его как icon

2024-11-02 11:52 UTC, Schrodinger71 commented
нууу окееей

2024-11-03 11:47 UTC, NameLunar commented
Пупупу

2024-11-03 12:53 UTC, Schrodinger71 submitted a review, later dismissed
![image](https://github.com/user-attachments/assets/b0dac167-595b-4f06-b507-83742a0a464a)
С текстурами, путями что то ни так, чиним Ямл

2024-11-04 05:14 UTC, NameLunar commented
Оу, да. Путь же переместил. Щя исправлю

2024-11-04 05:27 UTC, NameLunar commented
Путь был неверный со стороны расположения файла. Я поменял на Objects/Consumable/Food/Vulpix.rsi

2024-11-04 05:48 UTC, NameLunar commented
Переделал дважды... Путь Resources/Textures/ADT/Objects/Consumable/Food/Vulpix.rsi

2024-11-04 06:10 UTC, NameLunar commented
Последний...

2024-11-04 20:57 UTC, Bolper commented
Учимся читать ошибки с Волпером. 
Для начала находим то место, где мы видим ошибки. 
Это место выглядит так. 
![Screenshot_2024-11-04-23-53-38-250_com.github.android.png](https://github.com/user-attachments/assets/6c350a04-0f00-405a-98e7-fd065aafee3b)

Нас в первую очередь интересует Ямал линтер, так как если он не проходит, остальное однозначно не пройдет
![Screenshot_2024-11-04-23-53-42-500_com.github.android.png](https://github.com/user-attachments/assets/7da97c19-4343-4071-96ce-10fc3fcb4418)

Тыкаем по нему и видим в самом начале сообщение
![Screenshot_2024-11-04-23-52-28-685_com.github.android.png](https://github.com/user-attachments/assets/e1a98606-4eb5-4178-92a2-b766164ef5db)


Ругается на то, что не может загрузить rsi
То бишь ошибка в спрайтах. 
Просматриваем для начала все пути
![Screenshot_2024-11-04-23-54-15-576_com.github.android.png](https://github.com/user-attachments/assets/b912c158-0bb0-44b6-89b8-182d933929f8)

![Screenshot_2024-11-04-23-53-56-562_com.github.android.png](https://github.com/user-attachments/assets/34bb6433-60aa-442c-bc6e-730d6a902c55)

Опа. Ошибка нашлась! Разный регистр путей! 
@NameLunar

2024-11-04 20:59 UTC, Bolper commented
Так что убирай все что лишнее на придумывал и исправляй это

2024-11-04 21:00 UTC, Bolper commented
И ожидаю спасибо в свой адрес

2024-11-05 16:52 UTC, Darkiich approved these changes
Молодец

2024-11-05 16:52 UTC, merged