UI Бриг-Таймера
AdventureTimeSS14/space_station_ADT pull request #735
Opened 2024-11-03 19:08 UTC by BitBoxxxer

## Описание PR
+ Добавлена новая строчка "Статьи:" 
+ перевод "(mm:ss)" в "(мин:сек)"
+ Изменено расширение окна на более широкую версию для удобства

## Почему / Баланс
Попросили uwu
https://discord.com/channels/901772674865455115/1302356853853786255

## Техническая информация
+ В комментариях кода будет объяснение

## Медиа
       
![Снимок экрана 2024-11-04 000751](https://github.com/user-attachments/assets/a99af922-8bf2-4746-a9ce-43ac89ac43c5)

## Требования
- [ДА] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [ДА] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

**Чейнджлог**

:cl:Kasey [Adnoda] Bitboxxer
- add: Добавлено Бриг-Таймер: появилась строчка "Статьи:" 
- tweak: Изменен Бриг-Таймер: окно стало шире и изменено описание минут, секунд

2024-11-03 19:15 UTC, BitBoxxxer commented on Content.Client/MachineLinking/UI/SignalTimerWindow.xaml.cs
> +
ограничение по символам == 19

2024-11-03 19:19 UTC, BitBoxxxer commented on Content.Client/MachineLinking/UI/SignalTimerWindow.xaml
> +        </BoxContainer> <!-- ADT END -->
"Text:" ищет лодаут что будет написан в начале строки как инструкция UI
MinWidth="240" размер длины <---> строчки

2024-11-03 19:34 UTC, BitBoxxxer commented on Content.Client/MachineLinking/UI/SignalTimerWindow.xaml.cs
> +    } // ADT END
логика проверки символов на ограничения

2024-11-03 19:35 UTC, BitBoxxxer commented on Content.Client/MachineLinking/UI/SignalTimerWindow.xaml.cs
> +            CurrentTextEditAnother.CursorPosition = MaxTextLengthAnother;
логика проверки символов на ограничения

2024-11-03 23:02 UTC, KashRas2 requested changes
Довольно неплохая работа, несмотря на это. К коду вопросов не имею, да и там сложно к чему-то прикопаться. Попрошу обратить внимание на те недочёты, что я вам указал.

2024-11-03 23:02 UTC, KashRas2 commented on Content.Client/MachineLinking/UI/SignalTimerWindow.xaml
> +            <Label Name="DelayInfo" Text=" (мин:сек)" />
1. Пометить комментариями, что тут было произведено изменение 
2. Нельзя сделать это через локализацию? Это не придирка, но так было бы лучше как по мне. Оставлю на ваше усмотрение

2024-11-03 23:02 UTC, KashRas2 commented on Resources/Locale/ru-RU/machine-linking/components/signal-timer-component.ftl
> +signal-timer-menu-label-another = Статьи:
Лучше всего это перенести в нашу папку. Местонахождение переводов не влияет на это вот все. Просто так будет удобнее вырезать в случае чего, да и во время апстримов не будет лишних конфликтов.

2024-11-04 07:01 UTC, BitBoxxxer commented on Resources/Locale/ru-RU/machine-linking/components/signal-timer-component.ftl
> +signal-timer-menu-label-another = Статьи:
Без проблем🤝

2024-11-04 07:05 UTC, BitBoxxxer commented on Content.Client/MachineLinking/UI/SignalTimerWindow.xaml
> +            <Label Name="DelayInfo" Text=" (мин:сек)" />
Оки, сделаю

2024-11-04 12:18 UTC, KashRas2 requested changes
А так нормально

2024-11-04 12:18 UTC, KashRas2 commented on Content.Client/MachineLinking/UI/SignalTimerWindow.xaml
> +            <Label Name="DelayInfo" Text="{Loc signal-timer-menu-min-sec-another}" />
Комментарий

2024-11-04 12:20 UTC, BitBoxxxer commented on Content.Client/MachineLinking/UI/SignalTimerWindow.xaml
> +            <Label Name="DelayInfo" Text="{Loc signal-timer-menu-min-sec-another}" />
да, заметила до тебя, вот только исправила😎

2024-11-04 12:22 UTC, KashRas2 approved these changes
Ладно, пойдет

2024-11-04 13:09 UTC, merged