[QoL, FIX, TWEAK] Печать, Имена боргов, Фикс жилета, Нёрф пожарного шлюза, Лобби-фон, Гамлет, плюш. Джунгарик
AdventureTimeSS14/space_station_ADT pull request #736
Opened 2024-11-03 20:08 UTC by jungarikjan

## Описание PR
- add: NanoTrasen начала производить и поставлять на СЦК печать "ПЕРЕДЕЛАТЬ", чтобы сотрудники не ставили "отказ" на неправильно оформленные факсы экипажа. Теперь админам будет проще.
- add: На экран ожидания перед началом смены добавлен новый красивый тематический арт.
- add: плюшевый Джунгарик умеет кричать, а также издает фразы как фигурка при использовании. Звук использования заменён на писк мыши.
- add: Мыши теперь умеют разговаривать на мышином, вместе с летучей мышью и Гамлетом. По крайней мере, выбрать язык - могут.
- remove: Руководство NanoTrasen во избежание нарушения трудового порядка запретило отправку боргов с глупыми или странными именами. Удалены глупые и ЛРПшные имена боргов, добавлены новые
- tweak: Руководство NanoTrasen решило производить пожарные шлюзы по аналогии с обычными, ибо чрезмерная прочность им ни к чему, они всё итак выдерживают, а деньги экономить надо. Пожарный шлюз по резистам теперь как обычный (До этого резисты были как у укрепленной стены).
- fix: У инженеров в лоудауте теперь жилет с мультитулом, а не с конфигуратором.
- fix: Инженеры теперь не спавнятся с двумя поясами (один был на них из-за базового Gear, а второй из-за лоудаута в персонализации).

## Почему / Баланс
Печать - для админов, ибо функции кастомных печатей - нет
Имена боргов - ибо там были глупые, типа "Глава боргов" и прочая такая хуйня
Лоудаут - понятно
Пожарный шлюз невозможно было сломать большинством инструментов, а щас хоть по-человечески, как у обычного шлюза

**Ссылка на публикацию в Discord**
- [Предложения](https://discord.com/channels/901772674865455115/1298533959793377291)
- И личная инициатива

## Техническая информация
Всё просто

## Медиа
![image](https://github.com/user-attachments/assets/bc7b9c66-95de-4ca8-a8d1-c867a2bd8a87)
![image](https://github.com/user-attachments/assets/932f5c17-6223-46ca-a138-48b78c3e3ae4)

## Требования
- [x] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [x] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

## Критические изменения
None

**Чейнджлог**
:cl: eddiemercury
- add: NanoTrasen начала производить и поставлять на СЦК печать "ПЕРЕДЕЛАТЬ".
- add: На экран ожидания перед началом смены добавлен новый красивый тематический арт.
- add: плюшевый Джунгарик умеет кричать, издавать фразы и пищит при использовании.
- add: Мыши теперь умеют разговаривать на мышином, вместе с летучей мышью и Гамлетом.
- add: Выбор пояса или жилета в лоудауте есть теперь и у Бригадира. 
- remove: Руководство NanoTrasen во избежание нарушения трудового порядка запретило отправку боргов с глупыми или странными именами.
- tweak: Пожарный шлюз по резистам теперь как обычный (До этого резисты были как у укрепленной стены).
- fix: В лоудауте ИО в жилете теперь мультитул, а не конфигуратор.
- fix: Инженеры теперь не спавнятся с двумя поясами.

2024-11-03 22:54 UTC, KashRas2 submitted a review, later dismissed
Я великий злодей

2024-11-03 22:54 UTC, KashRas2 commented on Resources/Prototypes/Datasets/Names/borg.yml
> -  - Чинила
ВЕРНИ ЧЕНИЛУ

2024-11-03 22:54 UTC, KashRas2 commented on Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
> +  - type: LanguageSpeaker # Frontier
Приписку с фронтиром убери, она тут лишняя будто

2024-11-03 22:54 UTC, KashRas2 commented on Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
> +# ADT-Tweak-end
Если ты ему не добавил язык, то зачем убирал акцент?

2024-11-04 09:12 UTC, COTE-LAPYX commented
Я конечно не знаю наверняка как у вас там все прописано, но в ченджлог принято прописывать сами изменения, а не аргументацию и изменения .
То есть писать что ЦК решило что-то там как по мне не стоит, просто написать: изменёны резисты пожарных шлюзов 
При желании в скобках указать какие именно и с какого числа на какое 
Ибо читать ченджлоги ваши занимает больше времени чем нужно.

2024-11-04 11:10 UTC, Inconnu1337 requested changes
ъуъ

2024-11-04 11:10 UTC, Inconnu1337 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/rubber_stamp.ftl
> +ent-ADTRubberStampRemake = печать ПЕРЕДЕЛАТЬ
ВСЕ локали что ты сделал надо перенести в ADT

2024-11-04 11:10 UTC, Inconnu1337 commented on Resources/Prototypes/ADT/Loadouts/role_loadouts.yml
> +  - ADTEngineeringBelt # ADT-TWEAK
зачем тут комментарий если и так в ADT

2024-11-04 11:10 UTC, Inconnu1337 commented on Resources/Prototypes/Datasets/Names/borg.yml
> -  - Милаха-Бот
ВЕРНИ МИЛАХУ СУЧКА

2024-11-04 11:10 UTC, Inconnu1337 commented on Resources/Prototypes/Datasets/Names/borg.yml
> -  - Мистер Робист
ЕГО ТОЖЕ

2024-11-04 11:10 UTC, Inconnu1337 commented on Resources/Prototypes/Datasets/Names/borg.yml
> -  - Глава роботов
и его.

2024-11-04 11:10 UTC, Inconnu1337 commented on Resources/Prototypes/Datasets/Names/borg.yml
> +  - Сайбэл # ADT-Tweak
ебать ты насрал комментами
не проше было сделать
adt tweak start
adt tweak end

2024-11-04 11:10 UTC, Inconnu1337 commented on Resources/Prototypes/Entities/Objects/Misc/rubber_stamp.yml
> +  parent: RubberStampBaseAlt
в ADT

2024-11-04 11:24 UTC, Schrodinger71 commented
> Я конечно не знаю наверняка как у вас там все прописано, но в ченджлог принято прописывать сами изменения, а не аргументацию и изменения . То есть писать что ЦК решило что-то там как по мне не стоит, просто написать: изменёны резисты пожарных шлюзов При желании в скобках указать какие именно и с какого числа на какое Ибо читать ченджлоги ваши занимает больше времени чем нужно.

@COTE-LAPYX 

С одной стороны да, это было давно заведено мол РПЕшные чейнджлоги, чтобы читать было интересно, с другой у меня лимиты для отправкии сообщений упираеться, и не может нормально отправить в дис иногда

2024-11-04 11:33 UTC, COTE-LAPYX commented
> > Я конечно не знаю наверняка как у вас там все прописано, но в ченджлог принято прописывать сами изменения, а не аргументацию и изменения . То есть писать что ЦК решило что-то там как по мне не стоит, просто написать: изменёны резисты пожарных шлюзов При желании в скобках указать какие именно и с какого числа на какое Ибо читать ченджлоги ваши занимает больше времени чем нужно.
> 
> @COTE-LAPYX 
> 
> С одной стороны да, это было давно заведено мол РПЕшные чейнджлоги, чтобы читать было интересно, с другой у меня лимиты для отправкии сообщений упираеться, и не может нормально отправить в дис иногда


Если так хочется описывать по рп, то пусть делают это в описании пра а не в ченджлоге 

Ченджлоги буквально для того чтобы быстро прочитать изменения

2024-11-04 11:49 UTC, Schrodinger71 commented
> > > Я конечно не знаю наверняка как у вас там все прописано, но в ченджлог принято прописывать сами изменения, а не аргументацию и изменения . То есть писать что ЦК решило что-то там как по мне не стоит, просто написать: изменёны резисты пожарных шлюзов При желании в скобках указать какие именно и с какого числа на какое Ибо читать ченджлоги ваши занимает больше времени чем нужно.
> > 
> > 
> > @COTE-LAPYX
> > С одной стороны да, это было давно заведено мол РПЕшные чейнджлоги, чтобы читать было интересно, с другой у меня лимиты для отправкии сообщений упираеться, и не может нормально отправить в дис иногда
> 
> Если так хочется описывать по рп, то пусть делают это в описании пра а не в ченджлоге
> 
> Ченджлоги буквально для того чтобы быстро прочитать изменения

Пры не читают игроки

2024-11-04 12:01 UTC, COTE-LAPYX commented
> > > > Я конечно не знаю наверняка как у вас там все прописано, но в ченджлог принято прописывать сами изменения, а не аргументацию и изменения . То есть писать что ЦК решило что-то там как по мне не стоит, просто написать: изменёны резисты пожарных шлюзов При желании в скобках указать какие именно и с какого числа на какое Ибо читать ченджлоги ваши занимает больше времени чем нужно.
> > > 
> > > 
> > > @COTE-LAPYX
> > > С одной стороны да, это было давно заведено мол РПЕшные чейнджлоги, чтобы читать было интересно, с другой у меня лимиты для отправкии сообщений упираеться, и не может нормально отправить в дис иногда
> > 
> > Если так хочется описывать по рп, то пусть делают это в описании пра а не в ченджлоге
> > 
> > Ченджлоги буквально для того чтобы быстро прочитать изменения
> 
> Пры не читают игроки

Так разница не в том что игроки не читают а разрабы читают, а в том что больше уходит времени и приходится вчитываться что же было изменено такого 
Ну вот к примеру мне зачем читать что у шлюзов теперь меньше резистов потому-что так решило ЦК, вместо того чтобы прочитать - Уменьшены резисты пожарных шлюзов.

Ну ладно, я спорить не буду, если вам так удобно то пожалуйста.

2024-11-04 14:37 UTC, Inconnu1337 requested changes
какой же я злодей ХМХХААААЫЫАЫА

2024-11-04 14:37 UTC, Inconnu1337 commented on Resources/Locale/en-US/datasets/figurines.ftl
> +
удаляй

2024-11-04 14:40 UTC, Inconnu1337 approved these changes
меня зовут Inconnu и я ебланчик

2024-11-04 15:30 UTC, merged