Фиксы множества багов
AdventureTimeSS14/space_station_ADT pull request #737
Opened 2024-11-03 22:09 UTC by BitBoxxxer

## Описание PR
Исправление найденных ошибок игроками на сервере

## Почему / Баланс
Исправление ошибок для стабильной работы сервера, его контента
_и мне больно смотреть на то, сколько уже ошибок скопилось._

Я ДОДЕЛАЮ ПР ПОЗЖЕ, ИНАЧЕ Я УСНУ ЗА СТОЛОМ

## Медиа

## Требования

- [ ] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [ ] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

## Критические изменения

**Чейнджлог**

2024-11-04 18:09 UTC, Filokini commented
Что-то коментариев по типу # ADT tweak совсем нету.

2024-11-04 19:52 UTC, BitBoxxxer commented
> Что-то коментариев по типу # ADT tweak совсем нету.

добавлю под конечный коммит

2024-11-06 08:14 UTC, Bolper commented
> > Что-то коментариев по типу # ADT tweak совсем нету.
> 
> добавлю под конечный коммит

Лучше это делать сразу. А то можно забыть

2024-11-06 12:04 UTC, BitBoxxxer commented
> > > Что-то коментариев по типу # ADT tweak совсем нету.
> > 
> > 
> > добавлю под конечный коммит
> 
> Лучше это делать сразу. А то можно забыть

да, я была на столько занята конкретно кодом, что совсем забыла о комментах ADT, сейчас уже исправляюсь ахах

2024-11-06 16:33 UTC, Schrodinger71 requested changes

2024-11-06 16:33 UTC, Schrodinger71 commented on Content.Server/ADT/Power/Systems/BatteryDrinkerSystem.cs
> +            Text = Loc.GetString("Использовать бачок для зарядки"), // Позже разобраться с ссылками - лодаутами в C#
Вообще сразу бы сделать как надо

2024-11-06 16:36 UTC, Bolper commented on Content.Server/ADT/Power/Systems/BatteryDrinkerSystem.cs
> +            Text = Loc.GetString("Использовать бачок для зарядки"), // Позже разобраться с ссылками - лодаутами в C#
+

2024-11-06 16:41 UTC, Bolper commented on Resources/Prototypes/Entities/Objects/Misc/paper.yml
Это что такое?

2024-11-07 04:51 UTC, Bolper commented
> В общем я сделаю откат и оформлю нормально последние коммиты, чтобы не было огромного количества бесполезных коммитов.

Ути милаха
_pat pat  по голове_

2024-11-07 05:04 UTC, Schrodinger71 commented
> В общем я сделаю откат и оформлю нормально последние коммиты, чтобы не было огромного количества бесполезных коммитов.

Да какая разница, если они все в один превратятся

2024-11-07 08:56 UTC, BitBoxxxer commented
> > В общем я сделаю откат и оформлю нормально последние коммиты, чтобы не было огромного количества бесполезных коммитов.
> 
> Да какая разница, если они все в один превратятся

Красота, мне так спокойней

2024-11-07 11:04 UTC, BitBoxxxer commented
что за аномалия сломанная бехонкера

2024-11-07 15:53 UTC, closed without merging