Кассетный проигрыватель
AdventureTimeSS14/space_station_ADT pull request #742
Opened 2024-11-06 00:48 UTC by FaDeOkno

## Описание PR

Добавлен кассетный проигрыватель. Он позволяет записывать разговоры.
ура?

## Почему / Баланс

Иллюми попросил

**Ссылка на публикацию в Discord**

Всё, кроме поддержки барков и ТТСа, взято с https://github.com/space-wizards/space-station-14/pull/32234

## Техническая информация

ничего из существующего не менялось

## Медиа

## Требования

- [ ] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [ ] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

## Критические изменения

**Чейнджлог**

:cl: Котя
- add: Добавлен кассетный проигрыватель!

2024-11-06 18:29 UTC, Ratyyy requested changes

2024-11-06 18:29 UTC, Ratyyy commented on Resources/Audio/Items/Taperecorder/taperecorder_play.ogg
перенести в ADT, у нас такая папка и в аудио есть
так же и остальное аудио

2024-11-08 20:59 UTC, Ratyyy approved these changes
ну, лично я ничего больше не нашла. Ревью шарпа я не делала

2024-11-13 20:19 UTC, Schrodinger71 commented
@coderabbitai review

2024-11-13 20:22 UTC, Schrodinger71 commented
@coderabbitai summary

2024-11-15 12:17 UTC, KashRas2 approved these changes
Гойда

2024-11-15 12:19 UTC, merged