Маленькие 6 фикса
AdventureTimeSS14/space_station_ADT pull request #757
Opened 2024-11-07 14:33 UTC by BitBoxxxer

## Описание PR
Исправление найденных ошибок игроками на сервере

## Почему / Баланс
Исправление ошибок для стабильной работы сервера, его контента
_и мне больно смотреть на то, сколько уже ошибок скопилось._

_Заявки на исправления багов из дс:_

**Настенные зарядники:**
 https://discord.com/channels/901772674865455115/1301213459156832256
**Телескопический щит:**
https://discord.com/channels/901772674865455115/1302702427941765140
**Арбузный Ликёр:**
https://discord.com/channels/901772674865455115/1302358040854396982
**ЛКП Описание для КПБ:**
https://discord.com/channels/901772674865455115/1299006407776927875
**Переработка масок в переработчике мусора:**
https://discord.com/channels/901772674865455115/1302979512442818560
**Курсор на бумаге**
https://discord.com/channels/901772674865455115/1295021849830359132

## Медиа

![щит](https://github.com/user-attachments/assets/e694adbc-1a74-48c4-90fb-a1835d24b9ad)
![зарядник](https://github.com/user-attachments/assets/9848a1bf-b16c-4a87-b7d3-035b046f2c7c)
![ЛКП](https://github.com/user-attachments/assets/0852d105-3a9f-4c40-8922-cda8b1c1eb99)

## Требования

- [ДА] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [ДА] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

**Чейнджлог**

:cl: Kasey [Adnoda] Bitboxxer
- fix: Исправлен настенный зарядник для энергооружия + его расположение на стене
- fix: Телескопический щит теперь раздвигается
- fix: На обычной бумаге теперь тоже видно курсор
- fix: Исправлено описание Арбузного ликера
- fix: Исправлено ЛКП Описание для КПБ
- fix: Исправлено измельчение масок в переработчике мусора

2024-11-07 15:04 UTC, Bolper requested changes

2024-11-07 15:04 UTC, Bolper commented on Resources/Prototypes/Entities/Objects/Shields/shields.yml
> +    - type: PointLight
День комментариев))

2024-11-07 15:04 UTC, Bolper commented on Resources/Prototypes/Entities/Structures/Power/chargers.yml
> +  placement:
и тут тоже))

2024-11-07 15:05 UTC, BitBoxxxer commented on Resources/Prototypes/Entities/Structures/Power/chargers.yml
> +  placement:
у меня код не работает, я не понимаю в чем проблемааа >:(

2024-11-07 19:04 UTC, Bolper commented on Resources/Locale/ru-RU/ADT/Interaction/fast-hide-popups.ftl
> +battery-drinker-verb-drink = Использовать аккумулятор для зарядки.
Прости. Но я слишком много думал над названием файла куда ты это пихнула, и я заметил, что в названии присутсвует слово hide, в штуках выше тоже используется hide, и это все относиться к каким то пряткам. Так что я думаю не туда. И да, как я помню popups - всплывающие надписи над персонажем.

2024-11-07 19:08 UTC, BitBoxxxer commented on Resources/Locale/ru-RU/ADT/Interaction/fast-hide-popups.ftl
> +battery-drinker-verb-drink = Использовать аккумулятор для зарядки.
Я запихнула эти строчки в папку Interaction -- Взаимодействия, файл наверное да, подобран не совсем верно.
Вопрос тогда к кому переписывать эти строки ?

2024-11-08 05:15 UTC, BitBoxxxer commented on Resources/Locale/ru-RU/ADT/Interaction/fast-hide-popups.ftl
> +battery-drinker-verb-drink = Использовать аккумулятор для зарядки.
Так, в общем это перевод для взаимодействий игрока с окружением, а не перевод вещей -- clothing или предметов -- типа object, так что все хорошо.

2024-11-08 16:04 UTC, Filokini commented on Resources/Locale/ru-RU/ADT/Interaction/fast-hide-popups.ftl
> +battery-drinker-verb-drink = Использовать аккумулятор для зарядки.
Лучше будет создать новую ftl по пути
Resources/Locale/ru-RU/ADT/Interaction/interaction-system.ftl

2024-11-08 16:04 UTC, Filokini commented on Resources/Locale/ru-RU/ADT/Interaction/fast-hide-popups.ftl
> +battery-drinker-verb-drink = Использовать аккумулятор для зарядки.
Лучше будет создать новую ftl по пути
Resources/Locale/ru-RU/ADT/Interaction/interaction-system.ftl

2024-11-08 16:05 UTC, Filokini commented on Resources/Locale/ru-RU/ADT/Interaction/fast-hide-popups.ftl
> +battery-drinker-verb-drink = Использовать аккумулятор для зарядки.
далее туда уже засунуть это, просто в попапы это точно закидывать не нужно

2024-11-08 16:45 UTC, Bolper approved these changes

2024-11-08 16:46 UTC, merged