Rerev
AdventureTimeSS14/space_station_ADT pull request #766
Opened 2024-11-08 22:12 UTC by Ratyyy

## Описание PR

полностью переделала революцию 
## Почему / Баланс

весельн.
**Ссылка на публикацию в Discord**

## Медиа

## Требования

- [X] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [ ] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

## Критические изменения

**Чейнджлог**

:cl: Ratyyy
- add: На станциях НТ резко повысилось количество революций!
- add: НТ провело тренинги, как сопротивляться воздействию гипноза!
- add: Главам революции начали выдавать собственные ящики со снаряжением!

2024-11-08 23:14 UTC, Inconnu1337 commented
Вот бы кто то писал в описании что конкретно было добавлено или изменено

2024-11-09 11:14 UTC, KashRas2 requested changes
Немного посмотрел

2024-11-09 11:14 UTC, KashRas2 commented on Resources/Locale/ru-RU/ADT/Objects/Tools/emag.ftl
> +    .desc = Выглядит как айди карта, к котрой привязали мультитул, бумагу, а так же ещё несколько инструментов. Вам кажется, оно чем-то похоже на криптографический ключ. Пахнет довольно красновато.
Лучше убрать метаописание.

2024-11-09 11:14 UTC, KashRas2 commented on Resources/Locale/ru-RU/ADT/revolution/toolbox.ftl
> +    Для любителей хакинга, ИИ, боргов а так же троллiiн2а
лучше заменить последнее слово на что-то более благозвучное

2024-11-09 11:14 UTC, KashRas2 commented on Content.Server/GameTicking/Rules/RevolutionaryRuleSystem.cs
> +    ///ADT rerev end
/// - это не комментарий. Ну, как бы да, но его обычно используют для создания документации. Так что лучше заменить на двойной слэш.

2024-11-09 11:14 UTC, KashRas2 commented on Content.Server/GameTicking/Rules/RevolutionaryRuleSystem.cs
> +        ///ADT rerev end
Аналогично

2024-11-09 11:14 UTC, KashRas2 commented on Content.Shared/Revolutionary/Components/HeadRevolutionaryComponent.cs
> +/// ADT rerev end
Аналогично

2024-11-09 11:14 UTC, KashRas2 commented on Content.Server/GameTicking/Rules/RevolutionaryRuleSystem.cs
> +                comp.ConvertedCount++; ///ADT rerev end
Тоже самое.

2024-11-09 12:12 UTC, Ratyyy commented on Resources/Locale/ru-RU/ADT/revolution/toolbox.ftl
> +    Для любителей хакинга, ИИ, боргов а так же троллiiн2а
было бы хорошо, однако по другому не дать нужную отсылку

2024-11-09 16:42 UTC, KashRas2 approved these changes

2024-11-09 21:52 UTC, merged