184-ый коммит из старой сборки
AdventureTimeSS14/space_station_ADT pull request #769
Opened 2024-11-09 11:53 UTC by BitBoxxxer

## Описание PR
### НОВЫЙ 2025 ГОД !!! Вещи из старой сборки

_Добавлено: Уголь, игрушечные c4 + упакованная версия_

## Почему / Баланс
_Новый год, надо помочь перенести контент
Заказ из дс:_
https://discord.com/channels/901772674865455115/1304149766242046042

## Медиа

**(Пока в разработке, нет всех обнов для НГ)**
![ураураура2025](https://github.com/user-attachments/assets/7a474294-a872-4a9f-96c1-bad09f3fcc5e)

## Требования

- [ДА] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [ДА] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

**Чейнджлог**

:cl: Kasey [Adnoda] Bitboxxer
- add: Добавлены вещи для Нового Года :)

2024-11-09 13:53 UTC, Schrodinger71 requested changes

2024-11-09 13:53 UTC, Schrodinger71 commented on Resources/Prototypes/ADT/Entities/Objects/Fun/toys.yml
> +# Новый год
Ниттуда... ![Screenshot_20241109_165205.jpg](https://github.com/user-attachments/assets/4a638dbc-4dc9-4240-a1ac-6865a95c746a)

Я ж говорил по yml
Тьфу Труд

2024-11-09 13:54 UTC, BitBoxxxer commented on Resources/Prototypes/ADT/Entities/Objects/Fun/toys.yml
> +# Новый год
А блин, сорян Шредя, исправлю🙏

2024-11-09 14:58 UTC, Schrodinger71 commented on Resources/Prototypes/ADT/Entities/Objects/Fun/toys.yml
> +# Новый год
;w;

2024-11-14 19:40 UTC, BitBoxxxer commented
> Important
> 
> ## Review skipped
> Auto reviews are disabled on this repository.
> 
> Please check the settings in the CodeRabbit UI or the `.coderabbit.yaml` file in this repository. To trigger a single review, invoke the `@coderabbitai review` command.
> 
> You can disable this status message by setting the `reviews.review_status` to `false` in the CodeRabbit configuration file.
> 
> Thank you for using CodeRabbit. We offer it for free to the OSS community and would appreciate your support in helping us grow. If you find it useful, would you consider giving us a shout-out on your favorite social media?
> 
> ❤️ Share
> 🪧 Tips

ИЗЫЙДИ ДЕМОН ИЗ МОЕГО ПУЛЛА

2024-11-19 19:17 UTC, BitBoxxxer commented on Resources/Locale/ru-RU/ADT/ADTGlobalEvents/NewYears/Clothing/Head/masks.ftl
> +    .desc = Пушистая шапочка Деда Мороза - волшебника, придуманного Землянинами. Кажется сзади виднеется веревочка, соединяющая шапочку с бородой...
Да) Слово специально так написано, но могу изменить, если есть такая потребность

2024-11-20 05:59 UTC, BitBoxxxer commented
Теперь придется исправлять грамматические ошибки.... 😍😋 LETS GOOOOO

2024-11-20 06:01 UTC, BitBoxxxer commented on Resources/Locale/ru-RU/ADT/ADTGlobalEvents/NewYears/Clothing/Head/masks.ftl
> +    .desc = Пушистая шапочка Деда Мороза - волшебника, придуманного Землянинами. Кажется сзади виднеется веревочка, соединяющая шапочку с бородой...
В общем исправляю на землянами, чтобы потом не придирались за "ошибку"

2024-11-20 06:06 UTC, BitBoxxxer commented on Resources/Locale/ru-RU/ADT/ADTGlobalEvents/NewYears/Objects/Structures/christmas_tree.ftl
> +    .suffix = Новый Год
А смысл их ставить ? Суффикс так или иначе будет работать

2024-11-20 06:08 UTC, BitBoxxxer commented on Resources/Locale/ru-RU/ADT/ADTGlobalEvents/NewYears/Structures/Wallmount/Signs/posters.ftl
> +    .suffix = Новый Год
Суффикс нужен, чтобы позже было легче искать код для событий ?? Как Новый Год ?

2024-11-20 13:51 UTC, BitBoxxxer commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Consumable/Drinks/drinks.ftl
> +    .desc = { "бодрящий и вкусный способ начать рабочий день" }
Я как поняла нет разницы между использования скобок ( { " " } ) и простого написания. Метод с скобками использовался наверное, когда визарды только - только вводить начали локалы

2024-11-20 13:56 UTC, BitBoxxxer commented on Resources/Locale/ru-RU/ADT/ADTGlobalEvents/NewYears/Structures/Wallmount/Signs/posters.ftl
> +    .suffix = Новый Год
Скобки - не нужны, все и без них прекрасно работает
![Снимок экрана 2024-11-20 185616](https://github.com/user-attachments/assets/139d6dcf-5bf5-4b38-8629-72fc607de785)

2024-11-20 13:57 UTC, BitBoxxxer commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Consumable/Drinks/drinks.ftl
> +    .suffix = { "" }
Суффикс будет

2024-11-20 13:59 UTC, BitBoxxxer commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Fun/toys.ftl
> +    .desc = Это ЖУТКИЙ МЕСЯЦ!
Это не на НГ... Вроде как вообще для Хеллоуина было

2024-11-20 14:23 UTC, BitBoxxxer commented on Resources/Locale/ru-RU/ADT/ADTGlobalEvents/NewYears/Clothing/Underwear/underwear.ftl
> +    .desc = Специально для хождения по леденным шахтам помошникам санты.
> @BitBoxxxer ты не исправила, вроде..

![исправлено](https://github.com/user-attachments/assets/eab59d72-f955-455d-af88-2f4f74892a6c)
Неа, исправила

2024-11-20 15:30 UTC, BitBoxxxer commented
> Ревью локали окончен - Kasey, ты умничка, было приятно с тобой работать ![хомик](https://private-user-images.githubusercontent.com/145219878/388157433-3ee878bd-590e-4ffd-b492-b6f8dfa5bf8d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMTY4ODIsIm5iZiI6MTczMjExNjU4MiwicGF0aCI6Ii8xNDUyMTk4NzgvMzg4MTU3NDMzLTNlZTg3OGJkLTU5MGUtNGZmZC1iNDkyLWI2ZjhkZmE1YmY4ZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQxNTI5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWVlNmQ0Y2RmNGE3YjA5ZDFjOWM1YzY3MGNlYmQzOWVlZjM3NTlkM2RjYjkwOGNhMDdmMWEzM2JlMmZhNjU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iIWgomvOtpbjjwaq0IENk_0LxwN7S0CvkxoEAuYMqow) [ ![хомик](https://private-user-images.githubusercontent.com/145219878/388157433-3ee878bd-590e-4ffd-b492-b6f8dfa5bf8d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMTY4ODIsIm5iZiI6MTczMjExNjU4MiwicGF0aCI6Ii8xNDUyMTk4NzgvMzg4MTU3NDMzLTNlZTg3OGJkLTU5MGUtNGZmZC1iNDkyLWI2ZjhkZmE1YmY4ZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQxNTI5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWVlNmQ0Y2RmNGE3YjA5ZDFjOWM1YzY3MGNlYmQzOWVlZjM3NTlkM2RjYjkwOGNhMDdmMWEzM2JlMmZhNjU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iIWgomvOtpbjjwaq0IENk_0LxwN7S0CvkxoEAuYMqow) ](https://private-user-images.githubusercontent.com/145219878/388157433-3ee878bd-590e-4ffd-b492-b6f8dfa5bf8d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMTY4ODIsIm5iZiI6MTczMjExNjU4MiwicGF0aCI6Ii8xNDUyMTk4NzgvMzg4MTU3NDMzLTNlZTg3OGJkLTU5MGUtNGZmZC1iNDkyLWI2ZjhkZmE1YmY4ZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQxNTI5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWVlNmQ0Y2RmNGE3YjA5ZDFjOWM1YzY3MGNlYmQzOWVlZjM3NTlkM2RjYjkwOGNhMDdmMWEzM2JlMmZhNjU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iIWgomvOtpbjjwaq0IENk_0LxwN7S0CvkxoEAuYMqow) [ ](https://private-user-images.githubusercontent.com/145219878/388157433-3ee878bd-590e-4ffd-b492-b6f8dfa5bf8d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMTY4ODIsIm5iZiI6MTczMjExNjU4MiwicGF0aCI6Ii8xNDUyMTk4NzgvMzg4MTU3NDMzLTNlZTg3OGJkLTU5MGUtNGZmZC1iNDkyLWI2ZjhkZmE1YmY4ZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQxNTI5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWVlNmQ0Y2RmNGE3YjA5ZDFjOWM1YzY3MGNlYmQzOWVlZjM3NTlkM2RjYjkwOGNhMDdmMWEzM2JlMmZhNjU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iIWgomvOtpbjjwaq0IENk_0LxwN7S0CvkxoEAuYMqow)

Шпащиба <3

2024-11-20 15:54 UTC, merged