Фикс и добавление элементов внешности для вульп
AdventureTimeSS14/space_station_ADT pull request #770
Opened 2024-11-09 18:05 UTC by sh4zik

## Описание PR
Фиксы и добавление внешности для вульп

## Почему / Баланс
Большинство элементов внешности были в основном сломанные, но данный фикс увеличивает количество доступной кастомизации немного больше

## Требования

- [x] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [x] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

**Чейнджлог**

:cl: Sh4zik
- add: Были добавлены несколько новых элементов внешности
- fix:  Были исправлены большинство сломанных элементов внешности

2024-11-09 18:07 UTC, Schrodinger71 commented on .gitignore
> +Resources/Textures/ADT/Mobs/Customization/Vulpkanin/vulpkanin_tail.rsi/tail_m_wagging.png
Это зачем?

2024-11-09 18:07 UTC, Schrodinger71 commented on .gitignore
> +Resources/Textures/ADT/Mobs/Customization/Vulpkanin/vulpkanin_tail.rsi/tail_m_wagging.png
а

2024-11-09 18:12 UTC, sh4zik commented on .gitignore
> +Resources/Textures/ADT/Mobs/Customization/Vulpkanin/vulpkanin_tail.rsi/tail_m_wagging.png
А это я скачал гитхаб десктоп, и ещё не разобрался в нём

2024-11-09 18:12 UTC, Bolper commented on .gitignore
> +Resources/Textures/ADT/Mobs/Customization/Vulpkanin/vulpkanin_tail.rsi/tail_m_wagging.png
а зачем качал...

2024-11-09 18:21 UTC, sh4zik commented on .gitignore
> +Resources/Textures/ADT/Mobs/Customization/Vulpkanin/vulpkanin_tail.rsi/tail_m_wagging.png
Мне порекомендовали..

2024-11-09 20:26 UTC, sh4zik commented
![sisiphys (1)](https://github.com/user-attachments/assets/071ea452-d8f0-4683-9e20-66fa7c17a10a)

2024-11-13 21:17 UTC, Schrodinger71 requested changes

2024-11-13 21:17 UTC, Schrodinger71 commented on .gitignore
> -## files generated by popular Visual Studio add-ons.
не удаляй этот файл...

2024-11-16 16:17 UTC, BitBoxxxer commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Mobs/Customization/Markings/vulpkanin.ftl
> +ADTVulpkaninold = Скулы 1
нету суффикса marking- у: ADTVulpkaninoldchin && ADTVulpkaninold
допиши как:
1) marking-ADTVulpkaninoldchin
2) marking-ADTVulpkaninold

2024-11-16 16:42 UTC, BitBoxxxer requested changes
для ревью

2024-11-16 16:55 UTC, sh4zik commented
> для ревью

Готово. Лишь жалуется тут на что-то.. но не в плане кода, и то хорошо

2024-11-16 16:59 UTC, BitBoxxxer commented
> > для ревью
> 
> Готово. Лишь жалуется тут на что-то.. но не в плане кода, и то хорошо

Надо исправлять, сейчас тоже посмотрю в чем может быть проблема.

2024-11-16 17:29 UTC, sh4zik commented
> > > для ревью
> > 
> > 
> > Готово. Лишь жалуется тут на что-то.. но не в плане кода, и то хорошо
> 
> Надо исправлять, сейчас тоже посмотрю в чем может быть проблема.

Ну, Как я понял, Данная проблема заключается в самом гитхабе, и в статусах самого ПР`а, А самих проблем нету..

2024-11-16 17:37 UTC, BitBoxxxer commented
> > > > для ревью
> > > 
> > > 
> > > Готово. Лишь жалуется тут на что-то.. но не в плане кода, и то хорошо
> > 
> > 
> > Надо исправлять, сейчас тоже посмотрю в чем может быть проблема.
> 
> Ну, Как я понял, Данная проблема заключается в самом гитхабе, и в статусах самого ПР`а, А самих проблем нету..

Да, ошибок нет в консолях ни клиента, ни сервера.. Но она же появилась после коммита, значит с ним возможно какая то проблема. Можно сделать откат и посмотреть

2024-11-16 18:57 UTC, sh4zik commented
Я не знаю как, Но я его починил, Победа. Победа..

2024-11-17 17:39 UTC, BitBoxxxer commented
> Я не знаю как, Но я его починил, Победа. Победа..

Молодец))

2024-11-17 17:40 UTC, BitBoxxxer approved these changes

2024-11-17 17:46 UTC, merged