базовые стены и диагональные обычные
AdventureTimeSS14/space_station_ADT pull request #778
Opened 2024-11-11 01:36 UTC by PyotrIgn

## Описание PR
Добавление структур для корабельных боев

## Почему / Баланс
Потому что нужно строить шаттлы

:cl:
- add: Добавлены структуры для корабельных боев

2024-11-16 19:04 UTC, Schrodinger71 requested changes

2024-11-16 19:04 UTC, Schrodinger71 commented on Resources/Prototypes/ADT/ShipbattleEvent/Entities/Structures/Walls/walls.yml
> +#Базовые стены
![image](https://github.com/user-attachments/assets/d47baa15-917f-4e7d-aada-2179d4cca97e)
![image](https://github.com/user-attachments/assets/43b1eb51-b5d7-4d55-b722-a6fc4240d971)

`Resources/Prototypes/ADT/ShipbattleEvent/Entities/Structures/Walls/walls.yml`
этот файл сюда:
`Resources/Prototypes/ADT/ADTGlobalEventsShipbattleEvent/Entities/Structures/Walls/walls.yml`

в этой же папке /ADTGlobalEvents/ поместили новый год /NewYears/

2024-11-17 19:32 UTC, PyotrIgn commented on Resources/Prototypes/ADT/ShipbattleEvent/Entities/Structures/Walls/walls.yml
> +#Базовые стены
Сделал

2024-11-17 19:33 UTC, Schrodinger71 approved these changes
Гуд

2024-11-28 21:06 UTC, merged