[DRAFT, PORT] Attachments
AdventureTimeSS14/space_station_ADT pull request #784
Opened 2024-11-13 20:51 UTC by Inconnu1337

## Описание PR

## Почему / Баланс

**Ссылка на публикацию в Discord**

## Техническая информация

## Медиа

## Требования

- [ ] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [ ] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

## Критические изменения

**Чейнджлог**

2024-11-13 20:51 UTC, Inconnu1337 commented
@coderabbitai summary

2024-11-13 20:51 UTC, Inconnu1337 commented
@coderabbitai summary

2024-11-13 20:52 UTC, Inconnu1337 commented
@coderabbitai help

2024-11-13 20:54 UTC, Schrodinger71 commented
дохера файлов

2024-11-13 20:55 UTC, Inconnu1337 commented
ДА ТЫ АХУЕЛ АХХАХА

2024-11-22 15:38 UTC, Schrodinger71 commented on Content.Client/Weapons/Melee/MeleeWeaponSystem.cs
> -
Удалённые изменения никак не отмечены

2024-11-22 15:38 UTC, Schrodinger71 commented on Content.Client/Weapons/Melee/MeleeWeaponSystem.cs
Новое никак не отметил

2024-11-22 15:38 UTC, Schrodinger71 commented on Content.Client/Weapons/Melee/MeleeWeaponSystem.cs
> -                return;
Тож удалил и никак не отметил, наверное лучше просто комментить

2024-11-22 15:38 UTC, Schrodinger71 commented on Content.Client/Weapons/Melee/MeleeWeaponSystem.cs
> +                ClientDisarm(entity, mousePos, coordinates);
ни подписано

2024-11-22 15:38 UTC, Schrodinger71 commented on Content.Client/Weapons/Melee/MeleeWeaponSystem.cs
> -            RaisePredictiveEvent(new LightAttackEvent(GetNetEntity(target), GetNetEntity(weaponUid), GetNetCoordinates(coordinates)));
Тоже самое, не отмечено

2024-11-22 15:38 UTC, Schrodinger71 commented on Content.Client/Weapons/Melee/MeleeWeaponSystem.cs
> +            ClientLightAttack(entity, mousePos, coordinates, weaponUid, weapon);
подписать

2024-11-22 15:38 UTC, Schrodinger71 commented on Content.Client/Weapons/Melee/MeleeWeaponSystem.cs
Ни подписано

2024-11-22 15:38 UTC, Schrodinger71 commented on Content.Client/Weapons/Melee/MeleeWeaponSystem.cs
> +    public void ClientHeavyAttack(EntityUid user, EntityCoordinates coordinates, EntityUid meleeUid, MeleeWeaponComponent component)
ни подписано

2024-11-22 15:54 UTC, Inconnu1337 commented on runclient.bat
> +pause
мяу

2024-11-29 20:04 UTC, KashRas2 submitted a review, later dismissed
![-1.gif](https://github.com/user-attachments/assets/05cf7647-5d2d-49f3-b37c-cbbccf5f7ac1)

2024-12-14 23:01 UTC, FaDeOkno requested changes
Чиним баги.

2024-12-18 13:47 UTC, merged