Мультифазовый пистолет ГСБ
AdventureTimeSS14/space_station_ADT pull request #802
Opened 2024-11-19 06:36 UTC by Filokini

Со старой сборки перенесён мультифазовый пистолет ГСБ и починил выдачу цели на мобильный дефиб
:cl:
- add: ГСБ получил мультифазовый пистолет с тремя режимами стрельбы.
- fix: Синдикат прознал про мобильный дефибриллятор ГВ и уже раздают цели на его кражу.

2024-11-27 18:58 UTC, Darkiich reviewed
Так

2024-11-27 19:14 UTC, Darkiich requested changes
ревью

2024-11-27 19:14 UTC, Darkiich commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +#    - HighRiskItem
А это для чего?

2024-11-27 23:07 UTC, Filokini commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Weapons/Guns/Battery/battery_gun.ftl
> +ent-ADTWeaponPistolX01 = X-01 М.Э.П.
Я делал пути как у корваха, не думаю что стоит переносить туда куда ты говоришь, да и вообще эту фтлку надо разобрать по таким же папкам.

2024-11-27 23:08 UTC, Filokini commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +#    - HighRiskItem
Убираем хайриск дробовик

2024-11-28 07:22 UTC, Bolper commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +#    - HighRiskItem
Если ты не видел. То дробовики эти уже можно покупать в карго с этим  пром станет как я посмотрел. Так что да. Хайриск убираем

2024-11-28 07:23 UTC, Bolper commented
Кстати по этом. Почему описание пра не описывает всё изменения. Почему я не вижу про дробовики в карго

2024-11-28 08:18 UTC, Filokini commented
Забыл потому что

2024-11-28 08:21 UTC, Filokini commented
Забыл потому что, и еще как дома буду, ослаблю его, а то мне он кажется сильным для закупа.

2024-11-29 07:35 UTC, Darkiich approved these changes
Да

2024-11-29 14:21 UTC, merged