Я же хотел просто починить генокрада...
AdventureTimeSS14/space_station_ADT pull request #820
Opened 2024-11-21 22:38 UTC by FaDeOkno

## Описание PR

Вырезаны изменения в ActionContainerSystem, из-за которых ломалась нарколепсия
В торгоматах теперь можно выбрать количество покупаемого товара

## Почему / Баланс

Нарколепсия - баг
Торгоматы - да

**Ссылка на публикацию в Discord**

- [Баги](https://discord.com/channels/901772674865455115/1307275441555378177)

## Техническая информация

Класс `VendorItemsListData` теперь содержит в себе `VendingMachineInventoryEntry`, используемый для класса `GenerateButton()` в `VendingMachineMenu`
Использование Action `OnItemSelected` закомменчен в `VendingMachineBoundUserInterface`. Поэтому класс `VendingMachineEjectMessage` больше не используется. Вместо них добавились Action `OnItemCountSelected` и `VendingMachineEjectCountMessage` соответственно

## Медиа

![image](https://github.com/user-attachments/assets/8ceff456-b821-40d6-89a4-ebcc6d51719a)

## Требования

- [ ] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [ ] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

## Критические изменения

Во многих функциях `VendingMachineSystem` была добавлена переменная `count`, обозначающая число извлекаемых объектов.
Класс `VendingMachineEjectMessage`, и, следовательно, функция `OnInventoryEjectMessage()` больше не используются. Используйте `VendingMachineEjectCountMessage` и `OnInventoryEjectCountMessage()`
Файл VendingMachineItem.xaml был сильно видоизменён. В случае изменения UI торгоматов от официалов тыкайте меня

**Чейнджлог**

:cl: Котя
- add: Теперь в торгоматах можно купить несколько штук товара сразу
- fix: Злосчастный баг с нарколепсией исправлен. Доброе утро, сони

2024-11-22 21:05 UTC, KashRas2 requested changes
Генокрада отдельно посмотрю ещё.

2024-11-22 21:05 UTC, KashRas2 commented on Resources/Locale/ru-RU/store/store.ftl
> +vending-machine-ui-buy-button-text = Купить
Это можно и к нам запихнуть. Создать аналогичный файл и все.

2024-11-22 21:05 UTC, KashRas2 commented on Content.Client/VendingMachines/VendingMachineBoundUserInterface.cs
> +            _menu.OnItemCountSelected += OnItemSelected;    // ADT vending eject count
Не проще ли просто предыдущую строку на эту поменять?

2024-11-22 21:05 UTC, KashRas2 commented on Content.Client/VendingMachines/VendingMachineBoundUserInterface.cs
> +            _menu.OnItemCountSelected -= OnItemSelected;    // ADT vending eject count
Аналогично тому, что я сказал выше.

2024-11-22 21:53 UTC, Mirokko requested changes
В целом всё ок, но я не тестировал. Единственный момент отписал.

2024-11-22 21:53 UTC, Mirokko commented on Content.Server/ADT/Changeling/Systems/ChangelingSystem.cs
> +        var newLingComponent = new ChangelingComponent();
Я бы воспользовался IComponentFactory, методом GetComponent.

2024-11-22 21:57 UTC, Mirokko commented on Content.Client/VendingMachines/UI/VendingMachineMenu.xaml.cs
> +        // /// <summary>
Наш коммент

2024-11-22 21:58 UTC, FaDeOkno commented on Content.Server/ADT/Changeling/Systems/ChangelingSystem.cs
> +        var newLingComponent = new ChangelingComponent();
Не думаю, что тут это уместно будет. Генокрад же при превращении должен передавать информацию с прошлого компонента на новый

2024-11-22 22:03 UTC, Mirokko commented on Content.Client/VendingMachines/UI/VendingMachineMenu.xaml.cs
> +        public double PriceMultiplier = 1;  // ADT vending eject count
Я не очень понял нахера тебе эта переменная. У тебя цена НОЛЬ. Ноль ты умножаешь на любое число и будет ноль. Но может я что-то упускаю...

2024-11-22 22:13 UTC, FaDeOkno commented on Content.Client/VendingMachines/UI/VendingMachineMenu.xaml.cs
> +        public double PriceMultiplier = 1;  // ADT vending eject count
Нет, цена не ноль. Это модификатор цены, он берётся из компонента и присваивается здесь. Иного способа его использовать я, увы, не нашёл

2024-11-22 22:15 UTC, KashRas2 commented on Content.Client/VendingMachines/UI/VendingMachineMenu.xaml.cs
> +        public double PriceMultiplier = 1;  // ADT vending eject count
Эта переменная отвечает за "наценку" на товар. А сама цена не равна нулю. Тут 2 цены существует: из клиента и из сервера. Из клиента это то, что игрок видит, а из сервера то, что сервер видит. Просто нельзя их вместе сделать, так как цена и наценка существуют раздельно, а также это нужно для 0 цены на товарах.

2024-11-23 18:53 UTC, FaDeOkno commented on Content.Server/ADT/Changeling/Systems/ChangelingSystem.cs
> +        var newLingComponent = new ChangelingComponent();
Я даже пытался использовать сериализацию, но нет
Единственный способ скопировать компонент генокрада, что работает - так

2024-11-24 08:57 UTC, KashRas2 approved these changes

2024-11-25 19:49 UTC, merged