[TWEAK] Много разных изменений
AdventureTimeSS14/space_station_ADT pull request #828
Opened 2024-11-24 18:09 UTC by jungarikjan

## Описание PR
Небольшие изменения:
- Ботинки ниндзя теперь бесшумные
- Пун Пун, слайм РНД, боксёр-кенгуру, Гамлет теперь имеют таймер общего наигранного времени в 2ч (против набегеров)
- Подкрепления Синдиката и СолоЯО теперь имеют таймер общего наигранного времени в 2ч (против набегаторов)
- Скелет и ниндзя теперь имеют таймер общего наигранного времени в 2ч (против набегеров и новичков)
- Мехи умеют вскрывать незапитанные шлюзы
- Добавлены расширенные правила антагонистов: Дракон, Одинокий ЯО, Ниндзя, Скелет из шкафа, а также подкорректированы некоторые другие.
- Гайд на Еретика перенесен во вкладку антаги
- Время на еретика - 75ч общего времени
- Вколоть шприц другому - 6 сек вместо 5. Себе, соответственно, 3 сек вместо 2.5
- Съесть таблетку самому - 0.3 сек вместо 1. Другому скормить так и осталось 1 сек

## Почему / Баланс
Потому что ниндзя палили метаеберы + он ниндзя, а соответственно двигаться должен бесшумно.
За Пуна и остальных заходили набегеры после смерти и грифили
Для удобства игроков. Пусть они могут вскрывать незапитанные шлюзы, хуле. А то нелогично

**Ссылка на публикацию в Discord**
- [Предложения](https://discord.com/channels/901772674865455115/1308902934721069076)

## Техническая информация
Всё достаточно просто

## Медиа
Не требуется

## Требования
- [Х] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [Х] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

## Критические изменения
Не имеются

**Чейнджлог**
:cl: eddiemercury
- add: Добавлены расширенные правила антагонистов: Дракон, Одинокий ЯО, Ниндзя, Скелет из шкафа, а также подкорректированы некоторые другие.
- add: Добавлен перевод названия и описания гост-роли космокарпа
- add: Время на Еретика - 75 часов общего времени, как у генокрада
- tweak: Пун Пун, слайм РНД, боксёр-кенгуру, Гамлет, Скелеты, Ниндзя, Подкрепы ЯО и СолоЯО теперь имеют таймер общего наигранного времени в 2ч (против набегаторов)
- tweak: Мехи теперь умеют вскрывать незапитанные шлюзы
- tweak: Ботинки ниндзя теперь бесшумные (против метаеберов и + логика)
- tweak: Гайд на еретика перенесен во вкладку "антагонисты"
- tweak: Вколоть шприц другому - 6 сек вместо 5. Себе, соответственно, 3 сек вместо 2.5
- tweak: Съесть таблетку самому - 0.3 сек вместо 1. Другому скормить так и осталось 1 сек

2024-11-25 19:26 UTC, Darkiich commented on Resources/Prototypes/Guidebook/antagonist.yml
> +  name: guide-entry-heretics
Хм. Даже не знаю, надо ли это убирать из папки ADT и переносить в не наши дебри

2024-11-25 19:27 UTC, Darkiich commented on Resources/ServerInfo/Guidebook/Antagonist/Heretics.xml
С этим точно также

2024-11-25 19:29 UTC, Darkiich requested changes
Ревью

2024-11-26 21:29 UTC, merged

2024-11-27 12:03 UTC, COTE-LAPYX commented
У вас тут 1 тест не прошёл так-то...