[Admin, Discord] Добавление вебхука для админ-чата
AdventureTimeSS14/space_station_ADT pull request #835
Opened 2024-11-26 10:44 UTC by Schrodinger71

## Описание PR
Теперь сообщения из админ-чата будут автоматически пересылаться в указанный канал Discord через вебхук. Также добавлена функциональность для уведомлений о входе/выходе администраторов, а также изменении их прав(снятии или возращении).

## Почему / Баланс
Эти изменения были добавлены для улучшения коммуникации между администраторами и для более эффективного мониторинга действий в игре ***старшей администрацией***. Уведомления о действиях администраторов в реальном времени помогут команде быстро реагировать на изменения, связанные с правами и активностью администраторов.

## Техническая информация
Добавлена логика для отправки сообщений из админ-чата в Discord через вебхук, если URL вебхука настроен. Включены дополнительные уведомления о входе, выходе администраторов, а также изменениях в их правах. Это реализовано с помощью API Discord и использования webhook.

## Медиа
![image](https://github.com/user-attachments/assets/a135bc10-46e9-4281-bb22-83ca69513db1)

## Требования
- [x] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [x] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

## Критические изменения
Не выявлено критических изменений. Новый функционал не нарушает текущую логику работы системы.

**Чейнджлог**
no cl, no fun

2024-11-26 10:54 UTC, FaDeOkno commented
О
А сможешь так же прикрутить оповещения об обновах к дискорду?

2024-11-26 10:56 UTC, Schrodinger71 commented
попробую найти это

2024-11-26 14:23 UTC, FaDeOkno requested changes
КОММЕНТАРИИ

2024-11-26 14:23 UTC, FaDeOkno commented on Content.Server/Administration/Managers/AdminManager.cs
> +                    Content = $"**ОПОВЕЩЕНИЕ: Админ ВЫШЕЛ {senderName}**"
Зачем тут капс?

2024-11-26 14:23 UTC, FaDeOkno commented on Content.Server/Chat/Managers/ChatManager.cs
> +        }
Комментарии

2024-11-26 14:23 UTC, FaDeOkno commented on Content.Server/Chat/Managers/ChatManager.cs
> +    private async void SendAdminChat(ICommonSession player, string message)
Комментарии

2024-11-26 14:23 UTC, FaDeOkno commented on Content.Server/Administration/Managers/AdminManager.cs
> +            }
Комментарии

2024-11-26 14:23 UTC, FaDeOkno commented on Content.Server/Administration/Managers/AdminManager.cs
> +        public async void ReAdmin(ICommonSession session)
Комментарии

2024-11-26 14:23 UTC, FaDeOkno commented on Content.Server/Administration/Managers/AdminManager.cs
> +            }
Комментарии

2024-11-26 14:23 UTC, FaDeOkno commented on Content.Server/Administration/Managers/AdminManager.cs
> +        public async void DeAdmin(ICommonSession session)
Комментарии

2024-11-26 14:50 UTC, Schrodinger71 commented on Content.Server/Administration/Managers/AdminManager.cs
> +        public async void DeAdmin(ICommonSession session)
готово

2024-11-26 14:51 UTC, Schrodinger71 commented on Content.Server/Administration/Managers/AdminManager.cs
> +            }
Готово

2024-11-26 14:52 UTC, Schrodinger71 commented on Content.Server/Administration/Managers/AdminManager.cs
> +                    Content = $"**ОПОВЕЩЕНИЕ: Админ ВЫШЕЛ {senderName}**"
исправил

2024-11-26 14:57 UTC, Schrodinger71 commented on Content.Server/Chat/Managers/ChatManager.cs
> +    private async void SendAdminChat(ICommonSession player, string message)
да

2024-11-26 14:57 UTC, Schrodinger71 commented on Content.Server/Administration/Managers/AdminManager.cs
> +            }
да

2024-11-26 14:57 UTC, Schrodinger71 commented on Content.Server/Administration/Managers/AdminManager.cs
> +        public async void ReAdmin(ICommonSession session)
да

2024-12-05 09:25 UTC, Darkiich approved these changes
Какой ты молодец

2024-12-29 21:27 UTC, merged