Стаминдеф скафам, костюм кма и слайм
AdventureTimeSS14/space_station_ADT pull request #845
Opened 2024-11-27 07:14 UTC by Filokini

## Описание PR

Например: :cl: AruMoon

Используйте ключевые слова add, remove, tweak и fix.

2024-11-29 16:00 UTC, Bolper commented
![image](https://github.com/user-attachments/assets/676ca135-1928-4fae-952a-36e0f5f25207)
Ямал говорит чтоо чет не так
@Filokini

2024-12-02 14:07 UTC, PyotrIgn approved these changes

2024-12-02 14:08 UTC, PyotrIgn requested changes
Компонент стака для АДТшной бумаги

2024-12-02 16:02 UTC, Filokini commented
аппрувните но пока не мержите, мне кое-что проверить надо будет.

2024-12-03 12:44 UTC, PyotrIgn approved these changes

2024-12-03 12:44 UTC, merged