ъуъ
AdventureTimeSS14/space_station_ADT pull request #849
Opened 2024-11-27 20:51 UTC by Inconnu1337

## Описание PR

## Почему / Баланс

**Ссылка на публикацию в Discord**

## Техническая информация

## Медиа

## Требования

- [ ] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [ ] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

## Критические изменения

**Чейнджлог**

2024-11-27 20:59 UTC, Mirokko requested changes
Серьезных проблем я не нашел. Я не тестил это локально, если что.

2024-11-27 20:59 UTC, Mirokko commented on Content.Server/ADT/WW1/AirStrikeSystem.cs
> +            _popup.PopupEntity("Артиллерийный удар уже активирован!", args.User);
Хардкод перевода тут и ниже

2024-11-27 21:00 UTC, Darkiich commented
А нахуй нам мортира?

2024-11-29 16:58 UTC, Mirokko approved these changes

2024-11-29 16:58 UTC, Mirokko commented
Аналогично. Выглядит норм, но я не имею возможности затестить локально. Хорошо бы кто-то затестил

2024-11-29 16:58 UTC, Mirokko commented
> А нахуй нам мортира?

А почему нет?

2025-01-26 21:59 UTC, Inconnu1337 commented
alo blyat its DRAFT
dont trogat naxyi

2025-04-08 19:48 UTC, Unlumy commented
Blackout

2025-04-08 19:48 UTC, closed without merging