[SHIPBATTLE] Корабельные пушки
AdventureTimeSS14/space_station_ADT pull request #862
Opened 2024-12-01 00:49 UTC by PyotrIgn

## Описание PR
Добавление прототипов корабельных пушек для космических боев

## Почему / Баланс
Потому что мне нужна ДАККА

**Чейнджлог**
:cl: Пётр
- add: Добавлена малая корабельная турель GAU-32

2024-12-16 19:29 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/ADTGlobalEvents/ShipBattle/Prototypes/Entities/Objects/Weapons/Guns/ship_gun.ftl
> +    .desc = Корабельный зенитный комплекс GAU-32. Кажется для этой турели война уже закончена. Восстановлению не подлежит.
Пофиксил

2024-12-27 09:04 UTC, Filokini commented
А аттрибутионс у звуков нема?

2024-12-28 05:40 UTC, PyotrIgn commented
> А аттрибутионс у звуков нема?

Взяты из бесплатных библиотек или сшиты из кусков разного взятого из бесплатных. И в них оно без конкретного авторства

2024-12-28 08:46 UTC, Ratyyy requested changes
собственно ревью

2024-12-28 08:47 UTC, Ratyyy requested changes
собственно ревью

2024-12-28 08:47 UTC, Ratyyy commented on Resources/Audio/ADT/ADTGlobalEvents/ShipBattle/Weapons/Guns/turret_destroy.ogg
лицензию забыли

2024-12-28 23:25 UTC, KashRas2 approved these changes
![53tcyc.jpg](https://github.com/user-attachments/assets/c9521ebf-1660-40f1-8b28-f51006ec6342)

2024-12-29 02:44 UTC, PyotrIgn commented on Resources/Audio/ADT/ADTGlobalEvents/ShipBattle/Weapons/Guns/turret_destroy.ogg
Решено

2024-12-29 03:28 UTC, merged