Самодельные щиты, шапки, чай, и просто сборник случайного контента
AdventureTimeSS14/space_station_ADT pull request #873
Opened 2024-12-03 13:54 UTC by sh4zik

## Описание PR
Добавление двуручных щитов как самодельных так и синдикековских, синдикековская пицца в аплинке, новые чаи и система его готовки, шапки, и ещё пару вещей по мелочам

## Почему / Баланс
Разнообразие сервера контентом, потому что, почему бы и нет?

## Требования

- [x] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [x] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

**Чейнджлог**

:cl: Sh4zik
- add: Были добавлены несколько самодельных рецептов копей и заточек, из армированного урана и плазмы
- add: Была добавлена возможность скрафтить новый предмет - самодельный двуручный щит
- add: Был добавлен штурмовой двуручный щит синдиката в аплинк ядерного оперативника
- add: Был добавлен новый предмет - чайник для бармена, который используется для создания новых видов чая
- add: Были добавлены зимние шапки в Зимнемат
- add: Была добавлена пицца с омнизином в аплинк синдиката, в разделе безделушек
- add: Было добавлено три новых видов чая - Апельсиновый, Вишнёвый, А также арбузный..

2024-12-03 18:22 UTC, sh4zik commented
После проверки на локальном сервере проблем я не заметил, Без понятия почему именно YAML выдаёт ошибку, но должно быть, всё работает как нужно

2024-12-03 23:00 UTC, sh4zik commented
> @sh4zik у тебя в FTL ошибки. Нельзя иметь заглавные буквы. У тебя `Tea` и т.д имеют заглавные буквы.

Похоже, проблема не в этом, все заглавные буквы я успешно убрал, но Linter всё ещё жалуется на всё ту же проблему, в чём она заключается я и понять не могу, всё относительно должно работать как и планировалось

2024-12-04 13:14 UTC, sh4zik commented
what.. Опять YAML на что-то жалуется, на то, что не должно..

2024-12-05 19:41 UTC, Unlumy commented
@CrimeMoot Не знаю кто ты... Но ты легенда, получается. Раз появился из неоткуда и делаешь ревью.

2024-12-05 20:06 UTC, Filokini commented
ну у тебя проблема с крафтами походу

2024-12-09 19:44 UTC, sh4zik commented
Всё готово, Требуется ревью.. Также хочу выразить благодарность CrimeMoot, Не знаю кто ты, Но благодарю за помощь

2024-12-10 10:25 UTC, PyotrIgn requested changes

2024-12-10 10:25 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/prototypes/Catalog/store/uplink-catalog.ftl
> +uplink-nukiesShield-name = двуручный штурмовый щит
поправить орфографию - штурмовой
переформулировать описание, слишком много "превосходительных" характеристик

2024-12-10 10:25 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/prototypes/Catalog/store/uplink-catalog.ftl
> +uplink-omnizinpizza-desc = Это самая обычная коробка, с самой обычной пиццей внутри, это именно то, что используют элитные агенты для перекуса между стрельбой с капитаном, и кражей Иана.
Тут также. Перепроверить пунктуацию и подумать над формулировкой

2024-12-10 10:25 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Consumable/Food/containers.ftl
> +    .desc = Довольно большая коробка с пиццей синдиката внутри, возможно, тот кто ест эту пиццу настоящий безсердечный ублюдок, но её вкус замечателен.
Орфография!

2024-12-10 10:25 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Consumable/Food/teapacks.ftl
> +ent-ADTOrangeTeapack = пакетик сиропа апельсинового чая
пропущено "для"
поработать над описаниями всеми

2024-12-10 10:25 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Shields/shields.ftl
> +    .desc = Обладает довольно массивной защитой для носителя, выглядит громостко, но выполняет свою работу
"Массивная защита"? Это как? 

"Громостко" - орфография

2024-12-10 10:25 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Shields/shields.ftl
> +ent-ADTFullRiotShieldSyndicate = штурмовый двуручный щит синдиката
"штурмовой"
и другие приколы орфографии

2024-12-10 10:25 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Weapons/Melee/melee.ftl
> +    .desc = Копьё созданное из осколка закалённого урана, для более удобной нарезки ваших оппонентов.
Нарезка копьем? 
Запятая пропущена в начале

2024-12-10 10:25 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Weapons/Melee/melee.ftl
> +    .desc = Заточка созданная из осколка закалённого урана, имеющий тканневую основу, для более удобной нарезки ваших оппонентов.
То же ,что и выше

2024-12-10 10:25 UTC, PyotrIgn commented on Resources/Locale/ru-RU/ADT/prototypes/Entities/Structures/Machines/batmenkettle.ftl
> +    .desc = Этот ультрасовременный технологический шедевр — чайник (Обычная грелка собранная из металлолома), который не просто кипятит воду, а выводит ежедневный комфорт на новый уровень! (Он потреб
орфография и пунктуация описания

2024-12-10 10:25 UTC, PyotrIgn commented on Resources/Prototypes/ADT/Entities/Objects/Consumable/Drinks/drinks.yml
> +- type: entity
добавить пробелы между энтити

2024-12-12 22:10 UTC, PyotrIgn commented on Resources/Prototypes/ADT/Recipes/Reactions/drinks.yml
> +      amount: 29
Подобный реагент приготовить будет крайне сложно - 29 воды налить в стакан можно, но крайне сложно - обычно жидкости наливаются по 5 единиц

Предлагаю сделать либо 25 к 1 реакцию
либо 5 единиц сиропа в пакетике, и тогда 25 воды и 5 сиропа

2024-12-12 23:06 UTC, merged