[FIX, ADD] Снова лоудауты, фары для шаттлов, спрайт болы в руках, спрайты кнопок, пульты управления шаттлами
AdventureTimeSS14/space_station_ADT pull request #884
Opened 2024-12-10 13:50 UTC by jungarikjan

## Описание PR
Лабораторный халат возвращён учёным
Форма офицера-инструктора недоступна другим должностям СБ
Спрайт болы в руках
Фары для шаттлов
Исправлено положение спрайтов кнопок, каркасов, кнопок на замке
Пульты управления шаттлами
Фикс локали [ПРа 773](https://github.com/AdventureTimeSS14/space_station_ADT/issues/773)

## Почему / Баланс
Кнопки и всё остальное теперь выглядит нормально, по-человечески. Ты подходишь к стене, кнопка к тебе близко. Логично.
TODO: то же самое с пожарной сигнализацией надо сделать, но я там в спрайтах потерялся. Пожалуйста, сделайте в следующей обнове

**Ссылка на публикацию в Discord**
- [Заказы в разработку](https://discord.com/channels/901772674865455115/1314286567912640542)
- [Предложения](https://discord.com/channels/901772674865455115/1307080461591253114)
- [Предложения](https://discord.com/channels/901772674865455115/1305627106792702093)

## Техническая информация
ы

## Медиа
### БОЛА
![image](https://github.com/user-attachments/assets/8b89a3c8-9f20-470a-8a28-162e7b6e53ee) ![image](https://github.com/user-attachments/assets/7a2ef118-f0c7-4218-9214-16b9f155967c)
![image](https://github.com/user-attachments/assets/181a901c-d100-4033-ae60-4b964eabdd50) ![image](https://github.com/user-attachments/assets/e667d0ea-a07e-42b3-b613-72844f5487b6)

### КНОПКИ
ДО:
![image](https://github.com/user-attachments/assets/3473f747-faba-4926-b15d-3921e0597988)
ПОСЛЕ:
![image](https://github.com/user-attachments/assets/3032c85e-d629-430b-a936-04fca3993c79)

### КНОПКИ ДЕМОНСТРАЦИЯ
![image](https://github.com/user-attachments/assets/93553449-7ce4-4a54-9998-f29292d21684) ![image](https://github.com/user-attachments/assets/a62615a2-02e9-4b94-b770-e92467b71a76)
![image](https://github.com/user-attachments/assets/6d9100da-cd15-4e89-bf8d-005892023893) ![image](https://github.com/user-attachments/assets/918b6d06-9519-448d-8a1a-814c14c7894e)

### ПУЛЬТЫ УПРАВЛЕНИЯ ШАТТЛАМИ - РАБОТАЮТ
![image](https://github.com/user-attachments/assets/1692a3b4-a216-4f8f-b75f-6df4c0ea7441)
![image](https://github.com/user-attachments/assets/42db146f-ab09-41b8-9cad-33201ef46f47)
![image](https://github.com/user-attachments/assets/13888645-eef9-4160-a161-6ddacb344f55)

### ЛОУДАУТЫ И ШКАФЫ
шкаф ГСБ
![image](https://github.com/user-attachments/assets/c5baccec-3a8b-490e-a776-f58bd86e8b23)
шкаф КМ
![image](https://github.com/user-attachments/assets/fea80adc-29f8-4692-af92-b92beb955439)
лоудаут КОМАНДИРА ЯО
![image](https://github.com/user-attachments/assets/e8ae6f0d-b714-4958-8130-af948782a947)

### РЕСПРАЙТНУЛ СИНДИ ПУЛЬТ ШАТТЛА
![image](https://github.com/user-attachments/assets/aca8e4a4-2eff-44f4-b61b-ff314d873387)

### ФИКС ЛОКАЛИ 
![image](https://github.com/user-attachments/assets/1b7f6a84-17f2-41f5-91e5-9e98658afdd0)

### ФАРА ШАТТЛА
Всё нормально, она так и должна спавниться будто бы в стене, на краю
![image](https://github.com/user-attachments/assets/58c55cc4-73c5-471d-b7f8-3e24a940ad06)

## Требования
- [X] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [X] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

## Критические изменения
ы

**Чейнджлог**
:cl: eddiemercury
- tweak: Учёным возвращен лабораторный халат. У доцента - только халат учёного. У НРа - халат НРа
- fix: Одежда офицера-инструктора недоступна остальным в СБ
- fix: Спрайты кнопок, каркасов, замков кнопок
- fix: Робототехнику необязательно спавниться с кепкой. Фикс minLimit maxLimit
- fix: Фикс правил командных антагов после ПРа Кэйси...
- add: Фары для шаттлов. Отдельное спасибо discord: @prazat911
- add: Спрайт для болы в руках. Отдельное спасибо discord: @hixi.
- add: Пульты управления шаттлами утилей, СБ, ЯО. Добавлены в шкаф ГСБ, шкаф КМа и рюкзак КомЯО соответственно. Пульты утильского и СБ - цели антагов. За спрайты спасибо Петру!

2024-12-12 10:58 UTC, Inconnu1337 requested changes
в

2024-12-12 10:58 UTC, Inconnu1337 commented on Resources/Prototypes/ADT/Entities/Objects/Specific/handheldshuttleconsole.yml
> +  - type: Computer
не надо

2024-12-12 10:58 UTC, Inconnu1337 commented on Resources/Prototypes/ADT/Entities/Objects/Specific/handheldshuttleconsole.yml
> +        name: power-cell-slot-component-slot-name-default
батарейку по стандарту маленькую пихни

2024-12-12 10:58 UTC, Inconnu1337 commented on Resources/Prototypes/ADT/Entities/Objects/Specific/handheldshuttleconsole.yml
> +  - type: Computer
везде компутер удалить

2024-12-12 10:58 UTC, Inconnu1337 commented on Resources/Prototypes/ADT/Entities/Objects/Specific/handheldshuttleconsole.yml
> +      - type: SalvageShuttle
утильский сделал, а карго нет

2024-12-12 10:59 UTC, Inconnu1337 commented on Resources/Prototypes/ADT/Entities/Objects/Specific/handheldshuttleconsole.yml
> +  - type: Computer
(computer не надо)

2024-12-13 11:54 UTC, PyotrIgn commented
Чинить билдтест

2024-12-14 13:16 UTC, Inconnu1337 approved these changes
ny mbok

2024-12-14 17:52 UTC, merged