Починка некоторых вещей, и добавление новогодних предметов
AdventureTimeSS14/space_station_ADT pull request #897
Opened 2024-12-18 13:45 UTC by sh4zik

## Описание PR
Добавление новогодних штучек, по заказу Pangaari, А также фиксы моего предыдущего ПРа

## Почему / Баланс
Разнообразие сервера контентом, потому что, почему бы и нет, ну и починка этого разнообразного контента

## Требования

- [x] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [x] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

**Чейнджлог**

:cl: Sh4zik
- add: Был добавлен снежок
- add: Был добавлен огромный ящик, заполненным снегом
- add: Были добавлены превосходные, зимние сани
- add: Был добавлен ????? из слаймолюдов.
- add: Было добавлено новогоднее настроение!
- add: Была добавлены различные вариации кинжалов
- add: Была добавлена возможность скрафтить новые виды вооружения - кинжалы
- fix: Были починены крафты закалённых копей и заточек, а также их урон

2024-12-19 16:57 UTC, Schrodinger71 commented
Даа надо бы поднять вопрос о том, чтобы не создавать излишне громоздкие пулл-реквесты

2024-12-19 20:10 UTC, sh4zik commented
Ну, Я глупый, Но на будущее запомню больше так не делать

2024-12-20 04:45 UTC, Darkiich requested changes
Ревью

2024-12-20 04:45 UTC, Darkiich commented on Resources/Prototypes/ADT/Entities/Objects/Misc/newyearkatalki.yml
> +- type: entity
Это перенеси в Resources/Prototypes/ADT/Entities/Objects/Fun/misc.yml

2024-12-20 04:45 UTC, Darkiich commented on Resources/Prototypes/ADT/Entities/Objects/Misc/slimehappines.yml
> +- type: entity
Это перенеси в Resources/Prototypes/ADT/Entities/Objects/Fun/misc.yml

2024-12-20 04:45 UTC, Darkiich commented on Resources/Prototypes/ADT/Entities/Structures/Storage/Crates/snowballcrate.yml
> +    - ADTSnowball
Ухты бля. Надеюсь так можно делать

2024-12-20 04:45 UTC, Darkiich commented on Resources/Textures/ADT/Objects/Fun/snowball.rsi/meta.json
> +    "license": "CC-BY-SA-3.0",
Тут укажи автора, кто делал спрайты. По сути это Ранга, если она не брала откуда-то спрайты

2024-12-20 04:45 UTC, Darkiich commented on Resources/Textures/ADT/Objects/Misc/slimehappines.rsi/meta.json
> +    "copyright": "Created by discord:KING_DICE#4881, prazat911",
Если это был празат, то оставь, если нет, то поменяй

2024-12-20 04:45 UTC, Darkiich commented on Resources/Textures/ADT/Objects/Specific/snowdispenser.rsi/meta.json
> +    "size": {
Тут так же

2024-12-20 04:45 UTC, Darkiich commented on Resources/Textures/ADT/Structures/Specific/newyearkatalki.rsi/meta.json
> +    "size": {
Буэ, точно так же

2024-12-20 08:36 UTC, sh4zik commented on Resources/Prototypes/ADT/Entities/Structures/Storage/Crates/snowballcrate.yml
> +    - ADTSnowball
Ну, Прототип является именно таким, вписать определённое количество снежков не получится, требуется заполнять таким образом

2024-12-20 08:47 UTC, sh4zik commented
По какой-то, не понятной для меня причине гитхаб отказывается удалять пустые файлы, сам файл существует, но в нём ничего нет, как-то в целом странно гитхаб работает сегодня, но всё же

2024-12-20 12:09 UTC, Schrodinger71 commented on Resources/Prototypes/ADT/Entities/Structures/Storage/Crates/snowballcrate.yml
> +    - ADTSnowball
так..

2024-12-20 14:29 UTC, Darkiich commented
> По какой-то, не понятной для меня причине гитхаб отказывается удалять пустые файлы, сам файл существует, но в нём ничего нет, как-то в целом странно гитхаб работает сегодня, но всё же

Мгм, потом не забудь удалить через VSC

2024-12-20 14:29 UTC, Darkiich approved these changes
Боже, ты красаууучик

2024-12-20 14:30 UTC, merged