[Update] Buff Xeno
AdventureTimeSS14/space_station_ADT pull request #900
Opened 2024-12-18 16:23 UTC by NameLunar

## Описание PR

Увеличено здоровье ксеноморфам.
Добавлена способность ставить турельки у королевы.

**Ссылка на публикацию в Discord**
- [Заказы-разработка] https://discord.com/channels/901772674865455115/1318583251933331569

## Техническая информация
Попытался добавить ивент по шаблону ивента мима. Не получилось, не видел прототип ивента. (Сам ивент видел).
Добавил способность королеве на основе невидимой стены мима. Она может раз в 3 минуты призвать турель с 100 хп. (К сожалению спрайт стенки у кнопки. Да.)

## Требования
- [x] Я прочитал(а) и следую [Руководство по созданию пулл реквестов](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). Я понимаю, что в противном случае мой ПР может быть закрыт по усмотрению мейнтейнера.
- [x] Я добавил скриншоты/видео к этому пулл реквесту, демонстрирующие его изменения в игре, **или** этот пулл реквест не требует демонстрации в игре

**Чейнджлог**
:cl: NameLunar
- fix: Ксеноморфы эволюционировали и стали намного опасней. 
- add: Временно добавлено создание турелей для королевы ксеноморфов.

2024-12-18 16:52 UTC, NameLunar commented
Если мне помогут с ошибкой в ивенте, то я буду очень рад 😢

2024-12-19 03:06 UTC, Filokini commented
Вопрос как теперь утилизаторам с ксено воевать.

2024-12-19 03:43 UTC, NameLunar commented
Хардкооор

2024-12-19 03:43 UTC, NameLunar commented
Они не быстрее обычного человека. Думаю справятся

2024-12-19 03:51 UTC, Filokini commented
> Они не быстрее обычного человека. Думаю справятся

Напиши в ченжлоге не изменены харакстеристики, а усиленны

2024-12-19 03:55 UTC, NameLunar commented
А атк)?

2024-12-19 04:04 UTC, Filokini commented
> А атк)?

сойдет.

2024-12-19 14:00 UTC, NameLunar commented
> > А атк)?
> 
> сойдет.

2024-12-19 16:16 UTC, Schrodinger71 commented on Content.Server/Abilities/XenoQeen/XenoQeenSystem.cs
> +        private void OnInvisibleWall(EntityUid uid, XenoQeenComponent component, InvisibleWallActionEvent args)
Название функции думаю тут другое нужно..

2024-12-19 16:32 UTC, NameLunar commented on Content.Server/Abilities/XenoQeen/XenoQeenSystem.cs
> +        private void OnInvisibleWall(EntityUid uid, XenoQeenComponent component, InvisibleWallActionEvent args)
Хм... Возможно)
Исправлю, если оставлю

2024-12-19 16:42 UTC, Schrodinger71 requested changes

2024-12-19 16:42 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +        Brute: 8
Вот так желательно, чтобы не стёр случайно никто
```yml
  # ADT Start: Xeno baaf
  - type: MeleeWeapon
    damage:
      groups:
        Brute: 8  
  # ADT End

2024-12-19 16:42 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +      350: Dead
350: Dead # ADT Tweak

2024-12-19 16:42 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +      100: Dead
100: Dead # ADT Tweak

2024-12-19 16:42 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +        Brute: 5
Brute: 5 # ADT Tweak

2024-12-19 16:42 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +  - type: XenoQeen # Способность спавнта турелей
- type: XenoQeen # ADT Tweak: Способность спавнта турелей

2024-12-19 16:42 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +      1000: Dead
1000: Dead # ADT Tweak

2024-12-19 16:42 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +       Brute: 20
Brute: 20 # ADT TWEak

2024-12-19 16:42 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> -
зачем тут пробел убрали

2024-12-19 16:42 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +      750: Dead
750: Dead # ADT Tweak

2024-12-19 16:42 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +    baseSprintSpeed: 2
baseSprintSpeed: 2 # ADT Tweak

2024-12-19 16:42 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +       Brute: 30
Brute: 30 # ADT TWeak

2024-12-19 16:42 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +      100: Dead
```yml
  # ADT Start: Xeno baaf
  - type: MobThresholds
    thresholds:
      0: Alive
      100: Dead
 # ADT End
```

2024-12-19 16:42 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +    baseSprintSpeed: 12.0
baseSprintSpeed: 12.0 # ADT Tweak

2024-12-19 16:42 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +      80: Dead
80: Dead # ADT Tweak

2024-12-19 16:42 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
> +          Caustic: 12
Caustic: 12 # ADT Tweak

2024-12-20 10:27 UTC, NameLunar commented
Люди добрые, одобрите и обновите. Там человек инвент провести хочет 🥹

2024-12-21 13:27 UTC, Schrodinger71 commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> -
гуд

2024-12-21 13:41 UTC, Schrodinger71 approved these changes
Все мои требования выполнены, раз никто не появился) можн мерджить

2024-12-21 13:42 UTC, merged